import { PrismaService } from '../../common/prisma/prisma.service';
import { CreateGosiConfigDto } from './dto/create-gosi-config.dto';
export declare class GosiService {
    private prisma;
    constructor(prisma: PrismaService);
    create(dto: CreateGosiConfigDto, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        employeeRate: import("@prisma/client/runtime/library").Decimal;
        employerRate: import("@prisma/client/runtime/library").Decimal;
        sanedRate: import("@prisma/client/runtime/library").Decimal;
        hazardRate: import("@prisma/client/runtime/library").Decimal;
        maxCapAmount: import("@prisma/client/runtime/library").Decimal;
        minBaseSalary: import("@prisma/client/runtime/library").Decimal;
        isSaudiOnly: boolean;
        includeAllowances: boolean;
        notes: string | null;
    }>;
    getActiveConfig(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        employeeRate: import("@prisma/client/runtime/library").Decimal;
        employerRate: import("@prisma/client/runtime/library").Decimal;
        sanedRate: import("@prisma/client/runtime/library").Decimal;
        hazardRate: import("@prisma/client/runtime/library").Decimal;
        maxCapAmount: import("@prisma/client/runtime/library").Decimal;
        minBaseSalary: import("@prisma/client/runtime/library").Decimal;
        isSaudiOnly: boolean;
        includeAllowances: boolean;
        notes: string | null;
    } | null>;
    findAll(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        employeeRate: import("@prisma/client/runtime/library").Decimal;
        employerRate: import("@prisma/client/runtime/library").Decimal;
        sanedRate: import("@prisma/client/runtime/library").Decimal;
        hazardRate: import("@prisma/client/runtime/library").Decimal;
        maxCapAmount: import("@prisma/client/runtime/library").Decimal;
        minBaseSalary: import("@prisma/client/runtime/library").Decimal;
        isSaudiOnly: boolean;
        includeAllowances: boolean;
        notes: string | null;
    }[]>;
    update(id: string, dto: Partial<CreateGosiConfigDto>, companyId: string, userId?: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        employeeRate: import("@prisma/client/runtime/library").Decimal;
        employerRate: import("@prisma/client/runtime/library").Decimal;
        sanedRate: import("@prisma/client/runtime/library").Decimal;
        hazardRate: import("@prisma/client/runtime/library").Decimal;
        maxCapAmount: import("@prisma/client/runtime/library").Decimal;
        minBaseSalary: import("@prisma/client/runtime/library").Decimal;
        isSaudiOnly: boolean;
        includeAllowances: boolean;
        notes: string | null;
    }>;
}
