import { Request } from 'express';
import { LettersService } from './letters.service';
import { CreateLetterRequestDto } from './dto/create-letter-request.dto';
import { LetterQueryDto } from './dto/letter-query.dto';
import { UploadService } from '../../common/upload/upload.service';
export declare class LettersController {
    private readonly lettersService;
    private readonly uploadService;
    constructor(lettersService: LettersService, uploadService: UploadService);
    uploadAttachments(files: Express.Multer.File[]): Promise<{
        message: string;
        files: import("../../common/upload/upload.service").UploadedFile[];
    }>;
    createLetterRequest(userId: string, createLetterDto: CreateLetterRequestDto, req: Request): Promise<{
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            managerId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    }>;
    getMyLetterRequests(userId: string, query: LetterQueryDto): Promise<{
        data: ({
            approver: {
                id: string;
                firstName: string;
                lastName: string;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.LetterStatus;
            companyId: string | null;
            type: import(".prisma/client").$Enums.LetterType;
            notes: string | null;
            userId: string;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            currentStep: import(".prisma/client").$Enums.ApprovalStep;
            managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
            managerDecisionAt: Date | null;
            managerNotes: string | null;
            managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
            hrDecisionAt: Date | null;
            hrDecisionNotes: string | null;
            hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            approverNotes: string | null;
            approvedAt: Date | null;
            managerApproverId: string | null;
            hrApproverId: string | null;
            approverId: string | null;
        })[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    getLetterRequestById(id: string, userId: string): Promise<{
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            department: {
                name: string;
            } | null;
        };
        approver: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    }>;
    cancelLetterRequest(id: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    }>;
    getPendingRequests(userId: string, companyId: string, query: LetterQueryDto): Promise<{
        data: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
                jobTitle: string | null;
                department: {
                    name: string;
                } | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.LetterStatus;
            companyId: string | null;
            type: import(".prisma/client").$Enums.LetterType;
            notes: string | null;
            userId: string;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            currentStep: import(".prisma/client").$Enums.ApprovalStep;
            managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
            managerDecisionAt: Date | null;
            managerNotes: string | null;
            managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
            hrDecisionAt: Date | null;
            hrDecisionNotes: string | null;
            hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            approverNotes: string | null;
            approvedAt: Date | null;
            managerApproverId: string | null;
            hrApproverId: string | null;
            approverId: string | null;
        })[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    approveLetterRequest(id: string, approverId: string, body: {
        notes?: string;
        attachments?: any[];
    }): Promise<{
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    }>;
    rejectLetterRequest(id: string, approverId: string, body: {
        notes?: string;
        attachments?: any[];
    }): Promise<{
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    }>;
    getManagerInbox(managerId: string, companyId: string): Promise<({
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    })[]>;
    getHRInbox(hrUserId: string, companyId: string): Promise<({
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    })[]>;
    managerDecision(id: string, managerId: string, body: {
        decision: 'APPROVED' | 'REJECTED';
        notes?: string;
        attachments?: any[];
    }): Promise<{
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    }>;
    hrDecision(id: string, hrUserId: string, body: {
        decision: 'APPROVED' | 'REJECTED' | 'DELAYED';
        notes?: string;
        attachments?: any[];
    }): Promise<{
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    }>;
}
