import { PrismaService } from '../../common/prisma/prisma.service';
import { WpsStatus } from '@prisma/client';
import { StatusLogService } from '../../common/services/status-log.service';
import { StateMachineService } from '../../common/services/state-machine.service';
interface CreateWpsSubmissionDto {
    payrollRunId: string;
    filename: string;
    fileFormat?: string;
    fileUrl?: string;
    fileHashSha256?: string;
}
interface UpdateWpsStatusDto {
    status: WpsStatus;
    bankName?: string;
    bankRef?: string;
    attachmentUrl?: string;
    notes?: string;
    reason?: string;
}
export declare class WpsTrackingService {
    private prisma;
    private statusLogService;
    private stateMachineService;
    constructor(prisma: PrismaService, statusLogService: StatusLogService, stateMachineService: StateMachineService);
    createSubmission(dto: CreateWpsSubmissionDto, companyId: string, userId: string): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
    updateStatus(id: string, dto: UpdateWpsStatusDto, companyId: string, userId?: string): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
    findAll(companyId: string, status?: WpsStatus): Promise<({
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    })[]>;
    findOne(id: string, companyId: string): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
    findByPayrollRun(payrollRunId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }[]>;
    getStats(companyId: string, year?: number): Promise<{
        total: number;
        generated: number;
        downloaded: number;
        submitted: number;
        processing: number;
        processed: number;
        failed: number;
        totalAmount: number;
    }>;
    markAsDownloaded(id: string, companyId: string): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
}
export {};
