import { WpsTrackingService } from './wps-tracking.service';
export declare class WpsTrackingController {
    private readonly wpsTrackingService;
    constructor(wpsTrackingService: WpsTrackingService);
    create(dto: any, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
    findAll(req: any, status?: string): Promise<({
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    })[]>;
    getStats(req: any, year?: string): Promise<{
        total: number;
        generated: number;
        downloaded: number;
        submitted: number;
        processing: number;
        processed: number;
        failed: number;
        totalAmount: number;
    }>;
    findByRun(runId: string, req: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }[]>;
    findOne(id: string, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
    updateStatus(id: string, dto: any, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
    approveProcessing(id: string, dto: any, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
    markDownloaded(id: string, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.WpsStatus;
        companyId: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        bankName: string | null;
        fileUrl: string | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        errors: import("@prisma/client/runtime/library").JsonValue | null;
        employeeCount: number;
        fileHashSha256: string | null;
        generatorVersion: string | null;
        filename: string;
        fileFormat: string;
        bankRef: string | null;
        generatedAt: Date;
        generatedBy: string | null;
        downloadedAt: Date | null;
        downloadedBy: string | null;
        processedAt: Date | null;
        attachmentUrl: string | null;
    }>;
}
