import { PrismaService } from '../../common/prisma/prisma.service';
import { CreateCompanyBankAccountDto, UpdateCompanyBankAccountDto } from './dto/company-bank-account.dto';
export declare const SAUDI_BANKS: {
    code: string;
    name: string;
    swift: string;
}[];
export declare class CompanyBankAccountsService {
    private prisma;
    constructor(prisma: PrismaService);
    create(companyId: string, dto: CreateCompanyBankAccountDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    findAll(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }[]>;
    findActive(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }[]>;
    findPrimary(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    } | null>;
    findOne(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    update(id: string, companyId: string, dto: UpdateCompanyBankAccountDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    setPrimary(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    toggleActive(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    remove(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    getSaudiBanks(): {
        code: string;
        name: string;
        swift: string;
    }[];
}
