import { CompanyBankAccountsService } from './company-bank-accounts.service';
import { CreateCompanyBankAccountDto, UpdateCompanyBankAccountDto } from './dto/company-bank-account.dto';
export declare class CompanyBankAccountsController {
    private readonly service;
    constructor(service: CompanyBankAccountsService);
    create(dto: CreateCompanyBankAccountDto, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    findAll(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }[]>;
    findActive(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }[]>;
    findPrimary(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    } | null>;
    getSaudiBanks(): {
        code: string;
        name: string;
        swift: string;
    }[];
    findOne(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    update(id: string, dto: UpdateCompanyBankAccountDto, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    setPrimary(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    toggleActive(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
    remove(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        isActive: boolean;
        notes: string | null;
        iban: string;
        bankName: string;
        bankCode: string;
        swiftCode: string | null;
        isPrimary: boolean;
        accountName: string;
        molId: string | null;
        wpsParticipant: string | null;
        accountType: string;
        currency: string;
    }>;
}
