import { PrismaService } from '../../common/prisma/prisma.service';
import { AiService } from '../ai/ai.service';
export interface ToolDefinition {
    name: string;
    description: string;
    parameters: Record<string, {
        type: string;
        description: string;
        required?: boolean;
    }>;
    requiredRole: string[];
}
export interface ToolResult {
    success: boolean;
    message: string;
    data?: any;
}
export declare class AiAgentToolsService {
    private readonly prisma;
    private readonly aiService;
    private readonly logger;
    constructor(prisma: PrismaService, aiService: AiService);
    getAvailableTools(): ToolDefinition[];
    executeTool(toolName: string, params: Record<string, any>, context: {
        companyId: string;
        userId: string;
        userRole: string;
    }): Promise<ToolResult>;
    private createEmployee;
    private updateEmployee;
    private deleteEmployee;
    private listEmployees;
    private createTask;
    private createLeaveRequest;
    private approveLeave;
    private queryCount;
    private attendanceReport;
    private lateEmployees;
    private topSalaries;
    private leaveStatistics;
    private attendanceSummary;
    private employeeSearch;
    private readonly BASE_PATH;
    private readFile;
    private listDirectory;
    private searchCode;
    private getFileOutline;
    private writeFile;
    private modifyFile;
    private createModule;
    private capitalize;
    private restartBackend;
    private gitStatus;
    private systemInfo;
    private predictTurnover;
    private salaryAnalysis;
    private anomalyDetection;
    private workloadAnalysis;
    private sendNotification;
    private broadcastMessage;
    private createReminder;
    private sendSummaryReport;
    private exportData;
    private databaseStats;
    private backupStatus;
    private apiHealth;
    private quickActions;
    private smartSuggestions;
    private helpCommands;
    private batchApproveLeaves;
    private dailyDigest;
    private autoReminder;
    private attendanceDetailedReport;
    private salaryBreakdown;
    private departmentReport;
    private monthlyComparison;
    private addBonus;
    private addDeduction;
    private payrollStatus;
    private calculateOvertime;
    private createShift;
    private listShifts;
    private assignShift;
    private todayShifts;
    private companyHolidays;
    private upcomingEvents;
    private birthdaysThisMonth;
    private workAnniversaries;
    private requestAdvance;
    private pendingAdvances;
    private employeeLoans;
    private loanSummary;
    private employeeKpis;
    private departmentPerformance;
    private topPerformers;
    private performanceComparison;
    private generateContract;
    private generateCertificate;
    private generateSalarySlip;
    private generateWarningLetter;
    private userPermissions;
    private activeSessions;
    private loginHistory;
    private systemAudit;
    private attendanceForecast;
    private budgetForecast;
    private hiringNeeds;
    private turnoverPrediction;
    private bulkUpdateSalaries;
    private bulkAssignDepartment;
    private archiveOldRecords;
    private cleanupDuplicates;
    private sendWelcomeEmail;
    private sendReminderEmail;
    private emailTemplates;
    private emailHistory;
    private sendSms;
    private smsBalance;
    private smsHistory;
    private bulkSms;
    private createAlert;
    private activeAlerts;
    private alertHistory;
    private disableAlert;
    private dashboardSummary;
    private quickStats;
    private todayOverview;
    private weeklyReport;
    private exportEmployees;
    private exportAttendance;
    private importStatus;
    private dataValidation;
    private createWorkflow;
    private listWorkflows;
    private runWorkflow;
    private workflowHistory;
    private createForm;
    private listForms;
    private formResponses;
    private formAnalytics;
    private setGoal;
    private goalProgress;
    private teamGoals;
    private okrSummary;
    private sendTeamMessage;
    private teamAnnouncements;
    private directMessage;
    private chatHistory;
    private aiRecommendations;
    private patternAnalysis;
    private riskAssessment;
    private improvementSuggestions;
    private addDepartment;
    private addBranch;
    private addPosition;
    private addLeaveType;
    private addHoliday;
    private addPolicy;
    private addAttendanceManual;
    private addOvertimeRequest;
    private addTask;
    private addAnnouncement;
    private addNote;
    private addTraining;
    private translateModuleName;
    private parseFieldWithType;
    private generateModule;
    private generatePrismaModel;
    private generateApiEndpoint;
    private generateFrontendPage;
    private generateCrudSystem;
    private listGeneratedModules;
    private runPrismaMigrate;
    private deployChanges;
    private findEmployeeByName;
    aiGenerateSystem(request: string, context: any): Promise<ToolResult>;
    private generateDtoTemplate;
    private generateServiceTemplate;
    private generateControllerTemplate;
    private generateModuleTemplate;
    private generateFrontendTemplate;
    private extractModuleNameFromRequest;
    isOpenCreationRequest(message: string): boolean;
    private autoRegisterModule;
    private autoAddRoute;
    private autoBuildAndRestart;
    aiFullAutoGenerate(request: string, context: any): Promise<ToolResult>;
    aiGeniusBuilder(request: string, context: any): Promise<ToolResult>;
    private aiAnalyzeAndPlan;
    private executeGeniusStep;
    private validateGeneratedCode;
    aiSelfHeal(moduleName: string): Promise<ToolResult>;
    aiLearnFromCodebase(): Promise<{
        patterns: any;
        modules: string[];
    }>;
    aiUnderstandIntent(message: string): Promise<{
        intent: string;
        params: any;
    }>;
    aiAutoDeploy(): Promise<ToolResult>;
    aiRunMigration(action?: 'push' | 'generate' | 'migrate'): Promise<ToolResult>;
    aiGitOperation(action: 'status' | 'commit' | 'push' | 'pull', message?: string): Promise<ToolResult>;
    aiCreateBackup(type?: 'database' | 'files' | 'full'): Promise<ToolResult>;
    aiMonitorSystem(): Promise<ToolResult>;
    aiViewLogs(service?: string, lines?: number): Promise<ToolResult>;
    aiTestApi(endpoint: string, method?: string): Promise<ToolResult>;
    aiExecuteCommand(command: string): Promise<ToolResult>;
    aiFileOperation(action: 'read' | 'write' | 'delete' | 'list', path: string, content?: string): Promise<ToolResult>;
    aiMasterCommand(message: string, context: any): Promise<ToolResult>;
    private readonly systemKnowledge;
    aiSmartEnhance(request: string, context: any): Promise<ToolResult>;
    private analyzeEnhancementRequest;
    private planModifications;
    private executeModifications;
    private modifyServiceFile;
    private modifyFrontendFile;
    private buildAndDeploy;
    isEnhancementRequest(message: string): boolean;
}
