import { PrismaService } from '../../common/prisma/prisma.service';
import { AiService } from '../ai/ai.service';
import { AiAgentToolsService } from './ai-agent-tools.service';
import { SecureCommandService, SecureFileService, InputValidationService, AIResponseValidatorService, RetryCircuitBreakerService, ConversationStorageService, ChatMessage, ErrorHandlerService, AIPromptManagerService, EnhancedIntentClassifierService, PerformanceOptimizationService, SmartFeaturesService, NaturalLanguageQueryService, ShiftManagementService, ExpenseManagementService, AnalyticsService, WellnessService, GamificationService, ITSupportService, LearningService, MeetingService, OnboardingService, FeedbackService, DocumentFinderService, CareerAdvisorService, MultiCulturalService, DailyBriefingService, PerformanceCoachService, NotificationsService, TeamCollaborationService, ComplianceAssistantService, PredictiveInsightsService, HRAssistantService, SmartSchedulerService, VoiceAccessibilityService, SocialEngagementService, IntegrationHubService, AdvancedAIService, ReportsBuilderService, EmergencyService, FacilitiesService, TravelExpensesService, MobileFeaturesService, DataExportService, AutomationRulesService, StatisticsDashboardService, SystemContextBuilderService, ActionExecutorService } from './security';
interface ChatResponse {
    response: string;
    suggestions?: string[];
    requestId: string;
    processingTime: number;
}
export declare class SecureAiChatService {
    private readonly prisma;
    private readonly aiService;
    private readonly commandService;
    private readonly fileService;
    private readonly inputValidator;
    private readonly responseValidator;
    private readonly retryService;
    private readonly conversationStorage;
    private readonly errorHandler;
    private readonly promptManager;
    private readonly intentClassifier;
    private readonly performanceOpt;
    private readonly agentTools;
    private readonly smartFeatures;
    private readonly nlQuery;
    private readonly shiftMgmt;
    private readonly expenseMgmt;
    private readonly analytics;
    private readonly wellness;
    private readonly gamification;
    private readonly itSupport;
    private readonly learning;
    private readonly meeting;
    private readonly onboarding;
    private readonly feedback;
    private readonly documentFinder;
    private readonly careerAdvisor;
    private readonly multiCultural;
    private readonly dailyBriefing;
    private readonly performanceCoach;
    private readonly notifications;
    private readonly teamCollab;
    private readonly compliance;
    private readonly predictive;
    private readonly hrAssistant;
    private readonly smartScheduler;
    private readonly voiceAccess;
    private readonly social;
    private readonly integrationHub;
    private readonly advancedAI;
    private readonly reportsBuilder;
    private readonly emergency;
    private readonly facilities;
    private readonly travelExpenses;
    private readonly mobileFeatures;
    private readonly dataExport;
    private readonly automationRules;
    private readonly statsDashboard;
    private readonly systemContext;
    private readonly actionExecutor;
    private readonly logger;
    constructor(prisma: PrismaService, aiService: AiService, commandService: SecureCommandService, fileService: SecureFileService, inputValidator: InputValidationService, responseValidator: AIResponseValidatorService, retryService: RetryCircuitBreakerService, conversationStorage: ConversationStorageService, errorHandler: ErrorHandlerService, promptManager: AIPromptManagerService, intentClassifier: EnhancedIntentClassifierService, performanceOpt: PerformanceOptimizationService, agentTools: AiAgentToolsService, smartFeatures: SmartFeaturesService, nlQuery: NaturalLanguageQueryService, shiftMgmt: ShiftManagementService, expenseMgmt: ExpenseManagementService, analytics: AnalyticsService, wellness: WellnessService, gamification: GamificationService, itSupport: ITSupportService, learning: LearningService, meeting: MeetingService, onboarding: OnboardingService, feedback: FeedbackService, documentFinder: DocumentFinderService, careerAdvisor: CareerAdvisorService, multiCultural: MultiCulturalService, dailyBriefing: DailyBriefingService, performanceCoach: PerformanceCoachService, notifications: NotificationsService, teamCollab: TeamCollaborationService, compliance: ComplianceAssistantService, predictive: PredictiveInsightsService, hrAssistant: HRAssistantService, smartScheduler: SmartSchedulerService, voiceAccess: VoiceAccessibilityService, social: SocialEngagementService, integrationHub: IntegrationHubService, advancedAI: AdvancedAIService, reportsBuilder: ReportsBuilderService, emergency: EmergencyService, facilities: FacilitiesService, travelExpenses: TravelExpensesService, mobileFeatures: MobileFeaturesService, dataExport: DataExportService, automationRules: AutomationRulesService, statsDashboard: StatisticsDashboardService, systemContext: SystemContextBuilderService, actionExecutor: ActionExecutorService);
    chat(userId: string, message: string): Promise<ChatResponse>;
    private classifyIntent;
    private hasPermission;
    private handleIntent;
    private handleExecutiveCommand;
    private handleEnhancement;
    private handleEmployeeAction;
    private handleLeaveAction;
    private handlePayrollAction;
    private handleQuery;
    private handleGeneralChat;
    private getUserContext;
    private buildPrompt;
    private normalizeArabic;
    private parseEmployeeFromMessage;
    private generateSecurePassword;
    private generateRequestId;
    private getSuggestions;
    clearHistory(userId: string, companyId: string): Promise<void>;
    getHistory(userId: string, companyId: string): Promise<ChatMessage[]>;
}
export {};
