/**
 * Report Definitions - 70 Comprehensive Reports
 * Organized by category with access levels
 */

import {
    AssignmentTurnedIn,
    AccessTime,
    EventBusy,
    TrendingUp,
    CalendarMonth,
    Group,
    AttachMoney,
    Assessment,
    AccountBalance,
    Business,
    PersonAdd,
    Badge,
    School,
    ContactPhone,
    Star,
    Task,
    Folder,
    Timeline,
    Dashboard,
    Security,
    BarChart,
    PieChart,
    Speed,
    Warning,
    MonetizationOn,
    Receipt,
    CreditCard,
    Savings,
    AccountBalanceWallet,
    Calculate,
    CompareArrows,
    WorkHistory,
    Cake,
    EmojiEvents,
    Psychology,
    Inventory,
    SupervisedUserCircle,
    Flag,
    LocalShipping,
    Timer,
    CheckCircle,
    Cancel,
    Schedule,
    HourglassEmpty,
    BeachAccess,
    LocalHospital,
    FlightTakeoff,
    Sick,
    FamilyRestroom,
    Paid,
    RequestQuote,
    Percent,
    TrendingDown,
    SwapVert,
    SupportAgent,
    Engineering,
    Diversity3,
    Gavel,
    Description,
    Insights,
    AutoGraph,
    QueryStats,
    DataUsage
} from '@mui/icons-material';
import { ElementType } from 'react';

export type ReportCategory =
    | 'attendance'
    | 'leaves'
    | 'payroll'
    | 'employees'
    | 'performance'
    | 'tasks'
    | 'admin';

export type AccessLevel = 'ALL' | 'MANAGER' | 'ADMIN';

export interface ReportDefinition {
    id: string;
    name: string;
    nameEn: string;
    description: string;
    category: ReportCategory;
    accessLevel: AccessLevel;
    icon: ElementType;
    apiEndpoint: string;
    exportFormats: ('pdf' | 'excel' | 'csv')[];
    color: string;
}

export const REPORT_CATEGORIES: Record<ReportCategory, { name: string; icon: ElementType; color: string }> = {
    attendance: { name: 'الحضور والانصراف', icon: AccessTime, color: '#4caf50' },
    leaves: { name: 'الإجازات', icon: BeachAccess, color: '#2196f3' },
    payroll: { name: 'الرواتب والمالية', icon: AttachMoney, color: '#ff9800' },
    employees: { name: 'الموظفين', icon: Group, color: '#9c27b0' },
    performance: { name: 'الأداء والتقييم', icon: TrendingUp, color: '#e91e63' },
    tasks: { name: 'المهام والمشاريع', icon: Task, color: '#00bcd4' },
    admin: { name: 'تقارير إدارية', icon: Dashboard, color: '#607d8b' },
};

export const REPORTS: ReportDefinition[] = [
    // ============================================
    // 1. تقارير الحضور والانصراف (12 تقرير)
    // ============================================
    {
        id: 'daily-attendance',
        name: 'تقرير الحضور اليومي',
        nameEn: 'Daily Attendance Report',
        description: 'سجل حضور جميع الموظفين لليوم الحالي مع أوقات الدخول والخروج',
        category: 'attendance',
        accessLevel: 'ALL',
        icon: AssignmentTurnedIn,
        apiEndpoint: '/reports/attendance/daily',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'monthly-attendance',
        name: 'تقرير الحضور الشهري',
        nameEn: 'Monthly Attendance Report',
        description: 'ملخص شامل للحضور خلال شهر كامل لجميع الموظفين',
        category: 'attendance',
        accessLevel: 'ALL',
        icon: CalendarMonth,
        apiEndpoint: '/reports/attendance/monthly',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'late-arrivals',
        name: 'تقرير التأخيرات',
        nameEn: 'Late Arrivals Report',
        description: 'قائمة الموظفين المتأخرين مع مدة التأخير وتاريخه',
        category: 'attendance',
        accessLevel: 'MANAGER',
        icon: Schedule,
        apiEndpoint: '/reports/attendance/late',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'absences',
        name: 'تقرير الغياب',
        nameEn: 'Absence Report',
        description: 'تفاصيل أيام الغياب لكل موظف مع الأسباب إن وجدت',
        category: 'attendance',
        accessLevel: 'ALL',
        icon: EventBusy,
        apiEndpoint: '/reports/attendance/absences',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'overtime',
        name: 'تقرير ساعات العمل الإضافي',
        nameEn: 'Overtime Report',
        description: 'إجمالي الوقت الإضافي لكل موظف مع التفاصيل',
        category: 'attendance',
        accessLevel: 'MANAGER',
        icon: Timer,
        apiEndpoint: '/reports/attendance/overtime',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'early-leaves',
        name: 'تقرير الخروج المبكر',
        nameEn: 'Early Leave Report',
        description: 'حالات مغادرة الموظفين قبل الوقت المحدد',
        category: 'attendance',
        accessLevel: 'MANAGER',
        icon: TrendingDown,
        apiEndpoint: '/reports/attendance/early-leaves',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },
    {
        id: 'punctuality',
        name: 'تقرير الالتزام بالدوام',
        nameEn: 'Punctuality Report',
        description: 'نسبة الالتزام بمواعيد الحضور لكل موظف',
        category: 'attendance',
        accessLevel: 'ADMIN',
        icon: Speed,
        apiEndpoint: '/reports/attendance/punctuality',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'shifts',
        name: 'تقرير المناوبات',
        nameEn: 'Shifts Report',
        description: 'جدول الورديات والمناوبات الفعلية',
        category: 'attendance',
        accessLevel: 'MANAGER',
        icon: SwapVert,
        apiEndpoint: '/reports/attendance/shifts',
        exportFormats: ['pdf', 'excel'],
        color: '#795548',
    },
    {
        id: 'attendance-by-branch',
        name: 'تقرير الحضور حسب الفرع',
        nameEn: 'Attendance by Branch',
        description: 'مقارنة نسب الحضور بين جميع الفروع',
        category: 'attendance',
        accessLevel: 'ADMIN',
        icon: Business,
        apiEndpoint: '/reports/attendance/by-branch',
        exportFormats: ['pdf', 'excel'],
        color: '#3f51b5',
    },
    {
        id: 'attendance-by-department',
        name: 'تقرير الحضور حسب القسم',
        nameEn: 'Attendance by Department',
        description: 'مقارنة نسب الحضور بين الأقسام المختلفة',
        category: 'attendance',
        accessLevel: 'ADMIN',
        icon: Folder,
        apiEndpoint: '/reports/attendance/by-department',
        exportFormats: ['pdf', 'excel'],
        color: '#673ab7',
    },
    {
        id: 'attendance-rates',
        name: 'تقرير نسب الحضور',
        nameEn: 'Attendance Rates',
        description: 'النسب المئوية للحضور والغياب والتأخير',
        category: 'attendance',
        accessLevel: 'ALL',
        icon: PieChart,
        apiEndpoint: '/reports/attendance/rates',
        exportFormats: ['pdf', 'excel'],
        color: '#009688',
    },
    {
        id: 'fingerprint-details',
        name: 'تقرير تفاصيل البصمة',
        nameEn: 'Fingerprint Details',
        description: 'أوقات البصمة الفعلية لكل موظف بالتفصيل',
        category: 'attendance',
        accessLevel: 'ALL',
        icon: AccessTime,
        apiEndpoint: '/reports/attendance/fingerprint',
        exportFormats: ['pdf', 'excel'],
        color: '#607d8b',
    },

    // ============================================
    // 2. تقارير الإجازات (10 تقارير)
    // ============================================
    {
        id: 'leave-balance',
        name: 'تقرير رصيد الإجازات',
        nameEn: 'Leave Balance Report',
        description: 'رصيد كل موظف من الإجازات السنوية والمرضية',
        category: 'leaves',
        accessLevel: 'ALL',
        icon: AccountBalanceWallet,
        apiEndpoint: '/reports/leaves/balance',
        exportFormats: ['pdf', 'excel'],
        color: '#2196f3',
    },
    {
        id: 'approved-leaves',
        name: 'تقرير الإجازات المعتمدة',
        nameEn: 'Approved Leaves Report',
        description: 'قائمة جميع الإجازات الموافق عليها',
        category: 'leaves',
        accessLevel: 'MANAGER',
        icon: CheckCircle,
        apiEndpoint: '/reports/leaves/approved',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'rejected-leaves',
        name: 'تقرير الإجازات المرفوضة',
        nameEn: 'Rejected Leaves Report',
        description: 'قائمة الإجازات المرفوضة مع أسباب الرفض',
        category: 'leaves',
        accessLevel: 'MANAGER',
        icon: Cancel,
        apiEndpoint: '/reports/leaves/rejected',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'pending-leaves',
        name: 'تقرير الإجازات المعلقة',
        nameEn: 'Pending Leaves Report',
        description: 'الإجازات بانتظار الموافقة من المدير',
        category: 'leaves',
        accessLevel: 'MANAGER',
        icon: HourglassEmpty,
        apiEndpoint: '/reports/leaves/pending',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'leaves-by-type',
        name: 'تقرير الإجازات حسب النوع',
        nameEn: 'Leaves by Type Report',
        description: 'تصنيف الإجازات حسب نوعها (سنوية، مرضية، إلخ)',
        category: 'leaves',
        accessLevel: 'ADMIN',
        icon: Inventory,
        apiEndpoint: '/reports/leaves/by-type',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'leave-consumption',
        name: 'تقرير استهلاك الإجازات',
        nameEn: 'Leave Consumption Report',
        description: 'نسبة استهلاك رصيد الإجازات لكل موظف',
        category: 'leaves',
        accessLevel: 'ADMIN',
        icon: DataUsage,
        apiEndpoint: '/reports/leaves/consumption',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'leave-calendar',
        name: 'تقرير جدول الإجازات',
        nameEn: 'Leave Calendar Report',
        description: 'التقويم السنوي للإجازات المجدولة',
        category: 'leaves',
        accessLevel: 'ALL',
        icon: CalendarMonth,
        apiEndpoint: '/reports/leaves/calendar',
        exportFormats: ['pdf', 'excel'],
        color: '#3f51b5',
    },
    {
        id: 'overlapping-leaves',
        name: 'تقرير الإجازات المتزامنة',
        nameEn: 'Overlapping Leaves Report',
        description: 'تحذير من تعارض إجازات الموظفين في نفس الوقت',
        category: 'leaves',
        accessLevel: 'MANAGER',
        icon: Warning,
        apiEndpoint: '/reports/leaves/overlapping',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },
    {
        id: 'sick-leaves',
        name: 'تقرير الإجازات المرضية',
        nameEn: 'Sick Leaves Report',
        description: 'تفاصيل الإجازات المرضية مع المرفقات الطبية',
        category: 'leaves',
        accessLevel: 'ADMIN',
        icon: LocalHospital,
        apiEndpoint: '/reports/leaves/sick',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'end-of-service-leave',
        name: 'تقرير رصيد نهاية الخدمة',
        nameEn: 'End of Service Leave Balance',
        description: 'حساب رصيد الإجازات المتبقي عند نهاية الخدمة',
        category: 'leaves',
        accessLevel: 'ADMIN',
        icon: FlightTakeoff,
        apiEndpoint: '/reports/leaves/end-of-service',
        exportFormats: ['pdf', 'excel'],
        color: '#795548',
    },

    // ============================================
    // 3. تقارير الرواتب والمالية (15 تقرير)
    // ============================================
    {
        id: 'monthly-salary',
        name: 'كشف الراتب الشهري',
        nameEn: 'Monthly Salary Slip',
        description: 'تفاصيل راتب الموظف الشهري مع جميع البنود',
        category: 'payroll',
        accessLevel: 'ALL',
        icon: Receipt,
        apiEndpoint: '/reports/payroll/salary-slip',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'payroll-summary',
        name: 'تقرير مسير الرواتب',
        nameEn: 'Payroll Summary Report',
        description: 'ملخص رواتب جميع الموظفين للشهر',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: Paid,
        apiEndpoint: '/reports/payroll/summary',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'deductions',
        name: 'تقرير الخصومات',
        nameEn: 'Deductions Report',
        description: 'تفاصيل جميع الخصومات (تأخير، غياب، سلف)',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: TrendingDown,
        apiEndpoint: '/reports/payroll/deductions',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'allowances',
        name: 'تقرير البدلات',
        nameEn: 'Allowances Report',
        description: 'تفاصيل البدلات المصروفة (سكن، نقل، إلخ)',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: MonetizationOn,
        apiEndpoint: '/reports/payroll/allowances',
        exportFormats: ['pdf', 'excel'],
        color: '#2196f3',
    },
    {
        id: 'commissions',
        name: 'تقرير العمولات',
        nameEn: 'Commissions Report',
        description: 'حساب العمولات لموظفي المبيعات',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: Percent,
        apiEndpoint: '/reports/payroll/commissions',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'bonuses',
        name: 'تقرير المكافآت',
        nameEn: 'Bonuses Report',
        description: 'قائمة المكافآت المصروفة للموظفين',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: EmojiEvents,
        apiEndpoint: '/reports/payroll/bonuses',
        exportFormats: ['pdf', 'excel'],
        color: '#ffc107',
    },
    {
        id: 'loans',
        name: 'تقرير السلف',
        nameEn: 'Loans Report',
        description: 'السلف المصروفة والمسددة والمتبقية',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: CreditCard,
        apiEndpoint: '/reports/payroll/loans',
        exportFormats: ['pdf', 'excel'],
        color: '#795548',
    },
    {
        id: 'gosi',
        name: 'تقرير التأمينات الاجتماعية',
        nameEn: 'GOSI Report',
        description: 'مساهمات التأمينات الاجتماعية للموظفين',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: AccountBalance,
        apiEndpoint: '/reports/payroll/gosi',
        exportFormats: ['pdf', 'excel'],
        color: '#607d8b',
    },
    {
        id: 'wps',
        name: 'تقرير WPS',
        nameEn: 'WPS Report',
        description: 'ملف حماية الأجور للبنك المركزي',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: Security,
        apiEndpoint: '/reports/payroll/wps',
        exportFormats: ['excel', 'csv'],
        color: '#3f51b5',
    },
    {
        id: 'salary-comparison',
        name: 'تقرير مقارنة الرواتب',
        nameEn: 'Salary Comparison Report',
        description: 'مقارنة الرواتب بين الأشهر والسنوات',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: CompareArrows,
        apiEndpoint: '/reports/payroll/comparison',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'employee-costs',
        name: 'تقرير تكاليف الموظفين',
        nameEn: 'Employee Costs Report',
        description: 'إجمالي التكاليف لكل قسم وفرع',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: Calculate,
        apiEndpoint: '/reports/payroll/costs',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'salary-increments',
        name: 'تقرير الزيادات',
        nameEn: 'Salary Increments Report',
        description: 'تاريخ زيادات الرواتب لجميع الموظفين',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: TrendingUp,
        apiEndpoint: '/reports/payroll/increments',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'adjustments',
        name: 'تقرير التسويات',
        nameEn: 'Adjustments Report',
        description: 'التسويات المالية والتعديلات على الرواتب',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: RequestQuote,
        apiEndpoint: '/reports/payroll/adjustments',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },
    {
        id: 'variances',
        name: 'تقرير الفروقات',
        nameEn: 'Variances Report',
        description: 'فروقات الرواتب بين الشهور',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: SwapVert,
        apiEndpoint: '/reports/payroll/variances',
        exportFormats: ['pdf', 'excel'],
        color: '#673ab7',
    },
    {
        id: 'end-of-service-financial',
        name: 'تقرير نهاية الخدمة المالي',
        nameEn: 'End of Service Financial Report',
        description: 'حساب مستحقات نهاية الخدمة للموظف',
        category: 'payroll',
        accessLevel: 'ADMIN',
        icon: Savings,
        apiEndpoint: '/reports/payroll/end-of-service',
        exportFormats: ['pdf', 'excel'],
        color: '#795548',
    },

    // ============================================
    // 4. تقارير الموظفين (10 تقارير)
    // ============================================
    {
        id: 'employee-data',
        name: 'تقرير بيانات الموظفين',
        nameEn: 'Employee Data Report',
        description: 'معلومات شاملة عن جميع الموظفين',
        category: 'employees',
        accessLevel: 'ADMIN',
        icon: Group,
        apiEndpoint: '/reports/employees/data',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'new-hires',
        name: 'تقرير الموظفين الجدد',
        nameEn: 'New Hires Report',
        description: 'الموظفون المعينون حديثاً خلال الفترة',
        category: 'employees',
        accessLevel: 'ADMIN',
        icon: PersonAdd,
        apiEndpoint: '/reports/employees/new-hires',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'contract-expiry',
        name: 'تقرير انتهاء العقود',
        nameEn: 'Contract Expiry Report',
        description: 'العقود التي قاربت على الانتهاء',
        category: 'employees',
        accessLevel: 'ADMIN',
        icon: Description,
        apiEndpoint: '/reports/employees/contract-expiry',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'employees-by-nationality',
        name: 'تقرير الموظفين حسب الجنسية',
        nameEn: 'Employees by Nationality',
        description: 'توزيع الموظفين حسب الجنسيات',
        category: 'employees',
        accessLevel: 'ADMIN',
        icon: Flag,
        apiEndpoint: '/reports/employees/by-nationality',
        exportFormats: ['pdf', 'excel'],
        color: '#3f51b5',
    },
    {
        id: 'saudization',
        name: 'تقرير السعودة',
        nameEn: 'Saudization Report',
        description: 'نسب التوطين ونطاقات',
        category: 'employees',
        accessLevel: 'ADMIN',
        icon: Badge,
        apiEndpoint: '/reports/employees/saudization',
        exportFormats: ['pdf', 'excel'],
        color: '#2e7d32',
    },
    {
        id: 'org-structure',
        name: 'تقرير الهيكل التنظيمي',
        nameEn: 'Organization Structure Report',
        description: 'شجرة المراتب والمسميات الوظيفية',
        category: 'employees',
        accessLevel: 'MANAGER',
        icon: SupervisedUserCircle,
        apiEndpoint: '/reports/employees/org-structure',
        exportFormats: ['pdf', 'excel'],
        color: '#673ab7',
    },
    {
        id: 'birthdays',
        name: 'تقرير أعياد الميلاد',
        nameEn: 'Birthdays Report',
        description: 'قائمة أعياد ميلاد الموظفين للشهر',
        category: 'employees',
        accessLevel: 'ALL',
        icon: Cake,
        apiEndpoint: '/reports/employees/birthdays',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'work-anniversary',
        name: 'تقرير الذكرى السنوية',
        nameEn: 'Work Anniversary Report',
        description: 'ذكرى التعيين للموظفين',
        category: 'employees',
        accessLevel: 'ALL',
        icon: EmojiEvents,
        apiEndpoint: '/reports/employees/anniversary',
        exportFormats: ['pdf', 'excel'],
        color: '#ffc107',
    },
    {
        id: 'qualifications',
        name: 'تقرير المؤهلات',
        nameEn: 'Qualifications Report',
        description: 'المؤهلات العلمية والشهادات',
        category: 'employees',
        accessLevel: 'ADMIN',
        icon: School,
        apiEndpoint: '/reports/employees/qualifications',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'emergency-contacts',
        name: 'تقرير جهات الاتصال',
        nameEn: 'Emergency Contacts Report',
        description: 'معلومات الطوارئ لجميع الموظفين',
        category: 'employees',
        accessLevel: 'MANAGER',
        icon: ContactPhone,
        apiEndpoint: '/reports/employees/emergency-contacts',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },

    // ============================================
    // 5. تقارير الأداء والتقييم (8 تقارير)
    // ============================================
    {
        id: 'performance-evaluation',
        name: 'تقرير تقييم الأداء',
        nameEn: 'Performance Evaluation Report',
        description: 'نتائج التقييمات الدورية للموظفين',
        category: 'performance',
        accessLevel: 'MANAGER',
        icon: Assessment,
        apiEndpoint: '/reports/performance/evaluation',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'employee-goals',
        name: 'تقرير أهداف الموظفين',
        nameEn: 'Employee Goals Report',
        description: 'تتبع تحقيق الأهداف (OKRs)',
        category: 'performance',
        accessLevel: 'MANAGER',
        icon: Flag,
        apiEndpoint: '/reports/performance/goals',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'kpis',
        name: 'تقرير KPIs',
        nameEn: 'KPIs Report',
        description: 'مؤشرات الأداء الرئيسية للأقسام',
        category: 'performance',
        accessLevel: 'ADMIN',
        icon: Speed,
        apiEndpoint: '/reports/performance/kpis',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'productivity',
        name: 'تقرير الإنتاجية',
        nameEn: 'Productivity Report',
        description: 'معدل إنتاجية كل موظف وقسم',
        category: 'performance',
        accessLevel: 'ADMIN',
        icon: TrendingUp,
        apiEndpoint: '/reports/performance/productivity',
        exportFormats: ['pdf', 'excel'],
        color: '#2196f3',
    },
    {
        id: 'training',
        name: 'تقرير التدريب',
        nameEn: 'Training Report',
        description: 'الدورات التدريبية المكتملة والمخططة',
        category: 'performance',
        accessLevel: 'MANAGER',
        icon: School,
        apiEndpoint: '/reports/performance/training',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'promotions',
        name: 'تقرير الترقيات',
        nameEn: 'Promotions Report',
        description: 'سجل ترقيات الموظفين',
        category: 'performance',
        accessLevel: 'ADMIN',
        icon: WorkHistory,
        apiEndpoint: '/reports/performance/promotions',
        exportFormats: ['pdf', 'excel'],
        color: '#673ab7',
    },
    {
        id: 'recognition',
        name: 'تقرير التكريم والجوائز',
        nameEn: 'Recognition Report',
        description: 'المكافآت والتكريمات الممنوحة',
        category: 'performance',
        accessLevel: 'ALL',
        icon: Star,
        apiEndpoint: '/reports/performance/recognition',
        exportFormats: ['pdf', 'excel'],
        color: '#ffc107',
    },
    {
        id: 'warnings',
        name: 'تقرير الإنذارات',
        nameEn: 'Warnings Report',
        description: 'الإنذارات والجزاءات التأديبية',
        category: 'performance',
        accessLevel: 'ADMIN',
        icon: Gavel,
        apiEndpoint: '/reports/performance/warnings',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },

    // ============================================
    // 6. تقارير المهام والمشاريع (8 تقارير)
    // ============================================
    {
        id: 'completed-tasks',
        name: 'تقرير المهام المكتملة',
        nameEn: 'Completed Tasks Report',
        description: 'المهام المنجزة في الفترة المحددة',
        category: 'tasks',
        accessLevel: 'ALL',
        icon: CheckCircle,
        apiEndpoint: '/reports/tasks/completed',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'overdue-tasks',
        name: 'تقرير المهام المتأخرة',
        nameEn: 'Overdue Tasks Report',
        description: 'المهام التي تجاوزت الموعد المحدد',
        category: 'tasks',
        accessLevel: 'MANAGER',
        icon: Warning,
        apiEndpoint: '/reports/tasks/overdue',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'project-status',
        name: 'تقرير حالة المشاريع',
        nameEn: 'Project Status Report',
        description: 'تقدم المشاريع الجارية ونسب الإنجاز',
        category: 'tasks',
        accessLevel: 'MANAGER',
        icon: Timeline,
        apiEndpoint: '/reports/tasks/projects',
        exportFormats: ['pdf', 'excel'],
        color: '#2196f3',
    },
    {
        id: 'task-distribution',
        name: 'تقرير توزيع المهام',
        nameEn: 'Task Distribution Report',
        description: 'عبء العمل وتوزيع المهام لكل موظف',
        category: 'tasks',
        accessLevel: 'MANAGER',
        icon: BarChart,
        apiEndpoint: '/reports/tasks/distribution',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'project-hours',
        name: 'تقرير ساعات المشاريع',
        nameEn: 'Project Hours Report',
        description: 'الوقت المستثمر في كل مشروع',
        category: 'tasks',
        accessLevel: 'ADMIN',
        icon: Timer,
        apiEndpoint: '/reports/tasks/hours',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'achievements',
        name: 'تقرير الإنجازات',
        nameEn: 'Achievements Report',
        description: 'الإنجازات البارزة للفريق',
        category: 'tasks',
        accessLevel: 'ALL',
        icon: EmojiEvents,
        apiEndpoint: '/reports/tasks/achievements',
        exportFormats: ['pdf', 'excel'],
        color: '#ffc107',
    },
    {
        id: 'team-collaboration',
        name: 'تقرير التعاون',
        nameEn: 'Team Collaboration Report',
        description: 'التعاون بين الفرق والأقسام',
        category: 'tasks',
        accessLevel: 'ADMIN',
        icon: Diversity3,
        apiEndpoint: '/reports/tasks/collaboration',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'priorities',
        name: 'تقرير أولويات العمل',
        nameEn: 'Work Priorities Report',
        description: 'ترتيب المهام حسب الأولوية',
        category: 'tasks',
        accessLevel: 'MANAGER',
        icon: Flag,
        apiEndpoint: '/reports/tasks/priorities',
        exportFormats: ['pdf', 'excel'],
        color: '#673ab7',
    },

    // ============================================
    // 7. تقارير إدارية وتحليلية (7 تقارير)
    // ============================================
    {
        id: 'executive-dashboard',
        name: 'لوحة البيانات التنفيذية',
        nameEn: 'Executive Dashboard',
        description: 'ملخص تنفيذي شامل للمدير العام',
        category: 'admin',
        accessLevel: 'ADMIN',
        icon: Dashboard,
        apiEndpoint: '/reports/admin/executive',
        exportFormats: ['pdf', 'excel'],
        color: '#607d8b',
    },
    {
        id: 'yearly-comparison',
        name: 'تقرير المقارنة السنوية',
        nameEn: 'Yearly Comparison Report',
        description: 'مقارنة شاملة بين السنوات',
        category: 'admin',
        accessLevel: 'ADMIN',
        icon: CompareArrows,
        apiEndpoint: '/reports/admin/yearly-comparison',
        exportFormats: ['pdf', 'excel'],
        color: '#3f51b5',
    },
    {
        id: 'forecasts',
        name: 'تقرير التوقعات',
        nameEn: 'Forecasts Report',
        description: 'تنبؤات الموارد البشرية والتكاليف',
        category: 'admin',
        accessLevel: 'ADMIN',
        icon: AutoGraph,
        apiEndpoint: '/reports/admin/forecasts',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'audit-log',
        name: 'تقرير سجل النظام',
        nameEn: 'Audit Log Report',
        description: 'سجلات التدقيق وتتبع التغييرات',
        category: 'admin',
        accessLevel: 'ADMIN',
        icon: Security,
        apiEndpoint: '/reports/admin/audit-log',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'system-usage',
        name: 'تقرير استخدام النظام',
        nameEn: 'System Usage Report',
        description: 'إحصائيات استخدام التطبيق',
        category: 'admin',
        accessLevel: 'ADMIN',
        icon: QueryStats,
        apiEndpoint: '/reports/admin/usage',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'job-satisfaction',
        name: 'تقرير الرضا الوظيفي',
        nameEn: 'Job Satisfaction Report',
        description: 'نتائج استبيانات رضا الموظفين',
        category: 'admin',
        accessLevel: 'ADMIN',
        icon: Psychology,
        apiEndpoint: '/reports/admin/satisfaction',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'turnover-analysis',
        name: 'تقرير تحليل الدوران',
        nameEn: 'Turnover Analysis Report',
        description: 'تحليل معدل دوران الموظفين',
        category: 'admin',
        accessLevel: 'ADMIN',
        icon: Insights,
        apiEndpoint: '/reports/admin/turnover',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
];

// Helper functions
export const getReportsByCategory = (category: ReportCategory): ReportDefinition[] => {
    return REPORTS.filter(r => r.category === category);
};

export const getReportsByAccessLevel = (level: AccessLevel, userRole: string): ReportDefinition[] => {
    if (userRole === 'ADMIN') {
        return REPORTS;
    }
    if (userRole === 'MANAGER') {
        return REPORTS.filter(r => r.accessLevel === 'ALL' || r.accessLevel === 'MANAGER');
    }
    return REPORTS.filter(r => r.accessLevel === 'ALL');
};

export const getReportById = (id: string): ReportDefinition | undefined => {
    return REPORTS.find(r => r.id === id);
};

export const searchReports = (query: string): ReportDefinition[] => {
    const loweredQuery = query.toLowerCase();
    return REPORTS.filter(r =>
        r.name.toLowerCase().includes(loweredQuery) ||
        r.nameEn.toLowerCase().includes(loweredQuery) ||
        r.description.toLowerCase().includes(loweredQuery)
    );
};
