/**
 * Report Definitions - Synced with Backend API
 * Based on backend's extended-report.dto.ts REPORTS_CATALOG
 */

import {
    CalendarToday,
    AccessTime,
    PersonOff,
    ExitToApp,
    MoreTime,
    Home,
    Business,
    AccountTree,
    VerifiedUser,
    Warning,
    Payments,
    Receipt,
    MoneyOff,
    EventBusy,
    AttachMoney,
    Security,
    AccountBalance,
    CreditCard,
    TrendingUp,
    CompareArrows,
    PriceCheck,
    History,
    EventAvailable,
    ListAlt,
    DonutLarge,
    LocalHospital,
    PieChart,
    ReportProblem,
    EventRepeat,
    CalendarMonth,
    Groups,
    PersonAdd,
    WorkOff,
    Public,
    Badge,
    CardTravel,
    ArrowUpward,
    SwapHoriz,
    Analytics,
    Gavel,
    Error,
    Block,
    Search,
    NotificationImportant,
    Inventory,
    Person,
    AssignmentReturn,
    Build,
    Dashboard,
    Speed,
} from '@mui/icons-material';
import { ElementType } from 'react';

export type ReportCategory =
    | 'ATTENDANCE'
    | 'PAYROLL'
    | 'LEAVES'
    | 'HR'
    | 'DISCIPLINARY'
    | 'CUSTODY'
    | 'EXECUTIVE';

export type AccessLevel = 'ALL' | 'MANAGER' | 'ADMIN';

export interface ReportDefinition {
    id: string;
    name: string;
    nameEn: string;
    description: string;
    category: ReportCategory;
    accessLevel: AccessLevel;
    icon: ElementType;
    apiEndpoint: string;
    exportFormats: ('pdf' | 'excel' | 'csv')[];
    color: string;
}

export const REPORT_CATEGORIES: Record<ReportCategory, { name: string; icon: ElementType; color: string }> = {
    ATTENDANCE: { name: 'الحضور والانصراف', icon: AccessTime, color: '#4caf50' },
    LEAVES: { name: 'الإجازات', icon: EventAvailable, color: '#2196f3' },
    PAYROLL: { name: 'الرواتب والمالية', icon: AttachMoney, color: '#ff9800' },
    HR: { name: 'الموارد البشرية', icon: Groups, color: '#9c27b0' },
    DISCIPLINARY: { name: 'القضايا التأديبية', icon: Gavel, color: '#f44336' },
    CUSTODY: { name: 'العهد والأصول', icon: Inventory, color: '#00bcd4' },
    EXECUTIVE: { name: 'تقارير تنفيذية', icon: Dashboard, color: '#607d8b' },
};

// ===================== ALL REPORTS (Synced with Backend) =====================

export const REPORTS: ReportDefinition[] = [
    // ===== ATTENDANCE REPORTS (10) =====
    {
        id: 'daily-attendance',
        name: 'تقرير الحضور اليومي',
        nameEn: 'Daily Attendance Report',
        description: 'بيانات الحضور لليوم مع تفاصيل الدخول والخروج',
        category: 'ATTENDANCE',
        accessLevel: 'ALL',
        icon: CalendarToday,
        apiEndpoint: '/reports/attendance/daily',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'late-detailed',
        name: 'تقرير التأخيرات التفصيلي',
        nameEn: 'Late Arrivals Detailed Report',
        description: 'تفاصيل تأخيرات الموظفين مع المدة والتكرار',
        category: 'ATTENDANCE',
        accessLevel: 'MANAGER',
        icon: AccessTime,
        apiEndpoint: '/reports/attendance/late-detailed',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'absence',
        name: 'تقرير الغياب',
        nameEn: 'Absence Report',
        description: 'سجل الغياب وتحليل الأنماط',
        category: 'ATTENDANCE',
        accessLevel: 'MANAGER',
        icon: PersonOff,
        apiEndpoint: '/reports/attendance/absence',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'early-leave',
        name: 'تقرير الانصراف المبكر',
        nameEn: 'Early Leave Report',
        description: 'الموظفين الذين خرجوا قبل انتهاء الدوام',
        category: 'ATTENDANCE',
        accessLevel: 'MANAGER',
        icon: ExitToApp,
        apiEndpoint: '/reports/attendance/early-leave',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },
    {
        id: 'overtime',
        name: 'تقرير العمل الإضافي',
        nameEn: 'Overtime Report',
        description: 'ساعات العمل الإضافي لكل موظف',
        category: 'ATTENDANCE',
        accessLevel: 'MANAGER',
        icon: MoreTime,
        apiEndpoint: '/reports/attendance/overtime',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'wfh',
        name: 'تقرير العمل من المنزل',
        nameEn: 'Work From Home Report',
        description: 'أيام العمل عن بُعد لجميع الموظفين',
        category: 'ATTENDANCE',
        accessLevel: 'ALL',
        icon: Home,
        apiEndpoint: '/reports/attendance/work-from-home',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'branch-summary',
        name: 'ملخص الحضور حسب الفرع',
        nameEn: 'Attendance by Branch',
        description: 'إحصائيات الحضور موزعة على الفروع',
        category: 'ATTENDANCE',
        accessLevel: 'ADMIN',
        icon: Business,
        apiEndpoint: '/reports/attendance/by-branch',
        exportFormats: ['pdf', 'excel'],
        color: '#3f51b5',
    },
    {
        id: 'department-summary',
        name: 'ملخص الحضور حسب القسم',
        nameEn: 'Attendance by Department',
        description: 'إحصائيات الحضور موزعة على الأقسام',
        category: 'ATTENDANCE',
        accessLevel: 'ADMIN',
        icon: AccountTree,
        apiEndpoint: '/reports/attendance/by-department',
        exportFormats: ['pdf', 'excel'],
        color: '#673ab7',
    },
    {
        id: 'compliance',
        name: 'تقرير الالتزام بالدوام',
        nameEn: 'Compliance Report',
        description: 'نسب الالتزام بمواعيد الحضور لكل موظف',
        category: 'ATTENDANCE',
        accessLevel: 'ADMIN',
        icon: VerifiedUser,
        apiEndpoint: '/reports/attendance/compliance',
        exportFormats: ['pdf', 'excel'],
        color: '#009688',
    },
    {
        id: 'suspicious',
        name: 'المحاولات المشبوهة',
        nameEn: 'Suspicious Attempts',
        description: 'محاولات التلاعب والبصمات المشبوهة',
        category: 'ATTENDANCE',
        accessLevel: 'ADMIN',
        icon: Warning,
        apiEndpoint: '/reports/attendance/suspicious',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },

    // ===== PAYROLL REPORTS (12) =====
    {
        id: 'payroll-summary',
        name: 'ملخص الرواتب الشهري',
        nameEn: 'Monthly Payroll Summary',
        description: 'إجمالي الرواتب والخصومات لجميع الموظفين',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: Payments,
        apiEndpoint: '/reports/payroll/summary',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'payslip-details',
        name: 'تفاصيل قسائم الرواتب',
        nameEn: 'Payslip Details',
        description: 'تفاصيل كل قسيمة راتب',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: Receipt,
        apiEndpoint: '/reports/payroll/payslips',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'late-deductions',
        name: 'خصومات التأخير',
        nameEn: 'Late Deductions',
        description: 'خصومات الموظفين بسبب التأخير',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: MoneyOff,
        apiEndpoint: '/reports/payroll/late-deductions',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'absence-deductions',
        name: 'خصومات الغياب',
        nameEn: 'Absence Deductions',
        description: 'خصومات الغياب التفصيلية',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: EventBusy,
        apiEndpoint: '/reports/payroll/absence-deductions',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'overtime-allowances',
        name: 'بدلات العمل الإضافي',
        nameEn: 'Overtime Allowances',
        description: 'بدلات الأوفرتايم لكل موظف',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: AttachMoney,
        apiEndpoint: '/reports/payroll/overtime-allowances',
        exportFormats: ['pdf', 'excel'],
        color: '#2196f3',
    },
    {
        id: 'gosi',
        name: 'تقرير التأمينات GOSI',
        nameEn: 'GOSI Report',
        description: 'مساهمات التأمينات الاجتماعية',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: Security,
        apiEndpoint: '/reports/payroll/gosi',
        exportFormats: ['pdf', 'excel'],
        color: '#607d8b',
    },
    {
        id: 'wps',
        name: 'تقرير WPS',
        nameEn: 'WPS Report',
        description: 'ملف البنك للرواتب (حماية الأجور)',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: AccountBalance,
        apiEndpoint: '/reports/payroll/wps',
        exportFormats: ['excel', 'csv'],
        color: '#3f51b5',
    },
    {
        id: 'advances',
        name: 'السلف والقروض',
        nameEn: 'Advances & Loans',
        description: 'السلف المعتمدة والمتبقي منها',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: CreditCard,
        apiEndpoint: '/reports/payroll/advances',
        exportFormats: ['pdf', 'excel'],
        color: '#795548',
    },
    {
        id: 'raises',
        name: 'تقرير الزيادات',
        nameEn: 'Raises Report',
        description: 'زيادات الرواتب والمكافآت',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: TrendingUp,
        apiEndpoint: '/reports/payroll/raises',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'payroll-comparison',
        name: 'مقارنة الرواتب',
        nameEn: 'Payroll Comparison',
        description: 'مقارنة بين الفترات المختلفة',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: CompareArrows,
        apiEndpoint: '/reports/payroll/comparison',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'employee-cost',
        name: 'تكلفة الموظف',
        nameEn: 'Employee Cost',
        description: 'إجمالي تكلفة كل موظف على الشركة',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: PriceCheck,
        apiEndpoint: '/reports/payroll/employee-cost',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'retro-pay',
        name: 'التسويات بأثر رجعي',
        nameEn: 'Retro Payments',
        description: 'سجل التسويات المالية',
        category: 'PAYROLL',
        accessLevel: 'ADMIN',
        icon: History,
        apiEndpoint: '/reports/payroll/retro',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },

    // ===== LEAVE REPORTS (8) =====
    {
        id: 'leave-balance',
        name: 'رصيد الإجازات',
        nameEn: 'Leave Balance',
        description: 'أرصدة الإجازات لكل موظف',
        category: 'LEAVES',
        accessLevel: 'ALL',
        icon: EventAvailable,
        apiEndpoint: '/reports/leaves/balance',
        exportFormats: ['pdf', 'excel'],
        color: '#2196f3',
    },
    {
        id: 'leave-requests',
        name: 'طلبات الإجازات',
        nameEn: 'Leave Requests',
        description: 'حالة طلبات الإجازات (معتمدة/معلقة/مرفوضة)',
        category: 'LEAVES',
        accessLevel: 'MANAGER',
        icon: ListAlt,
        apiEndpoint: '/reports/leaves/requests',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'annual-consumption',
        name: 'استهلاك الإجازات',
        nameEn: 'Annual Consumption',
        description: 'تحليل استخدام الإجازات السنوية',
        category: 'LEAVES',
        accessLevel: 'ADMIN',
        icon: DonutLarge,
        apiEndpoint: '/reports/leaves/consumption',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'sick-leaves',
        name: 'الإجازات المرضية',
        nameEn: 'Sick Leaves',
        description: 'سجل الإجازات المرضية مع المرفقات',
        category: 'LEAVES',
        accessLevel: 'ADMIN',
        icon: LocalHospital,
        apiEndpoint: '/reports/leaves/sick',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'leaves-by-type',
        name: 'الإجازات حسب النوع',
        nameEn: 'Leaves by Type',
        description: 'توزيع الإجازات حسب نوعها',
        category: 'LEAVES',
        accessLevel: 'ADMIN',
        icon: PieChart,
        apiEndpoint: '/reports/leaves/by-type',
        exportFormats: ['pdf', 'excel'],
        color: '#3f51b5',
    },
    {
        id: 'unjustified-absence',
        name: 'الغياب غير المبرر',
        nameEn: 'Unjustified Absence',
        description: 'غياب بدون طلب إجازة',
        category: 'LEAVES',
        accessLevel: 'ADMIN',
        icon: ReportProblem,
        apiEndpoint: '/reports/leaves/unjustified',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'carried-forward',
        name: 'الإجازات المتراكمة',
        nameEn: 'Carried Forward',
        description: 'الإجازات المرحّلة من السنة السابقة',
        category: 'LEAVES',
        accessLevel: 'ADMIN',
        icon: EventRepeat,
        apiEndpoint: '/reports/leaves/carried-forward',
        exportFormats: ['pdf', 'excel'],
        color: '#795548',
    },
    {
        id: 'leave-forecast',
        name: 'توقعات الإجازات',
        nameEn: 'Leave Forecast',
        description: 'المواعيد المتوقعة للإجازات',
        category: 'LEAVES',
        accessLevel: 'MANAGER',
        icon: CalendarMonth,
        apiEndpoint: '/reports/leaves/forecast',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },

    // ===== HR REPORTS (10) =====
    {
        id: 'employee-list',
        name: 'سجل الموظفين',
        nameEn: 'Employee List',
        description: 'قائمة كاملة بجميع الموظفين',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: Groups,
        apiEndpoint: '/reports/hr/employees',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'new-hires',
        name: 'التوظيف الجديد',
        nameEn: 'New Hires',
        description: 'الموظفين الجدد خلال الفترة',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: PersonAdd,
        apiEndpoint: '/reports/hr/new-hires',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'contract-expiry',
        name: 'انتهاء العقود',
        nameEn: 'Contract Expiry',
        description: 'العقود القريبة للانتهاء',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: WorkOff,
        apiEndpoint: '/reports/hr/contract-expiry',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'employee-distribution',
        name: 'توزيع الموظفين',
        nameEn: 'Employee Distribution',
        description: 'توزيع الموظفين حسب الفرع/القسم',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: AccountTree,
        apiEndpoint: '/reports/hr/distribution',
        exportFormats: ['pdf', 'excel'],
        color: '#673ab7',
    },
    {
        id: 'nationality-analysis',
        name: 'تحليل الجنسيات (السعودة)',
        nameEn: 'Nationality Analysis',
        description: 'توزيع الموظفين حسب الجنسية',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: Public,
        apiEndpoint: '/reports/hr/nationalities',
        exportFormats: ['pdf', 'excel'],
        color: '#2e7d32',
    },
    {
        id: 'iqama-expiry',
        name: 'انتهاء الإقامات',
        nameEn: 'Iqama Expiry',
        description: 'الإقامات القريبة للانتهاء',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: Badge,
        apiEndpoint: '/reports/hr/iqama-expiry',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'passport-expiry',
        name: 'انتهاء الجوازات',
        nameEn: 'Passport Expiry',
        description: 'الجوازات القريبة للانتهاء',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: CardTravel,
        apiEndpoint: '/reports/hr/passport-expiry',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'promotions',
        name: 'تقرير الترقيات',
        nameEn: 'Promotions Report',
        description: 'سجل الترقيات الوظيفية',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: ArrowUpward,
        apiEndpoint: '/reports/hr/promotions',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'turnover',
        name: 'معدل دوران الموظفين',
        nameEn: 'Turnover Rate',
        description: 'تحليل الدوران والاستقالات',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: SwapHoriz,
        apiEndpoint: '/reports/hr/turnover',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },
    {
        id: 'demographics',
        name: 'التحليل الديموغرافي',
        nameEn: 'Demographics',
        description: 'تحليل الأعمار والخبرات',
        category: 'HR',
        accessLevel: 'ADMIN',
        icon: Analytics,
        apiEndpoint: '/reports/hr/demographics',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },

    // ===== DISCIPLINARY REPORTS (6) =====
    {
        id: 'disciplinary-cases',
        name: 'القضايا التأديبية',
        nameEn: 'Disciplinary Cases',
        description: 'جميع القضايا وحالاتها',
        category: 'DISCIPLINARY',
        accessLevel: 'ADMIN',
        icon: Gavel,
        apiEndpoint: '/reports/disciplinary/cases',
        exportFormats: ['pdf', 'excel'],
        color: '#f44336',
    },
    {
        id: 'violations-by-type',
        name: 'المخالفات حسب النوع',
        nameEn: 'Violations by Type',
        description: 'توزيع المخالفات التأديبية',
        category: 'DISCIPLINARY',
        accessLevel: 'ADMIN',
        icon: Error,
        apiEndpoint: '/reports/disciplinary/violations',
        exportFormats: ['pdf', 'excel'],
        color: '#e91e63',
    },
    {
        id: 'penalties',
        name: 'العقوبات المطبقة',
        nameEn: 'Applied Penalties',
        description: 'سجل العقوبات التأديبية',
        category: 'DISCIPLINARY',
        accessLevel: 'ADMIN',
        icon: Block,
        apiEndpoint: '/reports/disciplinary/penalties',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'investigations',
        name: 'تقرير التحقيقات',
        nameEn: 'Investigations Report',
        description: 'التحقيقات الجارية والمنتهية',
        category: 'DISCIPLINARY',
        accessLevel: 'ADMIN',
        icon: Search,
        apiEndpoint: '/reports/disciplinary/investigations',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'employee-record',
        name: 'السجل التأديبي',
        nameEn: 'Employee Disciplinary Record',
        description: 'السجل التأديبي لكل موظف',
        category: 'DISCIPLINARY',
        accessLevel: 'ADMIN',
        icon: PersonOff,
        apiEndpoint: '/reports/disciplinary/employee-record',
        exportFormats: ['pdf', 'excel'],
        color: '#795548',
    },
    {
        id: 'warnings',
        name: 'تقرير الإنذارات',
        nameEn: 'Warnings Report',
        description: 'الإنذارات الصادرة',
        category: 'DISCIPLINARY',
        accessLevel: 'ADMIN',
        icon: NotificationImportant,
        apiEndpoint: '/reports/disciplinary/warnings',
        exportFormats: ['pdf', 'excel'],
        color: '#ff5722',
    },

    // ===== CUSTODY REPORTS (5) =====
    {
        id: 'custody-inventory',
        name: 'جرد العهد',
        nameEn: 'Custody Inventory',
        description: 'جميع العهد وحالاتها',
        category: 'CUSTODY',
        accessLevel: 'ADMIN',
        icon: Inventory,
        apiEndpoint: '/reports/custody/inventory',
        exportFormats: ['pdf', 'excel'],
        color: '#00bcd4',
    },
    {
        id: 'custody-by-employee',
        name: 'عهد الموظفين',
        nameEn: 'Custody by Employee',
        description: 'العهد المسلمة لكل موظف',
        category: 'CUSTODY',
        accessLevel: 'MANAGER',
        icon: Person,
        apiEndpoint: '/reports/custody/by-employee',
        exportFormats: ['pdf', 'excel'],
        color: '#9c27b0',
    },
    {
        id: 'custody-returns',
        name: 'إرجاع العهد',
        nameEn: 'Custody Returns',
        description: 'سجل إرجاع العهد',
        category: 'CUSTODY',
        accessLevel: 'ADMIN',
        icon: AssignmentReturn,
        apiEndpoint: '/reports/custody/returns',
        exportFormats: ['pdf', 'excel'],
        color: '#4caf50',
    },
    {
        id: 'custody-maintenance',
        name: 'صيانة العهد',
        nameEn: 'Custody Maintenance',
        description: 'العهد التي تحتاج صيانة',
        category: 'CUSTODY',
        accessLevel: 'ADMIN',
        icon: Build,
        apiEndpoint: '/reports/custody/maintenance',
        exportFormats: ['pdf', 'excel'],
        color: '#ff9800',
    },
    {
        id: 'asset-value',
        name: 'قيمة الأصول',
        nameEn: 'Asset Value',
        description: 'إجمالي قيمة العهد والأصول',
        category: 'CUSTODY',
        accessLevel: 'ADMIN',
        icon: PriceCheck,
        apiEndpoint: '/reports/custody/value',
        exportFormats: ['pdf', 'excel'],
        color: '#2196f3',
    },

    // ===== EXECUTIVE REPORTS (4) =====
    {
        id: 'executive-dashboard',
        name: 'لوحة التحكم التنفيذية',
        nameEn: 'Executive Dashboard',
        description: 'ملخص شامل للمدير العام',
        category: 'EXECUTIVE',
        accessLevel: 'ADMIN',
        icon: Dashboard,
        apiEndpoint: '/reports/executive/dashboard',
        exportFormats: ['pdf'],
        color: '#607d8b',
    },
    {
        id: 'risk-alerts',
        name: 'تنبيهات المخاطر',
        nameEn: 'Risk Alerts',
        description: 'تنبيهات ذكية للمشاكل المحتملة',
        category: 'EXECUTIVE',
        accessLevel: 'ADMIN',
        icon: ReportProblem,
        apiEndpoint: '/reports/executive/alerts',
        exportFormats: ['pdf'],
        color: '#ff5722',
    },
    {
        id: 'kpis',
        name: 'مؤشرات الأداء KPIs',
        nameEn: 'Key Performance Indicators',
        description: 'مؤشرات الأداء الرئيسية للشركة',
        category: 'EXECUTIVE',
        accessLevel: 'ADMIN',
        icon: Speed,
        apiEndpoint: '/reports/executive/kpis',
        exportFormats: ['pdf'],
        color: '#4caf50',
    },
    {
        id: 'compliance-score',
        name: 'تقرير الامتثال',
        nameEn: 'Compliance Score',
        description: 'مستوى الامتثال للسياسات',
        category: 'EXECUTIVE',
        accessLevel: 'ADMIN',
        icon: VerifiedUser,
        apiEndpoint: '/reports/executive/compliance',
        exportFormats: ['pdf'],
        color: '#009688',
    },
];

// ===================== HELPER FUNCTIONS =====================

export const getReportsByCategory = (category: ReportCategory): ReportDefinition[] => {
    return REPORTS.filter(r => r.category === category);
};

export const getReportsByAccessLevel = (level: AccessLevel, userRole: string): ReportDefinition[] => {
    if (userRole === 'ADMIN' || userRole === 'HR' || userRole === 'FINANCE') {
        return REPORTS;
    }
    if (userRole === 'MANAGER') {
        return REPORTS.filter(r => r.accessLevel === 'ALL' || r.accessLevel === 'MANAGER');
    }
    return REPORTS.filter(r => r.accessLevel === 'ALL');
};

export const getReportById = (id: string): ReportDefinition | undefined => {
    return REPORTS.find(r => r.id === id);
};

export const searchReports = (query: string): ReportDefinition[] => {
    const loweredQuery = query.toLowerCase();
    return REPORTS.filter(r =>
        r.name.includes(query) ||
        r.nameEn.toLowerCase().includes(loweredQuery) ||
        r.description.includes(query)
    );
};

// Total count: 55 reports synced with backend APIs
