import { MudadService } from './mudad.service';
export declare class MudadController {
    private readonly mudadService;
    constructor(mudadService: MudadService);
    create(dto: any, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    findAll(req: any, year?: string): Promise<({
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    })[]>;
    getStats(req: any, year?: string): Promise<{
        total: number;
        pending: number;
        prepared: number;
        submitted: number;
        accepted: number;
        rejected: number;
        totalAmount: number;
    }>;
    findOne(id: string, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    updateStatus(id: string, dto: any, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    acceptSubmission(id: string, dto: any, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    rejectSubmission(id: string, dto: any, req: any): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    attachWpsFile(id: string, dto: {
        fileUrl: string;
        fileHashSha256?: string;
    }, req: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    delete(id: string, req: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
}
