import { PrismaService } from '../../common/prisma/prisma.service';
import { MudadStatus } from '@prisma/client';
import { StatusLogService } from '../../common/services/status-log.service';
import { StateMachineService } from '../../common/services/state-machine.service';
interface CreateMudadSubmissionDto {
    payrollRunId: string;
    submissionType?: string;
    notes?: string;
}
interface UpdateMudadStatusDto {
    status: MudadStatus;
    mudadRef?: string;
    rejectionNote?: string;
    notes?: string;
    reason?: string;
}
export declare class MudadService {
    private prisma;
    private statusLogService;
    private stateMachineService;
    constructor(prisma: PrismaService, statusLogService: StatusLogService, stateMachineService: StateMachineService);
    createSubmission(dto: CreateMudadSubmissionDto, companyId: string, userId: string): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    updateStatus(id: string, dto: UpdateMudadStatusDto, companyId: string, userId: string): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    findAll(companyId: string, year?: number): Promise<({
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    })[]>;
    findOne(id: string, companyId: string): Promise<{
        payrollRun: {
            period: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.PayrollStatus;
                companyId: string | null;
                endDate: Date;
                month: number;
                year: number;
                startDate: Date;
                cutOffDate: Date | null;
                inputsLockedAt: Date | null;
                lockedAt: Date | null;
                lockedBy: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    delete(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    attachWpsFile(id: string, fileUrl: string, companyId: string, fileHashSha256?: string, userId?: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.MudadStatus;
        companyId: string;
        period: string;
        notes: string | null;
        totalAmount: import("@prisma/client/runtime/library").Decimal;
        fileSize: number | null;
        rejectedAt: Date | null;
        submittedBy: string | null;
        submittedAt: Date | null;
        payrollRunId: string;
        employeeCount: number;
        submissionType: string;
        wpsFileUrl: string | null;
        mudadRef: string | null;
        preparedAt: Date | null;
        preparedBy: string | null;
        acceptedAt: Date | null;
        rejectionNote: string | null;
        fileHashSha256: string | null;
        generatorVersion: string | null;
    }>;
    getStats(companyId: string, year: number): Promise<{
        total: number;
        pending: number;
        prepared: number;
        submitted: number;
        accepted: number;
        rejected: number;
        totalAmount: number;
    }>;
}
export {};
