import { PrismaService } from '../../common/prisma/prisma.service';
import { CreateSalaryComponentDto } from './dto/create-salary-component.dto';
import { UpdateSalaryComponentDto } from './dto/update-salary-component.dto';
export declare class SalaryComponentsService {
    private prisma;
    constructor(prisma: PrismaService);
    create(dto: CreateSalaryComponentDto, companyId: string): Promise<{
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.SalaryComponentType;
        nature: import(".prisma/client").$Enums.SalaryComponentNature;
        description: string | null;
        gosiEligible: boolean;
        otEligible: boolean;
        eosEligible: boolean;
        isProrated: boolean;
        taxable: boolean;
        formula: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        roundingMode: string;
        decimals: number;
        priority: number;
    }>;
    findAll(companyId: string): Promise<{
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.SalaryComponentType;
        nature: import(".prisma/client").$Enums.SalaryComponentNature;
        description: string | null;
        gosiEligible: boolean;
        otEligible: boolean;
        eosEligible: boolean;
        isProrated: boolean;
        taxable: boolean;
        formula: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        roundingMode: string;
        decimals: number;
        priority: number;
    }[]>;
    findOne(id: string, companyId: string): Promise<{
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.SalaryComponentType;
        nature: import(".prisma/client").$Enums.SalaryComponentNature;
        description: string | null;
        gosiEligible: boolean;
        otEligible: boolean;
        eosEligible: boolean;
        isProrated: boolean;
        taxable: boolean;
        formula: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        roundingMode: string;
        decimals: number;
        priority: number;
    }>;
    update(id: string, companyId: string, dto: UpdateSalaryComponentDto): Promise<{
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.SalaryComponentType;
        nature: import(".prisma/client").$Enums.SalaryComponentNature;
        description: string | null;
        gosiEligible: boolean;
        otEligible: boolean;
        eosEligible: boolean;
        isProrated: boolean;
        taxable: boolean;
        formula: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        roundingMode: string;
        decimals: number;
        priority: number;
    }>;
    remove(id: string, companyId: string): Promise<{
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.SalaryComponentType;
        nature: import(".prisma/client").$Enums.SalaryComponentNature;
        description: string | null;
        gosiEligible: boolean;
        otEligible: boolean;
        eosEligible: boolean;
        isProrated: boolean;
        taxable: boolean;
        formula: string | null;
        version: number;
        effectiveDate: Date;
        endDate: Date | null;
        isActive: boolean;
        roundingMode: string;
        decimals: number;
        priority: number;
    }>;
}
