import { User } from '@prisma/client';
import { CustodyService } from './custody.service';
import { CreateCategoryCto, UpdateCategoryCto, CreateItemDto, UpdateItemDto, AssignCustodyDto, ApproveAssignmentDto, RejectAssignmentDto, SignAssignmentDto, RequestReturnDto, ReviewReturnDto, RequestTransferDto, ApproveTransferDto, RejectTransferDto, CreateMaintenanceDto, UpdateMaintenanceDto, CustodyQueryDto } from './dto/custody.dto';
export declare class CustodyController {
    private readonly custodyService;
    constructor(custodyService: CustodyService);
    getCategories(user: User): Promise<({
        _count: {
            items: number;
        };
    } & {
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        description: string | null;
        isActive: boolean;
        requiresApproval: boolean;
        icon: string | null;
        requiresSerialNumber: boolean;
        depreciationYears: number | null;
    })[]>;
    createCategory(user: User, dto: CreateCategoryCto): Promise<{
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        description: string | null;
        isActive: boolean;
        requiresApproval: boolean;
        icon: string | null;
        requiresSerialNumber: boolean;
        depreciationYears: number | null;
    }>;
    updateCategory(user: User, id: string, dto: UpdateCategoryCto): Promise<{
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        description: string | null;
        isActive: boolean;
        requiresApproval: boolean;
        icon: string | null;
        requiresSerialNumber: boolean;
        depreciationYears: number | null;
    }>;
    deleteCategory(user: User, id: string): Promise<{
        success: boolean;
    }>;
    getItems(user: User, query: CustodyQueryDto): Promise<{
        items: ({
            branch: {
                id: string;
                name: string;
                nameEn: string | null;
                address: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                isActive: boolean;
                workStartTime: string;
                workEndTime: string;
                lateGracePeriod: number;
                geofenceRadius: number;
                latitude: import("@prisma/client/runtime/library").Decimal;
                longitude: import("@prisma/client/runtime/library").Decimal;
                timezone: string;
                earlyCheckInPeriod: number;
                earlyCheckOutPeriod: number;
                workingDays: string;
            } | null;
            category: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string;
                description: string | null;
                isActive: boolean;
                requiresApproval: boolean;
                icon: string | null;
                requiresSerialNumber: boolean;
                depreciationYears: number | null;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        })[];
        total: number;
        page: number;
        limit: number;
    }>;
    getItem(user: User, id: string): Promise<{
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        } | null;
        category: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string;
            description: string | null;
            isActive: boolean;
            requiresApproval: boolean;
            icon: string | null;
            requiresSerialNumber: boolean;
            depreciationYears: number | null;
        };
        assignments: ({
            employee: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        })[];
        maintenances: {
            result: string | null;
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyMaintenanceStatus;
            companyId: string;
            type: import(".prisma/client").$Enums.MaintenanceType;
            description: string;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            custodyItemId: string;
            estimatedCost: import("@prisma/client/runtime/library").Decimal | null;
            reportedAt: Date;
            reportedById: string;
            startedAt: Date | null;
            completedAt: Date | null;
            actualCost: import("@prisma/client/runtime/library").Decimal | null;
            vendor: string | null;
            vendorContact: string | null;
            vendorEmail: string | null;
            invoiceNumber: string | null;
            conditionAfter: import(".prisma/client").$Enums.CustodyCondition | null;
        }[];
    } & {
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyItemStatus;
        companyId: string;
        branchId: string | null;
        code: string;
        description: string | null;
        notes: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        model: string | null;
        vendor: string | null;
        invoiceNumber: string | null;
        categoryId: string;
        serialNumber: string | null;
        brand: string | null;
        barcode: string | null;
        qrCode: string | null;
        purchaseDate: Date | null;
        purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
        warrantyExpiry: Date | null;
        condition: import(".prisma/client").$Enums.CustodyCondition;
        currentLocation: string | null;
        imageUrl: string | null;
        currentAssigneeId: string | null;
    }>;
    createItem(user: User, dto: CreateItemDto): Promise<{
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        } | null;
        category: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string;
            description: string | null;
            isActive: boolean;
            requiresApproval: boolean;
            icon: string | null;
            requiresSerialNumber: boolean;
            depreciationYears: number | null;
        };
    } & {
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyItemStatus;
        companyId: string;
        branchId: string | null;
        code: string;
        description: string | null;
        notes: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        model: string | null;
        vendor: string | null;
        invoiceNumber: string | null;
        categoryId: string;
        serialNumber: string | null;
        brand: string | null;
        barcode: string | null;
        qrCode: string | null;
        purchaseDate: Date | null;
        purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
        warrantyExpiry: Date | null;
        condition: import(".prisma/client").$Enums.CustodyCondition;
        currentLocation: string | null;
        imageUrl: string | null;
        currentAssigneeId: string | null;
    }>;
    updateItem(user: User, id: string, dto: UpdateItemDto): Promise<{
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        } | null;
        category: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string;
            description: string | null;
            isActive: boolean;
            requiresApproval: boolean;
            icon: string | null;
            requiresSerialNumber: boolean;
            depreciationYears: number | null;
        };
    } & {
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyItemStatus;
        companyId: string;
        branchId: string | null;
        code: string;
        description: string | null;
        notes: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        model: string | null;
        vendor: string | null;
        invoiceNumber: string | null;
        categoryId: string;
        serialNumber: string | null;
        brand: string | null;
        barcode: string | null;
        qrCode: string | null;
        purchaseDate: Date | null;
        purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
        warrantyExpiry: Date | null;
        condition: import(".prisma/client").$Enums.CustodyCondition;
        currentLocation: string | null;
        imageUrl: string | null;
        currentAssigneeId: string | null;
    }>;
    deleteItem(user: User, id: string): Promise<{
        success: boolean;
    }>;
    getMyCustody(user: User): Promise<({
        custodyItem: {
            category: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string;
                description: string | null;
                isActive: boolean;
                requiresApproval: boolean;
                icon: string | null;
                requiresSerialNumber: boolean;
                depreciationYears: number | null;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
        companyId: string;
        employeeId: string;
        notes: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        approvedAt: Date | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        approvedById: string | null;
        employeeSignature: string | null;
        custodyItemId: string;
        assignedAt: Date;
        expectedReturn: Date | null;
        actualReturn: Date | null;
        conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
        conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
        assignedById: string;
        signatureDate: Date | null;
    })[]>;
    getPendingAssignments(user: User): Promise<({
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
        custodyItem: {
            category: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string;
                description: string | null;
                isActive: boolean;
                requiresApproval: boolean;
                icon: string | null;
                requiresSerialNumber: boolean;
                depreciationYears: number | null;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
        assignedBy: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
        companyId: string;
        employeeId: string;
        notes: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        approvedAt: Date | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        approvedById: string | null;
        employeeSignature: string | null;
        custodyItemId: string;
        assignedAt: Date;
        expectedReturn: Date | null;
        actualReturn: Date | null;
        conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
        conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
        assignedById: string;
        signatureDate: Date | null;
    })[]>;
    assignCustody(user: User, dto: AssignCustodyDto): Promise<{
        employee: {
            id: string;
            firstName: string;
            lastName: string;
        };
        custodyItem: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
        companyId: string;
        employeeId: string;
        notes: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        approvedAt: Date | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        approvedById: string | null;
        employeeSignature: string | null;
        custodyItemId: string;
        assignedAt: Date;
        expectedReturn: Date | null;
        actualReturn: Date | null;
        conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
        conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
        assignedById: string;
        signatureDate: Date | null;
    }>;
    approveAssignment(user: User, dto: ApproveAssignmentDto): Promise<{
        success: boolean;
    }>;
    rejectAssignment(user: User, dto: RejectAssignmentDto): Promise<{
        success: boolean;
    }>;
    signAssignment(user: User, dto: SignAssignmentDto): Promise<{
        success: boolean;
    }>;
    getPendingReturns(user: User): Promise<({
        custodyItem: {
            category: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string;
                description: string | null;
                isActive: boolean;
                requiresApproval: boolean;
                icon: string | null;
                requiresSerialNumber: boolean;
                depreciationYears: number | null;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
        assignment: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        };
        returnedBy: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyReturnStatus;
        companyId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        custodyItemId: string;
        conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition;
        assignmentId: string;
        returnedById: string;
        returnDate: Date;
        returnReason: string | null;
        reviewedById: string | null;
        reviewedAt: Date | null;
        reviewNotes: string | null;
        damageDescription: string | null;
        estimatedCost: import("@prisma/client/runtime/library").Decimal | null;
        chargeEmployee: boolean;
        chargedToPayroll: boolean;
        payrollDeductionId: string | null;
    })[]>;
    requestReturn(user: User, dto: RequestReturnDto): Promise<{
        custodyItem: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyReturnStatus;
        companyId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        custodyItemId: string;
        conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition;
        assignmentId: string;
        returnedById: string;
        returnDate: Date;
        returnReason: string | null;
        reviewedById: string | null;
        reviewedAt: Date | null;
        reviewNotes: string | null;
        damageDescription: string | null;
        estimatedCost: import("@prisma/client/runtime/library").Decimal | null;
        chargeEmployee: boolean;
        chargedToPayroll: boolean;
        payrollDeductionId: string | null;
    }>;
    reviewReturn(user: User, dto: ReviewReturnDto): Promise<{
        success: boolean;
    }>;
    getMyPendingTransfers(user: User): Promise<({
        custodyItem: {
            category: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string;
                description: string | null;
                isActive: boolean;
                requiresApproval: boolean;
                icon: string | null;
                requiresSerialNumber: boolean;
                depreciationYears: number | null;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
        fromEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
        toEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyTransferStatus;
        companyId: string;
        notes: string | null;
        reason: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        approvedAt: Date | null;
        approvedById: string | null;
        custodyItemId: string;
        fromEmployeeId: string;
        toEmployeeId: string;
        transferDate: Date;
        initiatedById: string;
        fromSignature: string | null;
        toSignature: string | null;
    })[]>;
    getAllPendingTransfers(user: User): Promise<({
        custodyItem: {
            category: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string;
                description: string | null;
                isActive: boolean;
                requiresApproval: boolean;
                icon: string | null;
                requiresSerialNumber: boolean;
                depreciationYears: number | null;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
        fromEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
        toEmployee: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyTransferStatus;
        companyId: string;
        notes: string | null;
        reason: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        approvedAt: Date | null;
        approvedById: string | null;
        custodyItemId: string;
        fromEmployeeId: string;
        toEmployeeId: string;
        transferDate: Date;
        initiatedById: string;
        fromSignature: string | null;
        toSignature: string | null;
    })[]>;
    requestTransfer(user: User, dto: RequestTransferDto): Promise<{
        custodyItem: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
        toEmployee: {
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyTransferStatus;
        companyId: string;
        notes: string | null;
        reason: string | null;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        approvedAt: Date | null;
        approvedById: string | null;
        custodyItemId: string;
        fromEmployeeId: string;
        toEmployeeId: string;
        transferDate: Date;
        initiatedById: string;
        fromSignature: string | null;
        toSignature: string | null;
    }>;
    approveTransfer(user: User, dto: ApproveTransferDto): Promise<{
        success: boolean;
    }>;
    rejectTransfer(user: User, dto: RejectTransferDto): Promise<{
        success: boolean;
    }>;
    getMaintenances(user: User, status?: string): Promise<({
        custodyItem: {
            category: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string;
                description: string | null;
                isActive: boolean;
                requiresApproval: boolean;
                icon: string | null;
                requiresSerialNumber: boolean;
                depreciationYears: number | null;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
        reportedBy: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        result: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyMaintenanceStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.MaintenanceType;
        description: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        custodyItemId: string;
        estimatedCost: import("@prisma/client/runtime/library").Decimal | null;
        reportedAt: Date;
        reportedById: string;
        startedAt: Date | null;
        completedAt: Date | null;
        actualCost: import("@prisma/client/runtime/library").Decimal | null;
        vendor: string | null;
        vendorContact: string | null;
        vendorEmail: string | null;
        invoiceNumber: string | null;
        conditionAfter: import(".prisma/client").$Enums.CustodyCondition | null;
    })[]>;
    createMaintenance(user: User, dto: CreateMaintenanceDto): Promise<{
        custodyItem: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyItemStatus;
            companyId: string;
            branchId: string | null;
            code: string;
            description: string | null;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            model: string | null;
            vendor: string | null;
            invoiceNumber: string | null;
            categoryId: string;
            serialNumber: string | null;
            brand: string | null;
            barcode: string | null;
            qrCode: string | null;
            purchaseDate: Date | null;
            purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
            warrantyExpiry: Date | null;
            condition: import(".prisma/client").$Enums.CustodyCondition;
            currentLocation: string | null;
            imageUrl: string | null;
            currentAssigneeId: string | null;
        };
    } & {
        result: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyMaintenanceStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.MaintenanceType;
        description: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        custodyItemId: string;
        estimatedCost: import("@prisma/client/runtime/library").Decimal | null;
        reportedAt: Date;
        reportedById: string;
        startedAt: Date | null;
        completedAt: Date | null;
        actualCost: import("@prisma/client/runtime/library").Decimal | null;
        vendor: string | null;
        vendorContact: string | null;
        vendorEmail: string | null;
        invoiceNumber: string | null;
        conditionAfter: import(".prisma/client").$Enums.CustodyCondition | null;
    }>;
    updateMaintenance(user: User, id: string, dto: UpdateMaintenanceDto): Promise<{
        result: string | null;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.CustodyMaintenanceStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.MaintenanceType;
        description: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        custodyItemId: string;
        estimatedCost: import("@prisma/client/runtime/library").Decimal | null;
        reportedAt: Date;
        reportedById: string;
        startedAt: Date | null;
        completedAt: Date | null;
        actualCost: import("@prisma/client/runtime/library").Decimal | null;
        vendor: string | null;
        vendorContact: string | null;
        vendorEmail: string | null;
        invoiceNumber: string | null;
        conditionAfter: import(".prisma/client").$Enums.CustodyCondition | null;
    }>;
    getDashboard(user: User): Promise<{
        summary: {
            total: number;
            available: number;
            assigned: number;
            maintenance: number;
            lost: number;
        };
        categoryStats: ({
            _count: {
                items: number;
            };
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string;
            description: string | null;
            isActive: boolean;
            requiresApproval: boolean;
            icon: string | null;
            requiresSerialNumber: boolean;
            depreciationYears: number | null;
        })[];
        recentAssignments: ({
            employee: {
                firstName: string;
                lastName: string;
            };
            custodyItem: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.CustodyItemStatus;
                companyId: string;
                branchId: string | null;
                code: string;
                description: string | null;
                notes: string | null;
                attachments: import("@prisma/client/runtime/library").JsonValue | null;
                model: string | null;
                vendor: string | null;
                invoiceNumber: string | null;
                categoryId: string;
                serialNumber: string | null;
                brand: string | null;
                barcode: string | null;
                qrCode: string | null;
                purchaseDate: Date | null;
                purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
                warrantyExpiry: Date | null;
                condition: import(".prisma/client").$Enums.CustodyCondition;
                currentLocation: string | null;
                imageUrl: string | null;
                currentAssigneeId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        })[];
        pendingReturns: number;
    }>;
    getEmployeeReport(user: User, employeeId: string): Promise<{
        current: ({
            custodyItem: {
                category: {
                    id: string;
                    name: string;
                    nameEn: string | null;
                    createdAt: Date;
                    updatedAt: Date;
                    companyId: string;
                    description: string | null;
                    isActive: boolean;
                    requiresApproval: boolean;
                    icon: string | null;
                    requiresSerialNumber: boolean;
                    depreciationYears: number | null;
                };
            } & {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.CustodyItemStatus;
                companyId: string;
                branchId: string | null;
                code: string;
                description: string | null;
                notes: string | null;
                attachments: import("@prisma/client/runtime/library").JsonValue | null;
                model: string | null;
                vendor: string | null;
                invoiceNumber: string | null;
                categoryId: string;
                serialNumber: string | null;
                brand: string | null;
                barcode: string | null;
                qrCode: string | null;
                purchaseDate: Date | null;
                purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
                warrantyExpiry: Date | null;
                condition: import(".prisma/client").$Enums.CustodyCondition;
                currentLocation: string | null;
                imageUrl: string | null;
                currentAssigneeId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        })[];
        history: ({
            custodyItem: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.CustodyItemStatus;
                companyId: string;
                branchId: string | null;
                code: string;
                description: string | null;
                notes: string | null;
                attachments: import("@prisma/client/runtime/library").JsonValue | null;
                model: string | null;
                vendor: string | null;
                invoiceNumber: string | null;
                categoryId: string;
                serialNumber: string | null;
                brand: string | null;
                barcode: string | null;
                qrCode: string | null;
                purchaseDate: Date | null;
                purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
                warrantyExpiry: Date | null;
                condition: import(".prisma/client").$Enums.CustodyCondition;
                currentLocation: string | null;
                imageUrl: string | null;
                currentAssigneeId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        })[];
        totalValue: number | import("@prisma/client/runtime/library").Decimal;
    }>;
    getMyReport(user: User): Promise<{
        current: ({
            custodyItem: {
                category: {
                    id: string;
                    name: string;
                    nameEn: string | null;
                    createdAt: Date;
                    updatedAt: Date;
                    companyId: string;
                    description: string | null;
                    isActive: boolean;
                    requiresApproval: boolean;
                    icon: string | null;
                    requiresSerialNumber: boolean;
                    depreciationYears: number | null;
                };
            } & {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.CustodyItemStatus;
                companyId: string;
                branchId: string | null;
                code: string;
                description: string | null;
                notes: string | null;
                attachments: import("@prisma/client/runtime/library").JsonValue | null;
                model: string | null;
                vendor: string | null;
                invoiceNumber: string | null;
                categoryId: string;
                serialNumber: string | null;
                brand: string | null;
                barcode: string | null;
                qrCode: string | null;
                purchaseDate: Date | null;
                purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
                warrantyExpiry: Date | null;
                condition: import(".prisma/client").$Enums.CustodyCondition;
                currentLocation: string | null;
                imageUrl: string | null;
                currentAssigneeId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        })[];
        history: ({
            custodyItem: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.CustodyItemStatus;
                companyId: string;
                branchId: string | null;
                code: string;
                description: string | null;
                notes: string | null;
                attachments: import("@prisma/client/runtime/library").JsonValue | null;
                model: string | null;
                vendor: string | null;
                invoiceNumber: string | null;
                categoryId: string;
                serialNumber: string | null;
                brand: string | null;
                barcode: string | null;
                qrCode: string | null;
                purchaseDate: Date | null;
                purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
                warrantyExpiry: Date | null;
                condition: import(".prisma/client").$Enums.CustodyCondition;
                currentLocation: string | null;
                imageUrl: string | null;
                currentAssigneeId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        })[];
        totalValue: number | import("@prisma/client/runtime/library").Decimal;
    }>;
}
