import { UsersService } from './users.service';
import { CreateUserDto } from './dto/create-user.dto';
import { UpdateUserDto } from './dto/update-user.dto';
import { UserQueryDto } from './dto/user-query.dto';
import { ChangePasswordDto } from './dto/change-password.dto';
export declare class UsersController {
    private readonly usersService;
    constructor(usersService: UsersService);
    getProfile(userId: string, companyId: string): Promise<{
        faceData: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            faceEmbedding: string;
            faceImage: string | null;
            registeredAt: Date;
            lastVerifiedAt: Date | null;
            verificationCount: number;
            imageQuality: number | null;
            confidence: number | null;
        } | null;
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        } | null;
        department: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            branchId: string;
            workStartTime: string | null;
            workEndTime: string | null;
        } | null;
        manager: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
        } | null;
        employees: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
        }[];
        bankAccounts: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            iban: string;
            accountHolderName: string | null;
            bankName: string;
            bankCode: string | null;
            swiftCode: string | null;
            isPrimary: boolean;
            isVerified: boolean;
            verifiedAt: Date | null;
            verifiedBy: string | null;
        }[];
        contracts: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.ContractStatus;
            annualLeaveDays: number;
            type: import(".prisma/client").$Enums.ContractType;
            endDate: Date | null;
            startDate: Date;
            notes: string | null;
            userId: string;
            contractNumber: string | null;
            probationEndDate: Date | null;
            terminatedAt: Date | null;
            terminationReason: string | null;
            terminatedBy: string | null;
            renewalCount: number;
            previousContractId: string | null;
            salaryCycle: string;
            basicSalary: import("@prisma/client/runtime/library").Decimal | null;
            housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
            transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
            otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
            totalSalary: import("@prisma/client/runtime/library").Decimal | null;
            contractJobTitle: string | null;
            workLocation: string | null;
            workingHoursPerWeek: number;
            noticePeriodDays: number;
            employeeSignature: boolean;
            employeeSignedAt: Date | null;
            employerSignature: boolean;
            employerSignedAt: Date | null;
            signedByUserId: string | null;
            qiwaContractId: string | null;
            qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
            qiwaAuthDate: Date | null;
            qiwaRejectReason: string | null;
            qiwaLastSync: Date | null;
            documentUrl: string | null;
            additionalTerms: string | null;
        }[];
        costCenter: {
            id: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: string;
            companyId: string | null;
            managerId: string | null;
            code: string;
            nameAr: string;
            type: string;
            description: string | null;
            version: number;
            effectiveFrom: Date;
            effectiveTo: Date | null;
            level: number;
            path: string | null;
            isAllowOverbudget: boolean;
            parentId: string | null;
        } | null;
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    updateProfile(userId: string, updateUserDto: UpdateUserDto, companyId: string): Promise<{
        branch: {
            id: string;
            name: string;
        } | null;
        department: {
            id: string;
            name: string;
        } | null;
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    changePassword(userId: string, changePasswordDto: ChangePasswordDto): Promise<{
        message: string;
    }>;
    create(createUserDto: CreateUserDto, companyId: string): Promise<{
        branch: {
            id: string;
            name: string;
        } | null;
        department: {
            id: string;
            name: string;
        } | null;
        manager: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    findAll(req: any, query: UserQueryDto, companyId: string): Promise<{
        data: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            faceData: {
                faceImage: string | null;
                registeredAt: Date;
            } | null;
            branch: {
                id: string;
                name: string;
            } | null;
            department: {
                id: string;
                name: string;
            } | null;
            manager: {
                id: string;
                firstName: string;
                lastName: string;
            } | null;
            costCenter: {
                id: string;
                code: string;
                nameAr: string;
            } | null;
        }[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    getMyTeam(managerId: string, companyId: string): Promise<{
        id: string;
        email: string;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        status: import(".prisma/client").$Enums.UserStatus;
    }[]>;
    findOne(id: string, companyId: string): Promise<{
        faceData: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            faceEmbedding: string;
            faceImage: string | null;
            registeredAt: Date;
            lastVerifiedAt: Date | null;
            verificationCount: number;
            imageQuality: number | null;
            confidence: number | null;
        } | null;
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        } | null;
        department: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            branchId: string;
            workStartTime: string | null;
            workEndTime: string | null;
        } | null;
        manager: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
        } | null;
        employees: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
        }[];
        bankAccounts: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            iban: string;
            accountHolderName: string | null;
            bankName: string;
            bankCode: string | null;
            swiftCode: string | null;
            isPrimary: boolean;
            isVerified: boolean;
            verifiedAt: Date | null;
            verifiedBy: string | null;
        }[];
        contracts: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.ContractStatus;
            annualLeaveDays: number;
            type: import(".prisma/client").$Enums.ContractType;
            endDate: Date | null;
            startDate: Date;
            notes: string | null;
            userId: string;
            contractNumber: string | null;
            probationEndDate: Date | null;
            terminatedAt: Date | null;
            terminationReason: string | null;
            terminatedBy: string | null;
            renewalCount: number;
            previousContractId: string | null;
            salaryCycle: string;
            basicSalary: import("@prisma/client/runtime/library").Decimal | null;
            housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
            transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
            otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
            totalSalary: import("@prisma/client/runtime/library").Decimal | null;
            contractJobTitle: string | null;
            workLocation: string | null;
            workingHoursPerWeek: number;
            noticePeriodDays: number;
            employeeSignature: boolean;
            employeeSignedAt: Date | null;
            employerSignature: boolean;
            employerSignedAt: Date | null;
            signedByUserId: string | null;
            qiwaContractId: string | null;
            qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
            qiwaAuthDate: Date | null;
            qiwaRejectReason: string | null;
            qiwaLastSync: Date | null;
            documentUrl: string | null;
            additionalTerms: string | null;
        }[];
        costCenter: {
            id: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: string;
            companyId: string | null;
            managerId: string | null;
            code: string;
            nameAr: string;
            type: string;
            description: string | null;
            version: number;
            effectiveFrom: Date;
            effectiveTo: Date | null;
            level: number;
            path: string | null;
            isAllowOverbudget: boolean;
            parentId: string | null;
        } | null;
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    update(id: string, updateUserDto: UpdateUserDto, companyId: string): Promise<{
        branch: {
            id: string;
            name: string;
        } | null;
        department: {
            id: string;
            name: string;
        } | null;
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    remove(id: string, companyId: string): Promise<{
        message: string;
    }>;
    activate(id: string): Promise<{
        message: string;
    }>;
    resetFace(id: string, companyId: string): Promise<{
        message: string;
        userId: string;
        faceRegistered: boolean;
    }>;
}
