import { PerformanceReviewsService } from './performance-reviews.service';
import { AiGoalAssistantService } from './ai-goal-assistant.service';
import { CreateReviewCycleDto, UpdateReviewCycleDto, SubmitSelfReviewDto, SubmitManagerReviewDto, CalibrateReviewDto } from './dto';
interface RequestWithUser {
    user: {
        id: string;
        companyId: string;
    };
}
export declare class PerformanceReviewsController {
    private readonly performanceReviewsService;
    private readonly aiGoalAssistantService;
    constructor(performanceReviewsService: PerformanceReviewsService, aiGoalAssistantService: AiGoalAssistantService);
    createCycle(req: RequestWithUser, dto: CreateReviewCycleDto): Promise<{
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
        periodStart: Date;
        periodEnd: Date;
        selfReviewStart: Date | null;
        selfReviewEnd: Date | null;
        managerReviewStart: Date | null;
        managerReviewEnd: Date | null;
        feedbackStart: Date | null;
        feedbackEnd: Date | null;
        calibrationStart: Date | null;
        calibrationEnd: Date | null;
        includeSelfReview: boolean;
        include360Feedback: boolean;
        includeGoalRating: boolean;
        includeCompetencyRating: boolean;
        goalWeight: number;
        competencyWeight: number;
        valueWeight: number;
        competencyFrameworkId: string | null;
    }>;
    findAllCycles(req: RequestWithUser): Promise<({
        _count: {
            reviews: number;
        };
    } & {
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
        periodStart: Date;
        periodEnd: Date;
        selfReviewStart: Date | null;
        selfReviewEnd: Date | null;
        managerReviewStart: Date | null;
        managerReviewEnd: Date | null;
        feedbackStart: Date | null;
        feedbackEnd: Date | null;
        calibrationStart: Date | null;
        calibrationEnd: Date | null;
        includeSelfReview: boolean;
        include360Feedback: boolean;
        includeGoalRating: boolean;
        includeCompetencyRating: boolean;
        goalWeight: number;
        competencyWeight: number;
        valueWeight: number;
        competencyFrameworkId: string | null;
    })[]>;
    findCycleById(req: RequestWithUser, id: string): Promise<{
        reviews: {
            id: string;
            status: import(".prisma/client").$Enums.PerformanceReviewStatus;
            managerId: string;
            employeeId: string;
            nineBoxPosition: string | null;
            finalRating: import("@prisma/client/runtime/library").Decimal | null;
        }[];
    } & {
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
        periodStart: Date;
        periodEnd: Date;
        selfReviewStart: Date | null;
        selfReviewEnd: Date | null;
        managerReviewStart: Date | null;
        managerReviewEnd: Date | null;
        feedbackStart: Date | null;
        feedbackEnd: Date | null;
        calibrationStart: Date | null;
        calibrationEnd: Date | null;
        includeSelfReview: boolean;
        include360Feedback: boolean;
        includeGoalRating: boolean;
        includeCompetencyRating: boolean;
        goalWeight: number;
        competencyWeight: number;
        valueWeight: number;
        competencyFrameworkId: string | null;
    }>;
    updateCycle(req: RequestWithUser, id: string, dto: UpdateReviewCycleDto): Promise<{
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
        periodStart: Date;
        periodEnd: Date;
        selfReviewStart: Date | null;
        selfReviewEnd: Date | null;
        managerReviewStart: Date | null;
        managerReviewEnd: Date | null;
        feedbackStart: Date | null;
        feedbackEnd: Date | null;
        calibrationStart: Date | null;
        calibrationEnd: Date | null;
        includeSelfReview: boolean;
        include360Feedback: boolean;
        includeGoalRating: boolean;
        includeCompetencyRating: boolean;
        goalWeight: number;
        competencyWeight: number;
        valueWeight: number;
        competencyFrameworkId: string | null;
    }>;
    startCycle(req: RequestWithUser, id: string): Promise<{
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
        periodStart: Date;
        periodEnd: Date;
        selfReviewStart: Date | null;
        selfReviewEnd: Date | null;
        managerReviewStart: Date | null;
        managerReviewEnd: Date | null;
        feedbackStart: Date | null;
        feedbackEnd: Date | null;
        calibrationStart: Date | null;
        calibrationEnd: Date | null;
        includeSelfReview: boolean;
        include360Feedback: boolean;
        includeGoalRating: boolean;
        includeCompetencyRating: boolean;
        goalWeight: number;
        competencyWeight: number;
        valueWeight: number;
        competencyFrameworkId: string | null;
    }>;
    deleteCycle(req: RequestWithUser, id: string): Promise<{
        id: string;
        name: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
        companyId: string;
        type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
        periodStart: Date;
        periodEnd: Date;
        selfReviewStart: Date | null;
        selfReviewEnd: Date | null;
        managerReviewStart: Date | null;
        managerReviewEnd: Date | null;
        feedbackStart: Date | null;
        feedbackEnd: Date | null;
        calibrationStart: Date | null;
        calibrationEnd: Date | null;
        includeSelfReview: boolean;
        include360Feedback: boolean;
        includeGoalRating: boolean;
        includeCompetencyRating: boolean;
        goalWeight: number;
        competencyWeight: number;
        valueWeight: number;
        competencyFrameworkId: string | null;
    }>;
    findAllReviews(req: RequestWithUser, cycleId?: string): Promise<({
        cycle: {
            name: string;
            status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
            type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewStatus;
        companyId: string;
        managerId: string;
        employeeId: string;
        cycleId: string;
        performanceScore: number | null;
        potentialScore: number | null;
        nineBoxPosition: string | null;
        selfRating: import("@prisma/client/runtime/library").Decimal | null;
        selfComments: string | null;
        selfAchievements: import("@prisma/client/runtime/library").JsonValue | null;
        selfChallenges: import("@prisma/client/runtime/library").JsonValue | null;
        managerRating: import("@prisma/client/runtime/library").Decimal | null;
        managerComments: string | null;
        managerStrengths: import("@prisma/client/runtime/library").JsonValue | null;
        managerImprovements: import("@prisma/client/runtime/library").JsonValue | null;
        finalRating: import("@prisma/client/runtime/library").Decimal | null;
        finalComments: string | null;
        calibrationNotes: string | null;
        selfSubmittedAt: Date | null;
        managerSubmittedAt: Date | null;
        calibratedBy: string | null;
        calibratedAt: Date | null;
        employeeAcknowledged: boolean;
        employeeAcknowledgedAt: Date | null;
        employeeDisagreed: boolean;
        employeeDisagreeReason: string | null;
        aiSummary: string | null;
        aiBiasFlags: import("@prisma/client/runtime/library").JsonValue | null;
        aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
    })[]>;
    findReviewById(req: RequestWithUser, id: string): Promise<{
        developmentPlan: ({
            goals: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.DevelopmentGoalStatus;
                description: string;
                notes: string | null;
                category: string;
                actions: import("@prisma/client/runtime/library").JsonValue | null;
                completedAt: Date | null;
                progress: number;
                planId: string;
                targetDate: Date | null;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            companyId: string;
            year: number;
            employeeId: string;
            aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
            reviewId: string | null;
            aiStrengthsSummary: string | null;
            aiGapAnalysis: string | null;
        }) | null;
        cycle: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
            companyId: string;
            type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
            periodStart: Date;
            periodEnd: Date;
            selfReviewStart: Date | null;
            selfReviewEnd: Date | null;
            managerReviewStart: Date | null;
            managerReviewEnd: Date | null;
            feedbackStart: Date | null;
            feedbackEnd: Date | null;
            calibrationStart: Date | null;
            calibrationEnd: Date | null;
            includeSelfReview: boolean;
            include360Feedback: boolean;
            includeGoalRating: boolean;
            includeCompetencyRating: boolean;
            goalWeight: number;
            competencyWeight: number;
            valueWeight: number;
            competencyFrameworkId: string | null;
        };
        goalRatings: ({
            goal: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.GoalStatus;
                companyId: string;
                managerId: string | null;
                type: import(".prisma/client").$Enums.GoalType;
                description: string | null;
                startDate: Date | null;
                category: string | null;
                approvedAt: Date | null;
                title: string;
                titleEn: string | null;
                approvedBy: string | null;
                unit: string | null;
                completedAt: Date | null;
                dueDate: Date | null;
                rejectionReason: string | null;
                progress: number;
                weight: number;
                ownerId: string;
                targetValue: import("@prisma/client/runtime/library").Decimal | null;
                currentValue: import("@prisma/client/runtime/library").Decimal | null;
                isStretch: boolean;
                alignedCompanyGoalId: string | null;
                aiGenerated: boolean;
                aiPrompt: string | null;
                dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
                dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
                autoCalculated: boolean;
                lastSyncAt: Date | null;
                parentGoalId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            weight: number;
            goalId: string;
            selfRating: import("@prisma/client/runtime/library").Decimal | null;
            selfComments: string | null;
            managerRating: import("@prisma/client/runtime/library").Decimal | null;
            managerComments: string | null;
            finalRating: import("@prisma/client/runtime/library").Decimal | null;
            reviewId: string;
        })[];
        competencyRatings: ({
            competency: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                category: import(".prisma/client").$Enums.CompetencyCategory;
                sortOrder: number;
                frameworkId: string;
                level1Desc: string | null;
                level2Desc: string | null;
                level3Desc: string | null;
                level4Desc: string | null;
                level5Desc: string | null;
                behaviorExamples: import("@prisma/client/runtime/library").JsonValue | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            selfRating: number | null;
            selfComments: string | null;
            managerRating: number | null;
            managerComments: string | null;
            finalRating: number | null;
            reviewId: string;
            competencyId: string;
            selfEvidence: import("@prisma/client/runtime/library").JsonValue | null;
        })[];
        feedbackRequests: ({
            responses: {
                id: string;
                createdAt: Date;
                requestId: string;
                comment: string | null;
                rating: number | null;
                themes: import("@prisma/client/runtime/library").JsonValue | null;
                questionId: string | null;
                questionText: string;
                sentimentScore: import("@prisma/client/runtime/library").Decimal | null;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.FeedbackRequestStatus;
            dueDate: Date | null;
            submittedAt: Date | null;
            reviewId: string;
            requestorId: string;
            providerId: string;
            relationshipType: string;
            isAnonymous: boolean;
        })[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewStatus;
        companyId: string;
        managerId: string;
        employeeId: string;
        cycleId: string;
        performanceScore: number | null;
        potentialScore: number | null;
        nineBoxPosition: string | null;
        selfRating: import("@prisma/client/runtime/library").Decimal | null;
        selfComments: string | null;
        selfAchievements: import("@prisma/client/runtime/library").JsonValue | null;
        selfChallenges: import("@prisma/client/runtime/library").JsonValue | null;
        managerRating: import("@prisma/client/runtime/library").Decimal | null;
        managerComments: string | null;
        managerStrengths: import("@prisma/client/runtime/library").JsonValue | null;
        managerImprovements: import("@prisma/client/runtime/library").JsonValue | null;
        finalRating: import("@prisma/client/runtime/library").Decimal | null;
        finalComments: string | null;
        calibrationNotes: string | null;
        selfSubmittedAt: Date | null;
        managerSubmittedAt: Date | null;
        calibratedBy: string | null;
        calibratedAt: Date | null;
        employeeAcknowledged: boolean;
        employeeAcknowledgedAt: Date | null;
        employeeDisagreed: boolean;
        employeeDisagreeReason: string | null;
        aiSummary: string | null;
        aiBiasFlags: import("@prisma/client/runtime/library").JsonValue | null;
        aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    getMyReview(req: RequestWithUser, cycleId: string): Promise<{
        cycle: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PerformanceReviewCycleStatus;
            companyId: string;
            type: import(".prisma/client").$Enums.PerformanceReviewCycleType;
            periodStart: Date;
            periodEnd: Date;
            selfReviewStart: Date | null;
            selfReviewEnd: Date | null;
            managerReviewStart: Date | null;
            managerReviewEnd: Date | null;
            feedbackStart: Date | null;
            feedbackEnd: Date | null;
            calibrationStart: Date | null;
            calibrationEnd: Date | null;
            includeSelfReview: boolean;
            include360Feedback: boolean;
            includeGoalRating: boolean;
            includeCompetencyRating: boolean;
            goalWeight: number;
            competencyWeight: number;
            valueWeight: number;
            competencyFrameworkId: string | null;
        };
        goalRatings: ({
            goal: {
                id: string;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.GoalStatus;
                companyId: string;
                managerId: string | null;
                type: import(".prisma/client").$Enums.GoalType;
                description: string | null;
                startDate: Date | null;
                category: string | null;
                approvedAt: Date | null;
                title: string;
                titleEn: string | null;
                approvedBy: string | null;
                unit: string | null;
                completedAt: Date | null;
                dueDate: Date | null;
                rejectionReason: string | null;
                progress: number;
                weight: number;
                ownerId: string;
                targetValue: import("@prisma/client/runtime/library").Decimal | null;
                currentValue: import("@prisma/client/runtime/library").Decimal | null;
                isStretch: boolean;
                alignedCompanyGoalId: string | null;
                aiGenerated: boolean;
                aiPrompt: string | null;
                dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
                dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
                autoCalculated: boolean;
                lastSyncAt: Date | null;
                parentGoalId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            weight: number;
            goalId: string;
            selfRating: import("@prisma/client/runtime/library").Decimal | null;
            selfComments: string | null;
            managerRating: import("@prisma/client/runtime/library").Decimal | null;
            managerComments: string | null;
            finalRating: import("@prisma/client/runtime/library").Decimal | null;
            reviewId: string;
        })[];
        competencyRatings: ({
            competency: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                description: string | null;
                isActive: boolean;
                category: import(".prisma/client").$Enums.CompetencyCategory;
                sortOrder: number;
                frameworkId: string;
                level1Desc: string | null;
                level2Desc: string | null;
                level3Desc: string | null;
                level4Desc: string | null;
                level5Desc: string | null;
                behaviorExamples: import("@prisma/client/runtime/library").JsonValue | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            selfRating: number | null;
            selfComments: string | null;
            managerRating: number | null;
            managerComments: string | null;
            finalRating: number | null;
            reviewId: string;
            competencyId: string;
            selfEvidence: import("@prisma/client/runtime/library").JsonValue | null;
        })[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewStatus;
        companyId: string;
        managerId: string;
        employeeId: string;
        cycleId: string;
        performanceScore: number | null;
        potentialScore: number | null;
        nineBoxPosition: string | null;
        selfRating: import("@prisma/client/runtime/library").Decimal | null;
        selfComments: string | null;
        selfAchievements: import("@prisma/client/runtime/library").JsonValue | null;
        selfChallenges: import("@prisma/client/runtime/library").JsonValue | null;
        managerRating: import("@prisma/client/runtime/library").Decimal | null;
        managerComments: string | null;
        managerStrengths: import("@prisma/client/runtime/library").JsonValue | null;
        managerImprovements: import("@prisma/client/runtime/library").JsonValue | null;
        finalRating: import("@prisma/client/runtime/library").Decimal | null;
        finalComments: string | null;
        calibrationNotes: string | null;
        selfSubmittedAt: Date | null;
        managerSubmittedAt: Date | null;
        calibratedBy: string | null;
        calibratedAt: Date | null;
        employeeAcknowledged: boolean;
        employeeAcknowledgedAt: Date | null;
        employeeDisagreed: boolean;
        employeeDisagreeReason: string | null;
        aiSummary: string | null;
        aiBiasFlags: import("@prisma/client/runtime/library").JsonValue | null;
        aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    submitSelfReview(req: RequestWithUser, id: string, dto: SubmitSelfReviewDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewStatus;
        companyId: string;
        managerId: string;
        employeeId: string;
        cycleId: string;
        performanceScore: number | null;
        potentialScore: number | null;
        nineBoxPosition: string | null;
        selfRating: import("@prisma/client/runtime/library").Decimal | null;
        selfComments: string | null;
        selfAchievements: import("@prisma/client/runtime/library").JsonValue | null;
        selfChallenges: import("@prisma/client/runtime/library").JsonValue | null;
        managerRating: import("@prisma/client/runtime/library").Decimal | null;
        managerComments: string | null;
        managerStrengths: import("@prisma/client/runtime/library").JsonValue | null;
        managerImprovements: import("@prisma/client/runtime/library").JsonValue | null;
        finalRating: import("@prisma/client/runtime/library").Decimal | null;
        finalComments: string | null;
        calibrationNotes: string | null;
        selfSubmittedAt: Date | null;
        managerSubmittedAt: Date | null;
        calibratedBy: string | null;
        calibratedAt: Date | null;
        employeeAcknowledged: boolean;
        employeeAcknowledgedAt: Date | null;
        employeeDisagreed: boolean;
        employeeDisagreeReason: string | null;
        aiSummary: string | null;
        aiBiasFlags: import("@prisma/client/runtime/library").JsonValue | null;
        aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    submitManagerReview(req: RequestWithUser, id: string, dto: SubmitManagerReviewDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewStatus;
        companyId: string;
        managerId: string;
        employeeId: string;
        cycleId: string;
        performanceScore: number | null;
        potentialScore: number | null;
        nineBoxPosition: string | null;
        selfRating: import("@prisma/client/runtime/library").Decimal | null;
        selfComments: string | null;
        selfAchievements: import("@prisma/client/runtime/library").JsonValue | null;
        selfChallenges: import("@prisma/client/runtime/library").JsonValue | null;
        managerRating: import("@prisma/client/runtime/library").Decimal | null;
        managerComments: string | null;
        managerStrengths: import("@prisma/client/runtime/library").JsonValue | null;
        managerImprovements: import("@prisma/client/runtime/library").JsonValue | null;
        finalRating: import("@prisma/client/runtime/library").Decimal | null;
        finalComments: string | null;
        calibrationNotes: string | null;
        selfSubmittedAt: Date | null;
        managerSubmittedAt: Date | null;
        calibratedBy: string | null;
        calibratedAt: Date | null;
        employeeAcknowledged: boolean;
        employeeAcknowledgedAt: Date | null;
        employeeDisagreed: boolean;
        employeeDisagreeReason: string | null;
        aiSummary: string | null;
        aiBiasFlags: import("@prisma/client/runtime/library").JsonValue | null;
        aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    calibrateReview(req: RequestWithUser, id: string, dto: CalibrateReviewDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewStatus;
        companyId: string;
        managerId: string;
        employeeId: string;
        cycleId: string;
        performanceScore: number | null;
        potentialScore: number | null;
        nineBoxPosition: string | null;
        selfRating: import("@prisma/client/runtime/library").Decimal | null;
        selfComments: string | null;
        selfAchievements: import("@prisma/client/runtime/library").JsonValue | null;
        selfChallenges: import("@prisma/client/runtime/library").JsonValue | null;
        managerRating: import("@prisma/client/runtime/library").Decimal | null;
        managerComments: string | null;
        managerStrengths: import("@prisma/client/runtime/library").JsonValue | null;
        managerImprovements: import("@prisma/client/runtime/library").JsonValue | null;
        finalRating: import("@prisma/client/runtime/library").Decimal | null;
        finalComments: string | null;
        calibrationNotes: string | null;
        selfSubmittedAt: Date | null;
        managerSubmittedAt: Date | null;
        calibratedBy: string | null;
        calibratedAt: Date | null;
        employeeAcknowledged: boolean;
        employeeAcknowledgedAt: Date | null;
        employeeDisagreed: boolean;
        employeeDisagreeReason: string | null;
        aiSummary: string | null;
        aiBiasFlags: import("@prisma/client/runtime/library").JsonValue | null;
        aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    acknowledgeReview(req: RequestWithUser, id: string, body: {
        disagree: boolean;
        reason?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PerformanceReviewStatus;
        companyId: string;
        managerId: string;
        employeeId: string;
        cycleId: string;
        performanceScore: number | null;
        potentialScore: number | null;
        nineBoxPosition: string | null;
        selfRating: import("@prisma/client/runtime/library").Decimal | null;
        selfComments: string | null;
        selfAchievements: import("@prisma/client/runtime/library").JsonValue | null;
        selfChallenges: import("@prisma/client/runtime/library").JsonValue | null;
        managerRating: import("@prisma/client/runtime/library").Decimal | null;
        managerComments: string | null;
        managerStrengths: import("@prisma/client/runtime/library").JsonValue | null;
        managerImprovements: import("@prisma/client/runtime/library").JsonValue | null;
        finalRating: import("@prisma/client/runtime/library").Decimal | null;
        finalComments: string | null;
        calibrationNotes: string | null;
        selfSubmittedAt: Date | null;
        managerSubmittedAt: Date | null;
        calibratedBy: string | null;
        calibratedAt: Date | null;
        employeeAcknowledged: boolean;
        employeeAcknowledgedAt: Date | null;
        employeeDisagreed: boolean;
        employeeDisagreeReason: string | null;
        aiSummary: string | null;
        aiBiasFlags: import("@prisma/client/runtime/library").JsonValue | null;
        aiRecommendations: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    getNineBoxGrid(req: RequestWithUser, cycleId: string): Promise<{
        grid: Record<string, string[]>;
        totalReviews: number;
        distribution: {
            position: string;
            count: number;
            percentage: string | number;
        }[];
    }>;
    getCycleAnalytics(req: RequestWithUser, cycleId: string): Promise<{
        stats: {
            total: number;
            notStarted: number;
            selfReview: number;
            managerReview: number;
            calibration: number;
            completed: number;
        };
        completionRate: string | number;
        avgRating: string | null;
    }>;
    generateGoal(req: RequestWithUser, body: {
        prompt: string;
        context?: string;
    }): Promise<{
        title: string;
        titleEn?: string;
        description: string;
        targetValue?: number;
        unit?: string;
        suggestions: string[];
    }>;
    generateOKR(req: RequestWithUser, body: {
        objective: string;
        context?: string;
    }): Promise<{
        objective: {
            title: string;
            description: string;
        };
        keyResults: Array<{
            title: string;
            targetValue: number;
            unit: string;
        }>;
    }>;
}
export {};
