import { AdvancesService } from './advances.service';
import { UploadService } from '../../common/upload/upload.service';
import { CreateAdvanceRequestDto, ManagerDecisionDto, HrDecisionDto } from './dto/advance-request.dto';
export declare class AdvancesController {
    private readonly advancesService;
    private readonly uploadService;
    constructor(advancesService: AdvancesService, uploadService: UploadService);
    uploadAttachments(files: Express.Multer.File[]): Promise<{
        message: string;
        files: import("../../common/upload/upload.service").UploadedFile[];
    }>;
    createRequest(req: any, dto: CreateAdvanceRequestDto): Promise<{
        user: {
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getMyRequests(req: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }[]>;
    getManagerInbox(req: any): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    managerDecision(id: string, req: any, dto: ManagerDecisionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getHRInbox(req: any): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    hrDecision(id: string, req: any, dto: HrDecisionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getFinanceInbox(req: any): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    financeDecision(id: string, req: any, dto: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getCEOInbox(req: any): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            firstName: string;
            lastName: string;
        } | null;
        financeApprover: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    ceoDecision(id: string, req: any, dto: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getRequestDetails(id: string, req: any): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }) | null>;
    getEmployeePreviousAdvances(employeeId: string, req: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }[]>;
}
