import { PrismaService } from '../../common/prisma/prisma.service';
import { NotificationsService } from '../notifications/notifications.service';
import { PermissionsService } from '../permissions/permissions.service';
import { ApprovalWorkflowService } from '../../common/services/approval-workflow.service';
import { CreateAdvanceRequestDto, ManagerDecisionDto, HrDecisionDto } from './dto/advance-request.dto';
export declare class FinanceDecisionDto {
    decision: 'APPROVED' | 'REJECTED' | 'DELAYED';
    notes?: string;
}
export declare class CEODecisionDto {
    decision: 'APPROVED' | 'REJECTED' | 'DELAYED';
    notes?: string;
}
export declare class AdvancesService {
    private prisma;
    private notificationsService;
    private permissionsService;
    private approvalWorkflowService;
    constructor(prisma: PrismaService, notificationsService: NotificationsService, permissionsService: PermissionsService, approvalWorkflowService: ApprovalWorkflowService);
    createAdvanceRequest(userId: string, companyId: string, dto: CreateAdvanceRequestDto): Promise<{
        user: {
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getManagerInbox(managerId: string, companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    managerDecision(requestId: string, companyId: string, managerId: string, dto: ManagerDecisionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getHRInbox(hrId: string, companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    hrDecision(requestId: string, companyId: string, hrId: string, dto: HrDecisionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getMyRequests(userId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }[]>;
    getRequestDetails(requestId: string, companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }) | null>;
    getEmployeePreviousAdvances(employeeId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }[]>;
    private getApproversForStep;
    getFinanceInbox(financeId: string, companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    financeDecision(requestId: string, companyId: string, financeId: string, dto: FinanceDecisionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    getCEOInbox(ceoId: string, companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            firstName: string;
            lastName: string;
        } | null;
        financeApprover: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    })[]>;
    ceoDecision(requestId: string, companyId: string, ceoId: string, dto: CEODecisionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
}
