import { AuthService } from './auth.service';
import { LoginDto } from './dto/login.dto';
import { RegisterDto } from './dto/register.dto';
import { RefreshTokenDto } from './dto/refresh-token.dto';
import { ForgotPasswordDto } from './dto/forgot-password.dto';
import { ResetPasswordDto } from './dto/reset-password.dto';
import { UpdateFcmTokenDto } from './dto/update-fcm-token.dto';
export declare class AuthController {
    private readonly authService;
    constructor(authService: AuthService);
    login(loginDto: LoginDto, req: any): Promise<{
        accessToken: string;
        refreshToken: string;
        expiresIn: any;
        user: {
            branch: {
                id: string;
                name: string;
                nameEn: string | null;
                address: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                isActive: boolean;
                workStartTime: string;
                workEndTime: string;
                lateGracePeriod: number;
                geofenceRadius: number;
                latitude: import("@prisma/client/runtime/library").Decimal;
                longitude: import("@prisma/client/runtime/library").Decimal;
                timezone: string;
                earlyCheckInPeriod: number;
                earlyCheckOutPeriod: number;
                workingDays: string;
            } | null;
            department: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                branchId: string;
                workStartTime: string | null;
                workEndTime: string | null;
            } | null;
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
    }>;
    register(registerDto: RegisterDto): Promise<{
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    refreshTokens(refreshTokenDto: RefreshTokenDto): Promise<{
        accessToken: string;
        refreshToken: string;
        expiresIn: any;
    }>;
    logout(userId: string, refreshToken?: string): Promise<{
        message: string;
    }>;
    forgotPassword(forgotPasswordDto: ForgotPasswordDto): Promise<{
        resetToken?: string | undefined;
        message: string;
    }>;
    resetPassword(resetPasswordDto: ResetPasswordDto): Promise<void>;
    updateFcmToken(userId: string, updateFcmTokenDto: UpdateFcmTokenDto): Promise<{
        message: string;
    }>;
}
