import { PrismaService } from '../../common/prisma/prisma.service';
import { CreateRetroPayDto } from './dto/create-retro-pay.dto';
import { Decimal } from '@prisma/client/runtime/library';
export declare class RetroPayService {
    private prisma;
    constructor(prisma: PrismaService);
    create(dto: CreateRetroPayDto, createdById: string): Promise<{
        employee: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroPayStatus;
        companyId: string | null;
        paidAt: Date | null;
        employeeId: string;
        notes: string | null;
        effectiveFrom: Date;
        effectiveTo: Date;
        createdById: string | null;
        reason: string;
        approvedAt: Date | null;
        oldAmount: Decimal;
        newAmount: Decimal;
        difference: Decimal;
        monthsCount: number;
        totalAmount: Decimal;
        approvedById: string | null;
    }>;
    private calculateMonthsDifference;
    findAll(): Promise<({
        employee: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroPayStatus;
        companyId: string | null;
        paidAt: Date | null;
        employeeId: string;
        notes: string | null;
        effectiveFrom: Date;
        effectiveTo: Date;
        createdById: string | null;
        reason: string;
        approvedAt: Date | null;
        oldAmount: Decimal;
        newAmount: Decimal;
        difference: Decimal;
        monthsCount: number;
        totalAmount: Decimal;
        approvedById: string | null;
    })[]>;
    findByEmployee(employeeId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroPayStatus;
        companyId: string | null;
        paidAt: Date | null;
        employeeId: string;
        notes: string | null;
        effectiveFrom: Date;
        effectiveTo: Date;
        createdById: string | null;
        reason: string;
        approvedAt: Date | null;
        oldAmount: Decimal;
        newAmount: Decimal;
        difference: Decimal;
        monthsCount: number;
        totalAmount: Decimal;
        approvedById: string | null;
    }[]>;
    approve(id: string, approvedById: string): Promise<{
        employee: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroPayStatus;
        companyId: string | null;
        paidAt: Date | null;
        employeeId: string;
        notes: string | null;
        effectiveFrom: Date;
        effectiveTo: Date;
        createdById: string | null;
        reason: string;
        approvedAt: Date | null;
        oldAmount: Decimal;
        newAmount: Decimal;
        difference: Decimal;
        monthsCount: number;
        totalAmount: Decimal;
        approvedById: string | null;
    }>;
    markAsPaid(id: string): Promise<{
        employee: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroPayStatus;
        companyId: string | null;
        paidAt: Date | null;
        employeeId: string;
        notes: string | null;
        effectiveFrom: Date;
        effectiveTo: Date;
        createdById: string | null;
        reason: string;
        approvedAt: Date | null;
        oldAmount: Decimal;
        newAmount: Decimal;
        difference: Decimal;
        monthsCount: number;
        totalAmount: Decimal;
        approvedById: string | null;
    }>;
    cancel(id: string): Promise<{
        employee: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroPayStatus;
        companyId: string | null;
        paidAt: Date | null;
        employeeId: string;
        notes: string | null;
        effectiveFrom: Date;
        effectiveTo: Date;
        createdById: string | null;
        reason: string;
        approvedAt: Date | null;
        oldAmount: Decimal;
        newAmount: Decimal;
        difference: Decimal;
        monthsCount: number;
        totalAmount: Decimal;
        approvedById: string | null;
    }>;
    getStats(): Promise<{
        pendingCount: number;
        approvedCount: number;
        totalPaidAmount: number | Decimal;
    }>;
}
