import { PrismaService } from '../../common/prisma/prisma.service';
import { GoalType, GoalStatus } from '@prisma/client';
export declare class GoalsService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    create(companyId: string, userId: string, dto: {
        title: string;
        titleEn?: string;
        description?: string;
        type?: GoalType;
        startDate?: string;
        dueDate?: string;
        targetValue?: number;
        unit?: string;
        weight?: number;
        category?: string;
        isStretch?: boolean;
        parentGoalId?: string;
        alignedCompanyGoalId?: string;
        managerId?: string;
        aiGenerated?: boolean;
        aiPrompt?: string;
    }): Promise<{
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    findAll(companyId: string, filters?: {
        ownerId?: string;
        type?: GoalType;
        status?: GoalStatus;
    }): Promise<({
        childGoals: {
            id: string;
            status: import(".prisma/client").$Enums.GoalStatus;
            title: string;
            progress: number;
        }[];
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    findById(companyId: string, id: string): Promise<{
        parentGoal: {
            id: string;
            title: string;
        } | null;
        childGoals: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.GoalStatus;
            companyId: string;
            managerId: string | null;
            type: import(".prisma/client").$Enums.GoalType;
            description: string | null;
            startDate: Date | null;
            category: string | null;
            approvedAt: Date | null;
            title: string;
            titleEn: string | null;
            approvedBy: string | null;
            unit: string | null;
            completedAt: Date | null;
            dueDate: Date | null;
            rejectionReason: string | null;
            progress: number;
            weight: number;
            ownerId: string;
            targetValue: import("@prisma/client/runtime/library").Decimal | null;
            currentValue: import("@prisma/client/runtime/library").Decimal | null;
            isStretch: boolean;
            alignedCompanyGoalId: string | null;
            aiGenerated: boolean;
            aiPrompt: string | null;
            dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
            dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
            autoCalculated: boolean;
            lastSyncAt: Date | null;
            parentGoalId: string | null;
        }[];
        keyResults: ({
            checkIns: {
                id: string;
                createdAt: Date;
                notes: string | null;
                userId: string;
                newValue: import("@prisma/client/runtime/library").Decimal;
                previousValue: import("@prisma/client/runtime/library").Decimal;
                keyResultId: string;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        })[];
        checkIns: {
            id: string;
            createdAt: Date;
            userId: string;
            newValue: import("@prisma/client/runtime/library").Decimal;
            confidence: number | null;
            previousValue: import("@prisma/client/runtime/library").Decimal;
            statusUpdate: string | null;
            blockers: string | null;
            nextSteps: string | null;
            goalId: string;
        }[];
        ratings: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            weight: number;
            goalId: string;
            selfRating: import("@prisma/client/runtime/library").Decimal | null;
            selfComments: string | null;
            managerRating: import("@prisma/client/runtime/library").Decimal | null;
            managerComments: string | null;
            finalRating: import("@prisma/client/runtime/library").Decimal | null;
            reviewId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    update(companyId: string, id: string, dto: Partial<{
        title: string;
        titleEn: string;
        description: string;
        type: GoalType;
        status: GoalStatus;
        startDate: string;
        dueDate: string;
        targetValue: number;
        currentValue: number;
        unit: string;
        progress: number;
        weight: number;
        category: string;
        isStretch: boolean;
    }>): Promise<{
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    delete(companyId: string, id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    submitForApproval(companyId: string, id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    approveGoal(companyId: string, id: string, approverId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    rejectGoal(companyId: string, id: string, reason: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    createCheckIn(companyId: string, goalId: string, userId: string, dto: {
        newValue: number;
        statusUpdate?: string;
        blockers?: string;
        nextSteps?: string;
        confidence?: number;
    }): Promise<{
        id: string;
        createdAt: Date;
        userId: string;
        newValue: import("@prisma/client/runtime/library").Decimal;
        confidence: number | null;
        previousValue: import("@prisma/client/runtime/library").Decimal;
        statusUpdate: string | null;
        blockers: string | null;
        nextSteps: string | null;
        goalId: string;
    }>;
    getCheckIns(companyId: string, goalId: string): Promise<{
        id: string;
        createdAt: Date;
        userId: string;
        newValue: import("@prisma/client/runtime/library").Decimal;
        confidence: number | null;
        previousValue: import("@prisma/client/runtime/library").Decimal;
        statusUpdate: string | null;
        blockers: string | null;
        nextSteps: string | null;
        goalId: string;
    }[]>;
    addKeyResult(companyId: string, goalId: string, dto: {
        title: string;
        description?: string;
        targetValue: number;
        unit?: string;
        dueDate?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    updateKeyResult(id: string, dto: {
        title?: string;
        description?: string;
        targetValue?: number;
        currentValue?: number;
        unit?: string;
        dueDate?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    deleteKeyResult(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    checkInKeyResult(keyResultId: string, userId: string, dto: {
        newValue: number;
        notes?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    getCompanyGoals(companyId: string): Promise<({
        childGoals: {
            id: string;
            title: string;
            progress: number;
            ownerId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    getMyGoals(companyId: string, userId: string): Promise<({
        parentGoal: {
            id: string;
            title: string;
        } | null;
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    getTeamGoals(companyId: string, managerId: string): Promise<({
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    getAvailableDataSources(): {
        key: string;
        label: string;
        labelEn: string;
        icon: string;
        metrics: string[];
    }[];
    syncGoalFromDataSource(companyId: string, goalId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    syncAllAutoCalculatedGoals(companyId: string): Promise<{
        syncedCount: number;
        totalGoals: number;
    }>;
}
