import { GoalsService } from './goals.service';
import { GoalType, GoalStatus } from '@prisma/client';
interface RequestWithUser {
    user: {
        id: string;
        companyId: string;
    };
}
export declare class GoalsController {
    private readonly goalsService;
    constructor(goalsService: GoalsService);
    create(req: RequestWithUser, dto: any): Promise<{
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    findAll(req: RequestWithUser, ownerId?: string, type?: GoalType, status?: GoalStatus): Promise<({
        childGoals: {
            id: string;
            status: import(".prisma/client").$Enums.GoalStatus;
            title: string;
            progress: number;
        }[];
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    getMyGoals(req: RequestWithUser): Promise<({
        parentGoal: {
            id: string;
            title: string;
        } | null;
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    getTeamGoals(req: RequestWithUser): Promise<({
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    getCompanyGoals(req: RequestWithUser): Promise<({
        childGoals: {
            id: string;
            title: string;
            progress: number;
            ownerId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    })[]>;
    getAvailableDataSources(): Promise<{
        key: string;
        label: string;
        labelEn: string;
        icon: string;
        metrics: string[];
    }[]>;
    syncAllAutoCalculatedGoals(req: RequestWithUser): Promise<{
        syncedCount: number;
        totalGoals: number;
    }>;
    findById(req: RequestWithUser, id: string): Promise<{
        parentGoal: {
            id: string;
            title: string;
        } | null;
        childGoals: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.GoalStatus;
            companyId: string;
            managerId: string | null;
            type: import(".prisma/client").$Enums.GoalType;
            description: string | null;
            startDate: Date | null;
            category: string | null;
            approvedAt: Date | null;
            title: string;
            titleEn: string | null;
            approvedBy: string | null;
            unit: string | null;
            completedAt: Date | null;
            dueDate: Date | null;
            rejectionReason: string | null;
            progress: number;
            weight: number;
            ownerId: string;
            targetValue: import("@prisma/client/runtime/library").Decimal | null;
            currentValue: import("@prisma/client/runtime/library").Decimal | null;
            isStretch: boolean;
            alignedCompanyGoalId: string | null;
            aiGenerated: boolean;
            aiPrompt: string | null;
            dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
            dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
            autoCalculated: boolean;
            lastSyncAt: Date | null;
            parentGoalId: string | null;
        }[];
        keyResults: ({
            checkIns: {
                id: string;
                createdAt: Date;
                notes: string | null;
                userId: string;
                newValue: import("@prisma/client/runtime/library").Decimal;
                previousValue: import("@prisma/client/runtime/library").Decimal;
                keyResultId: string;
            }[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        })[];
        checkIns: {
            id: string;
            createdAt: Date;
            userId: string;
            newValue: import("@prisma/client/runtime/library").Decimal;
            confidence: number | null;
            previousValue: import("@prisma/client/runtime/library").Decimal;
            statusUpdate: string | null;
            blockers: string | null;
            nextSteps: string | null;
            goalId: string;
        }[];
        ratings: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            weight: number;
            goalId: string;
            selfRating: import("@prisma/client/runtime/library").Decimal | null;
            selfComments: string | null;
            managerRating: import("@prisma/client/runtime/library").Decimal | null;
            managerComments: string | null;
            finalRating: import("@prisma/client/runtime/library").Decimal | null;
            reviewId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    update(req: RequestWithUser, id: string, dto: any): Promise<{
        keyResults: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            description: string | null;
            title: string;
            unit: string;
            dueDate: Date | null;
            progress: number;
            targetValue: import("@prisma/client/runtime/library").Decimal;
            currentValue: import("@prisma/client/runtime/library").Decimal;
            goalId: string;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    delete(req: RequestWithUser, id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    submitForApproval(req: RequestWithUser, id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    approveGoal(req: RequestWithUser, id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    rejectGoal(req: RequestWithUser, id: string, body: {
        reason: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
    createCheckIn(req: RequestWithUser, id: string, dto: any): Promise<{
        id: string;
        createdAt: Date;
        userId: string;
        newValue: import("@prisma/client/runtime/library").Decimal;
        confidence: number | null;
        previousValue: import("@prisma/client/runtime/library").Decimal;
        statusUpdate: string | null;
        blockers: string | null;
        nextSteps: string | null;
        goalId: string;
    }>;
    getCheckIns(req: RequestWithUser, id: string): Promise<{
        id: string;
        createdAt: Date;
        userId: string;
        newValue: import("@prisma/client/runtime/library").Decimal;
        confidence: number | null;
        previousValue: import("@prisma/client/runtime/library").Decimal;
        statusUpdate: string | null;
        blockers: string | null;
        nextSteps: string | null;
        goalId: string;
    }[]>;
    addKeyResult(req: RequestWithUser, goalId: string, dto: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    updateKeyResult(id: string, dto: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    deleteKeyResult(id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    checkInKeyResult(req: RequestWithUser, id: string, dto: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        description: string | null;
        title: string;
        unit: string;
        dueDate: Date | null;
        progress: number;
        targetValue: import("@prisma/client/runtime/library").Decimal;
        currentValue: import("@prisma/client/runtime/library").Decimal;
        goalId: string;
    }>;
    syncGoalFromDataSource(req: RequestWithUser, id: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.GoalStatus;
        companyId: string;
        managerId: string | null;
        type: import(".prisma/client").$Enums.GoalType;
        description: string | null;
        startDate: Date | null;
        category: string | null;
        approvedAt: Date | null;
        title: string;
        titleEn: string | null;
        approvedBy: string | null;
        unit: string | null;
        completedAt: Date | null;
        dueDate: Date | null;
        rejectionReason: string | null;
        progress: number;
        weight: number;
        ownerId: string;
        targetValue: import("@prisma/client/runtime/library").Decimal | null;
        currentValue: import("@prisma/client/runtime/library").Decimal | null;
        isStretch: boolean;
        alignedCompanyGoalId: string | null;
        aiGenerated: boolean;
        aiPrompt: string | null;
        dataSource: import(".prisma/client").$Enums.GoalDataSource | null;
        dataSourceConfig: import("@prisma/client/runtime/library").JsonValue | null;
        autoCalculated: boolean;
        lastSyncAt: Date | null;
        parentGoalId: string | null;
    }>;
}
export {};
