import { Request } from 'express';
import { LeavesService } from './leaves.service';
import { CreateLeaveRequestDto } from './dto/create-leave-request.dto';
import { LeaveQueryDto } from './dto/leave-query.dto';
import { ApproveLeaveDto } from './dto/approve-leave.dto';
import { WorkFromHomeDto } from './dto/work-from-home.dto';
import { UploadService } from '../../common/upload/upload.service';
export declare class LeavesController {
    private readonly leavesService;
    private readonly uploadService;
    constructor(leavesService: LeavesService, uploadService: UploadService);
    uploadAttachments(files: Express.Multer.File[]): Promise<{
        message: string;
        files: import("../../common/upload/upload.service").UploadedFile[];
    }>;
    createLeaveRequest(userId: string, companyId: string, createLeaveDto: CreateLeaveRequestDto, req: Request): Promise<{
        user: {
            firstName: string;
            lastName: string;
            managerId: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    }>;
    getMyLeaveRequests(userId: string, companyId: string, query: LeaveQueryDto): Promise<{
        data: ({
            approver: {
                firstName: string;
                lastName: string;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.LeaveStatus;
            companyId: string | null;
            type: import(".prisma/client").$Enums.LeaveType;
            endDate: Date;
            startDate: Date;
            notes: string | null;
            userId: string;
            requestedDays: number;
            approvedDays: number | null;
            reason: string;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            currentStep: import(".prisma/client").$Enums.ApprovalStep;
            managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
            managerDecisionAt: Date | null;
            managerNotes: string | null;
            managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
            hrDecisionAt: Date | null;
            hrDecisionNotes: string | null;
            hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            approverNotes: string | null;
            approvedAt: Date | null;
            fullPayDays: number | null;
            partialPayDays: number | null;
            unpaidDays: number | null;
            salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
            noticeDaysProvided: number | null;
            managerApproverId: string | null;
            hrApproverId: string | null;
            approverId: string | null;
            leaveTypeConfigId: string | null;
        })[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    getLeaveRequestById(id: string, companyId: string, userId: string): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
        approver: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    }>;
    getLeaveRequestWithEmployeeContext(id: string, companyId: string, userId: string): Promise<any>;
    cancelLeaveRequest(id: string, companyId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    }>;
    getPendingRequests(userId: string, companyId: string, query: LeaveQueryDto): Promise<{
        data: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
                jobTitle: string | null;
                department: {
                    name: string;
                } | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.LeaveStatus;
            companyId: string | null;
            type: import(".prisma/client").$Enums.LeaveType;
            endDate: Date;
            startDate: Date;
            notes: string | null;
            userId: string;
            requestedDays: number;
            approvedDays: number | null;
            reason: string;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            currentStep: import(".prisma/client").$Enums.ApprovalStep;
            managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
            managerDecisionAt: Date | null;
            managerNotes: string | null;
            managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
            hrDecisionAt: Date | null;
            hrDecisionNotes: string | null;
            hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            approverNotes: string | null;
            approvedAt: Date | null;
            fullPayDays: number | null;
            partialPayDays: number | null;
            unpaidDays: number | null;
            salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
            noticeDaysProvided: number | null;
            managerApproverId: string | null;
            hrApproverId: string | null;
            approverId: string | null;
            leaveTypeConfigId: string | null;
        })[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    approveLeaveRequest(id: string, companyId: string, approverId: string, approveDto: ApproveLeaveDto): Promise<({
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    }) | null>;
    rejectLeaveRequest(id: string, companyId: string, approverId: string, approveDto: ApproveLeaveDto): Promise<({
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    }) | null>;
    getManagerInbox(managerId: string, companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            department: {
                name: string;
            } | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    })[]>;
    getHRInbox(hrUserId: string, companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            jobTitle: string | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    })[]>;
    managerDecision(id: string, companyId: string, managerId: string, body: {
        decision: 'APPROVED' | 'REJECTED';
        notes?: string;
    }): Promise<({
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    }) | null>;
    hrDecision(id: string, companyId: string, hrUserId: string, body: {
        decision: 'APPROVED' | 'REJECTED' | 'DELAYED';
        notes?: string;
    }): Promise<({
        user: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        };
        managerApprover: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        } | null;
        hrApprover: {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    }) | null>;
    getAllLeaveRequests(companyId: string, query: LeaveQueryDto): Promise<{
        data: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
                department: {
                    name: string;
                } | null;
            };
            approver: {
                firstName: string;
                lastName: string;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.LeaveStatus;
            companyId: string | null;
            type: import(".prisma/client").$Enums.LeaveType;
            endDate: Date;
            startDate: Date;
            notes: string | null;
            userId: string;
            requestedDays: number;
            approvedDays: number | null;
            reason: string;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            currentStep: import(".prisma/client").$Enums.ApprovalStep;
            managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
            managerDecisionAt: Date | null;
            managerNotes: string | null;
            managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
            hrDecisionAt: Date | null;
            hrDecisionNotes: string | null;
            hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            approverNotes: string | null;
            approvedAt: Date | null;
            fullPayDays: number | null;
            partialPayDays: number | null;
            unpaidDays: number | null;
            salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
            noticeDaysProvided: number | null;
            managerApproverId: string | null;
            hrApproverId: string | null;
            approverId: string | null;
            leaveTypeConfigId: string | null;
        })[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    enableWorkFromHome(companyId: string, approverId: string, wfhDto: WorkFromHomeDto): Promise<{
        id: string;
        createdAt: Date;
        companyId: string | null;
        date: Date;
        userId: string;
        reason: string | null;
        approvedBy: string | null;
    }>;
    disableWorkFromHome(companyId: string, userId: string, date: string): Promise<{
        message: string;
    }>;
}
