import { PrismaService } from '../../common/prisma/prisma.service';
import { LeaveTypeConfigService } from './leave-type-config.service';
import { Decimal } from '@prisma/client/runtime/library';
export declare class LeaveBalanceService {
    private prisma;
    private leaveTypeConfigService;
    constructor(prisma: PrismaService, leaveTypeConfigService: LeaveTypeConfigService);
    getEmployeeBalances(userId: string, year?: number): Promise<{
        available: number;
        leaveType: {
            id: string;
            nameEn: string | null;
            code: string;
            nameAr: string;
            category: import(".prisma/client").$Enums.LeaveCategory;
            maxBalanceCap: number | null;
            allowCarryForward: boolean;
            isPaid: boolean;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    }[]>;
    getBalance(userId: string, leaveTypeId: string, year?: number): Promise<{
        available: number;
        leaveType: {
            id: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            code: string;
            nameAr: string;
            description: string | null;
            isActive: boolean;
            category: import(".prisma/client").$Enums.LeaveCategory;
            sortOrder: number;
            allowNegativeBalance: boolean;
            minNoticeDays: number;
            isOneTimeOnly: boolean;
            requiresAttachment: boolean;
            isEntitlementBased: boolean;
            defaultEntitlement: number;
            maxBalanceCap: number | null;
            allowCarryForward: boolean;
            maxCarryForwardDays: number | null;
            isPaid: boolean;
            paymentPercentage: number;
            attachmentRequiredAfterDays: number | null;
            carryForwardExpiryMonths: number | null;
            minRequestDays: number;
            maxRequestDays: number | null;
            deductFromAnnual: boolean;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    }>;
    initializeBalance(userId: string, leaveTypeId: string, year: number): Promise<{
        available: number;
        leaveType: {
            id: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            code: string;
            nameAr: string;
            description: string | null;
            isActive: boolean;
            category: import(".prisma/client").$Enums.LeaveCategory;
            sortOrder: number;
            allowNegativeBalance: boolean;
            minNoticeDays: number;
            isOneTimeOnly: boolean;
            requiresAttachment: boolean;
            isEntitlementBased: boolean;
            defaultEntitlement: number;
            maxBalanceCap: number | null;
            allowCarryForward: boolean;
            maxCarryForwardDays: number | null;
            isPaid: boolean;
            paymentPercentage: number;
            attachmentRequiredAfterDays: number | null;
            carryForwardExpiryMonths: number | null;
            minRequestDays: number;
            maxRequestDays: number | null;
            deductFromAnnual: boolean;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    }>;
    deductBalance(userId: string, leaveTypeId: string, days: number, year?: number): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    }>;
    restoreBalance(userId: string, leaveTypeId: string, days: number, year?: number): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    } | undefined>;
    addPendingDays(userId: string, leaveTypeId: string, days: number, year?: number): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    }>;
    removePendingDays(userId: string, leaveTypeId: string, days: number, year?: number): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    } | undefined>;
    carryForwardBalances(companyId: string, fromYear: number): Promise<{
        processed: number;
        carriedForward: number;
        expired: number;
    }>;
    recalculateEmployeeBalances(userId: string, year: number): Promise<{
        available: number;
        leaveType: {
            id: string;
            nameEn: string | null;
            code: string;
            nameAr: string;
            category: import(".prisma/client").$Enums.LeaveCategory;
            maxBalanceCap: number | null;
            allowCarryForward: boolean;
            isPaid: boolean;
        };
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string | null;
        year: number;
        userId: string;
        leaveTypeId: string;
        entitled: Decimal;
        carriedForward: Decimal;
        used: Decimal;
        pending: Decimal;
        timesUsed: number;
        carryForwardExpiresAt: Date | null;
    }[]>;
    private calculateAvailable;
}
