import { ContractsService } from './contracts.service';
import { CreateContractDto, UpdateContractDto, TerminateContractDto, RenewContractDto, SignContractDto, RejectContractDto, UpdateQiwaStatusDto } from './dto/contract.dto';
export declare class ContractsController {
    private contractsService;
    constructor(contractsService: ContractsService);
    findAll(companyId: string, status?: string, qiwaStatus?: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            isSaudi: boolean;
            nationalId: string | null;
            iqamaNumber: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    })[]>;
    getStats(companyId: string): Promise<{
        total: number;
        byStatus: {
            draft: number;
            pendingEmployee: number;
            pendingEmployer: number;
            active: number;
            expired: number;
            terminated: number;
        };
        byQiwaStatus: {
            notSubmitted: number;
            pending: number;
            authenticated: number;
            rejected: number;
        };
        expiringSoon: number;
        byType: {
            permanent: number;
            fixedTerm: number;
            partTime: number;
        };
    }>;
    getExpiring(companyId: string, days?: string): Promise<({
        user: {
            id: string;
            phone: string | null;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    })[]>;
    getPendingForEmployer(companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    })[]>;
    getPendingForEmployee(employeeId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }[]>;
    findByEmployee(userId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }[]>;
    findOne(id: string, companyId: string): Promise<{
        user: {
            id: string;
            phone: string | null;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            isSaudi: boolean;
            nationalId: string | null;
            iqamaNumber: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    create(dto: CreateContractDto, companyId: string, userId: string): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    update(id: string, dto: UpdateContractDto, companyId: string, userId: string): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    sendToEmployee(id: string, companyId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    employeeSign(id: string, dto: SignContractDto, companyId: string, employeeId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    employeeReject(id: string, dto: RejectContractDto, companyId: string, employeeId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    employerSign(id: string, dto: SignContractDto, companyId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    updateQiwaStatus(id: string, dto: UpdateQiwaStatusDto, companyId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    terminate(id: string, dto: TerminateContractDto, companyId: string, userId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    renew(id: string, dto: RenewContractDto, companyId: string, userId: string): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    }>;
    delete(id: string, companyId: string, userId: string): Promise<{
        success: boolean;
    }>;
}
