import { PrismaService } from '../../common/prisma/prisma.service';
export interface QiwaContractExport {
    contractNumber: string;
    employeeId: string;
    employeeName: string;
    nationalId: string;
    iqamaNumber: string | null;
    isSaudi: boolean;
    contractType: string;
    startDate: string;
    endDate: string | null;
    probationEndDate: string | null;
    jobTitle: string;
    workLocation: string | null;
    workingHoursPerWeek: number;
    basicSalary: number | null;
    housingAllowance: number | null;
    transportAllowance: number | null;
    otherAllowances: number | null;
    totalSalary: number | null;
    annualLeaveDays: number;
    noticePeriodDays: number;
    employeeSignature: boolean;
    employerSignature: boolean;
    qiwaContractId: string | null;
    qiwaStatus: string;
    status: string;
}
export declare class QiwaService {
    private prisma;
    constructor(prisma: PrismaService);
    exportContracts(companyId: string, status?: string, qiwaStatus?: string): Promise<QiwaContractExport[]>;
    exportContractsCsv(companyId: string, status?: string): Promise<string>;
    getContractStats(companyId: string): Promise<{
        total: number;
        active: number;
        expired: number;
        terminated: number;
        draft: number;
        pendingSignatures: number;
        expiringSoon30: number;
        expiringSoon60: number;
        byType: {
            permanent: number;
            fixedTerm: number;
            partTime: number;
            probation: number;
        };
        byQiwaStatus: {
            notSubmitted: number;
            pending: number;
            authenticated: number;
            rejected: number;
        };
    }>;
    getContractsRequiringAction(companyId: string): Promise<({
        user: {
            id: string;
            phone: string | null;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    })[]>;
    getContractsPendingQiwa(companyId: string): Promise<({
        user: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.ContractStatus;
        annualLeaveDays: number;
        type: import(".prisma/client").$Enums.ContractType;
        endDate: Date | null;
        startDate: Date;
        notes: string | null;
        userId: string;
        contractNumber: string | null;
        probationEndDate: Date | null;
        terminatedAt: Date | null;
        terminationReason: string | null;
        terminatedBy: string | null;
        renewalCount: number;
        previousContractId: string | null;
        salaryCycle: string;
        basicSalary: import("@prisma/client/runtime/library").Decimal | null;
        housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
        transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
        otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
        totalSalary: import("@prisma/client/runtime/library").Decimal | null;
        contractJobTitle: string | null;
        workLocation: string | null;
        workingHoursPerWeek: number;
        noticePeriodDays: number;
        employeeSignature: boolean;
        employeeSignedAt: Date | null;
        employerSignature: boolean;
        employerSignedAt: Date | null;
        signedByUserId: string | null;
        qiwaContractId: string | null;
        qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
        qiwaAuthDate: Date | null;
        qiwaRejectReason: string | null;
        qiwaLastSync: Date | null;
        documentUrl: string | null;
        additionalTerms: string | null;
    })[]>;
    private mapContractType;
    private mapContractStatus;
    private mapQiwaStatus;
}
