import { Strategy } from 'passport-jwt';
import { ConfigService } from '@nestjs/config';
import { PrismaService } from '../../../common/prisma/prisma.service';
export interface JwtPayload {
    sub: string;
    email: string;
    role: string;
    companyId: string;
    iat?: number;
    exp?: number;
}
declare const JwtStrategy_base: new (...args: any[]) => Strategy;
export declare class JwtStrategy extends JwtStrategy_base {
    private configService;
    private prisma;
    constructor(configService: ConfigService, prisma: PrismaService);
    validate(payload: JwtPayload): Promise<{
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        } | null;
        department: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            branchId: string;
            workStartTime: string | null;
            workEndTime: string | null;
        } | null;
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
}
export {};
