import { PrismaService } from '../../common/prisma/prisma.service';
import { NotificationsService } from '../notifications/notifications.service';
import { PermissionsService } from '../permissions/permissions.service';
import { SmartPolicyTriggerService } from "../smart-policies/smart-policy-trigger.service";
import { CreateCaseDto } from './dto/create-case.dto';
import { HRReviewDto } from './dto/hr-review.dto';
import { IssueDecisionDto } from './dto/issue-decision.dto';
import { EmployeeResponseDto } from './dto/employee-response.dto';
import { ObjectionReviewDto } from './dto/objection-review.dto';
export declare class DisciplinaryService {
    private prisma;
    private notificationsService;
    private permissionsService;
    private smartPolicyTrigger;
    private readonly logger;
    constructor(prisma: PrismaService, notificationsService: NotificationsService, permissionsService: PermissionsService, smartPolicyTrigger: SmartPolicyTriggerService);
    getPolicy(companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        companyId: string;
        incidentMaxAgeDays: number;
        decisionDeadlineDays: number;
        objectionWindowDays: number;
        allowRetrospectiveIncidents: boolean;
        autoApplyToOpenPayrollPeriod: boolean;
        deductionBasePolicy: import(".prisma/client").$Enums.DeductionBasePolicy;
    } | {
        incidentMaxAgeDays: number;
        decisionDeadlineDays: number;
        objectionWindowDays: number;
        allowRetrospectiveIncidents: boolean;
        autoApplyToOpenPayrollPeriod: boolean;
        deductionBasePolicy: "BASIC_FIXED";
    }>;
    createCase(managerId: string, companyId: string, dto: CreateCaseDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    }>;
    hrInitialReview(caseId: string, hrId: string, companyId: string, dto: HRReviewDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    }>;
    employeeInformalResponse(caseId: string, employeeId: string, companyId: string, dto: EmployeeResponseDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    } | null>;
    issueDecision(caseId: string, hrId: string, companyId: string, dto: IssueDecisionDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    }>;
    toggleLegalHold(caseId: string, hrId: string, companyId: string, hold: boolean): Promise<{
        success: boolean;
        legalHold: boolean;
    }>;
    objectionReview(caseId: string, hrId: string, companyId: string, dto: ObjectionReviewDto): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    }>;
    finalizeCase(caseId: string, actorId: string, companyId: string): Promise<any>;
    private findCaseOrThrow;
    private logEvent;
    scheduleHearing(caseId: string, hrId: string, companyId: string, dto: {
        hearingDatetime: string;
        hearingLocation: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    }>;
    uploadMinutes(caseId: string, hrId: string, companyId: string, dto: {
        sessionNo: number;
        minutesText?: string;
        minutesFileUrl?: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        caseId: string;
        sessionNo: number;
        minutesText: string | null;
        minutesFileUrl: string | null;
        createdByHrId: string;
    }>;
    employeeDecisionResponse(caseId: string, employeeId: string, companyId: string, dto: {
        action: 'ACCEPT' | 'OBJECT';
        objectionText?: string;
    }): Promise<any>;
    getCasesForRole(userId: string, companyId: string, role: 'manager' | 'hr' | 'employee'): Promise<({
        manager: {
            id: string;
            firstName: string;
            lastName: string;
        };
        employee: {
            id: string;
            firstName: string;
            lastName: string;
        };
        events: {
            id: string;
            createdAt: Date;
            message: string | null;
            caseId: string;
            actorUserId: string | null;
            eventType: import(".prisma/client").$Enums.CaseEventType;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    })[]>;
    getCaseDetail(caseId: string, companyId: string): Promise<{
        deadlines: {
            decision: {
                date: Date;
                daysRemaining: number;
                isExpired: boolean;
            } | null;
            objection: {
                date: Date;
                daysRemaining: number;
                isExpired: boolean;
            } | null;
        };
        manager: {
            id: string;
            firstName: string;
            lastName: string;
        };
        payrollPeriod: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            endDate: Date;
            month: number;
            year: number;
            startDate: Date;
            cutOffDate: Date | null;
            inputsLockedAt: Date | null;
            lockedAt: Date | null;
            lockedBy: string | null;
        } | null;
        employee: {
            id: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
        attachments: {
            id: string;
            createdAt: Date;
            caseId: string;
            fileType: string;
            fileName: string;
            fileUrl: string;
            uploaderUserId: string;
        }[];
        minutes: {
            id: string;
            createdAt: Date;
            caseId: string;
            sessionNo: number;
            minutesText: string | null;
            minutesFileUrl: string | null;
            createdByHrId: string;
        }[];
        events: {
            id: string;
            createdAt: Date;
            message: string | null;
            caseId: string;
            actorUserId: string | null;
            eventType: import(".prisma/client").$Enums.CaseEventType;
            metadata: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
        records: {
            id: string;
            createdAt: Date;
            effectiveDate: Date;
            employeeId: string;
            reason: string | null;
            decisionType: import(".prisma/client").$Enums.DecisionType;
            caseId: string;
            penaltyMetadata: import("@prisma/client/runtime/library").JsonValue | null;
        }[];
        adjustments: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollAdjustmentStatus;
            companyId: string;
            description: string | null;
            effectiveDate: Date | null;
            employeeId: string;
            amount: import("@prisma/client/runtime/library").Decimal | null;
            value: import("@prisma/client/runtime/library").Decimal;
            payrollPeriodId: string;
            caseId: string;
            adjustmentType: string;
            unit: import(".prisma/client").$Enums.AdjustmentUnit;
            postedAt: Date | null;
            reversedAt: Date | null;
        }[];
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.DisciplinaryStatus;
        companyId: string;
        managerId: string;
        description: string;
        employeeId: string;
        title: string;
        caseCode: string;
        violationType: string | null;
        incidentDate: Date;
        incidentLocation: string;
        involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
        stage: import(".prisma/client").$Enums.DisciplinaryStage;
        incidentMaxAgeDaysSnapshot: number;
        decisionDeadlineDaysSnapshot: number;
        objectionWindowDaysSnapshot: number;
        allowRetrospectiveSnapshot: boolean;
        deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
        isRetrospective: boolean;
        retrospectiveReason: string | null;
        hrInitialAction: string | null;
        hrInitialReason: string | null;
        officialInvestigationOpenedAt: Date | null;
        hearingDatetime: Date | null;
        hearingLocation: string | null;
        decisionType: import(".prisma/client").$Enums.DecisionType | null;
        decisionReason: string | null;
        decisionCreatedAt: Date | null;
        penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
        penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
        penaltyEffectiveDate: Date | null;
        payrollPeriodId: string | null;
        employeeAckStatus: string | null;
        employeeAckAt: Date | null;
        objectionText: string | null;
        objectionSubmittedAt: Date | null;
        hrAfterObjectionAction: string | null;
        hrAfterObjectionReason: string | null;
        finalizedAt: Date | null;
        legalHold: boolean;
    }>;
    uploadAttachment(caseId: string, userId: string, companyId: string, dto: {
        fileUrl: string;
        fileName: string;
        fileType: string;
    }): Promise<{
        id: string;
        createdAt: Date;
        caseId: string;
        fileType: string;
        fileName: string;
        fileUrl: string;
        uploaderUserId: string;
    }>;
    uploadFiles(caseId: string, userId: string, companyId: string, files: Express.Multer.File[]): Promise<{
        message: string;
        attachments: {
            id: string;
            createdAt: Date;
            caseId: string;
            fileType: string;
            fileName: string;
            fileUrl: string;
            uploaderUserId: string;
        }[];
    }>;
}
