import { PrismaService } from '../../common/prisma/prisma.service';
import { PolicyContextService } from './policy-context.service';
import { SmartPolicyExecutorService } from './smart-policy-executor.service';
import { RetroApplicationStatus } from '@prisma/client';
export interface CreateRetroApplicationDto {
    policyId: string;
    startPeriod: string;
    endPeriod: string;
    notes?: string;
}
export interface EmployeeRetroResult {
    employeeId: string;
    employeeName: string;
    periods: {
        period: string;
        amount: number;
        type: 'ADDITION' | 'DEDUCTION';
        details: any;
    }[];
    totalAmount: number;
    netType: 'ADDITION' | 'DEDUCTION' | 'NEUTRAL';
}
export declare class RetroactivePolicyService {
    private readonly prisma;
    private readonly policyContext;
    private readonly policyExecutor;
    private readonly logger;
    constructor(prisma: PrismaService, policyContext: PolicyContextService, policyExecutor: SmartPolicyExecutorService);
    createApplication(companyId: string, dto: CreateRetroApplicationDto, requestedBy: string, requestedByName: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroApplicationStatus;
        companyId: string;
        totalDeductions: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        approvedAt: Date | null;
        policyId: string;
        approvedBy: string | null;
        reviewedAt: Date | null;
        reviewedBy: string | null;
        appliedAt: Date | null;
        results: import("@prisma/client/runtime/library").JsonValue;
        totalEmployeesAffected: number;
        totalAdditions: import("@prisma/client/runtime/library").Decimal;
        startPeriod: string;
        endPeriod: string;
        periods: string[];
        netAmount: import("@prisma/client/runtime/library").Decimal;
        requestedBy: string;
        requestedByName: string;
        requestedAt: Date;
        reviewedByName: string | null;
        approvedByName: string | null;
        appliedToPayrollPeriod: string | null;
    }>;
    calculate(applicationId: string): Promise<{
        summary: {
            totalEmployees: number;
            totalAdditions: number;
            totalDeductions: number;
            netAmount: number;
        };
        results: EmployeeRetroResult[];
    }>;
    approve(applicationId: string, approvedBy: string, approvedByName: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroApplicationStatus;
        companyId: string;
        totalDeductions: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        approvedAt: Date | null;
        policyId: string;
        approvedBy: string | null;
        reviewedAt: Date | null;
        reviewedBy: string | null;
        appliedAt: Date | null;
        results: import("@prisma/client/runtime/library").JsonValue;
        totalEmployeesAffected: number;
        totalAdditions: import("@prisma/client/runtime/library").Decimal;
        startPeriod: string;
        endPeriod: string;
        periods: string[];
        netAmount: import("@prisma/client/runtime/library").Decimal;
        requestedBy: string;
        requestedByName: string;
        requestedAt: Date;
        reviewedByName: string | null;
        approvedByName: string | null;
        appliedToPayrollPeriod: string | null;
    }>;
    apply(applicationId: string, targetPayrollPeriod: string): Promise<{
        retroPayRecords: number;
        totalAmount: number;
    }>;
    cancel(applicationId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroApplicationStatus;
        companyId: string;
        totalDeductions: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        approvedAt: Date | null;
        policyId: string;
        approvedBy: string | null;
        reviewedAt: Date | null;
        reviewedBy: string | null;
        appliedAt: Date | null;
        results: import("@prisma/client/runtime/library").JsonValue;
        totalEmployeesAffected: number;
        totalAdditions: import("@prisma/client/runtime/library").Decimal;
        startPeriod: string;
        endPeriod: string;
        periods: string[];
        netAmount: import("@prisma/client/runtime/library").Decimal;
        requestedBy: string;
        requestedByName: string;
        requestedAt: Date;
        reviewedByName: string | null;
        approvedByName: string | null;
        appliedToPayrollPeriod: string | null;
    }>;
    findByPolicy(policyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroApplicationStatus;
        companyId: string;
        totalDeductions: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        approvedAt: Date | null;
        policyId: string;
        approvedBy: string | null;
        reviewedAt: Date | null;
        reviewedBy: string | null;
        appliedAt: Date | null;
        results: import("@prisma/client/runtime/library").JsonValue;
        totalEmployeesAffected: number;
        totalAdditions: import("@prisma/client/runtime/library").Decimal;
        startPeriod: string;
        endPeriod: string;
        periods: string[];
        netAmount: import("@prisma/client/runtime/library").Decimal;
        requestedBy: string;
        requestedByName: string;
        requestedAt: Date;
        reviewedByName: string | null;
        approvedByName: string | null;
        appliedToPayrollPeriod: string | null;
    }[]>;
    findByCompany(companyId: string, options?: {
        status?: RetroApplicationStatus;
    }): Promise<({
        policy: {
            id: string;
            name: string | null;
            originalText: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroApplicationStatus;
        companyId: string;
        totalDeductions: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        approvedAt: Date | null;
        policyId: string;
        approvedBy: string | null;
        reviewedAt: Date | null;
        reviewedBy: string | null;
        appliedAt: Date | null;
        results: import("@prisma/client/runtime/library").JsonValue;
        totalEmployeesAffected: number;
        totalAdditions: import("@prisma/client/runtime/library").Decimal;
        startPeriod: string;
        endPeriod: string;
        periods: string[];
        netAmount: import("@prisma/client/runtime/library").Decimal;
        requestedBy: string;
        requestedByName: string;
        requestedAt: Date;
        reviewedByName: string | null;
        approvedByName: string | null;
        appliedToPayrollPeriod: string | null;
    })[]>;
    findOne(applicationId: string): Promise<{
        policy: {
            id: string;
            name: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.SmartPolicyStatus;
            companyId: string;
            description: string | null;
            isActive: boolean;
            priority: number;
            effectiveFrom: Date | null;
            effectiveTo: Date | null;
            createdById: string | null;
            requiresApproval: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            approvedAt: Date | null;
            approvedById: string | null;
            originalText: string;
            triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
            triggerSubEvent: string | null;
            parsedRule: import("@prisma/client/runtime/library").JsonValue;
            actions: import("@prisma/client/runtime/library").JsonValue;
            conditionLogic: string;
            lookbackMonths: number | null;
            scopeType: string;
            scopeId: string | null;
            scopeName: string | null;
            aiExplanation: string | null;
            clarificationNeeded: string | null;
            executionCount: number;
            lastExecutedAt: Date | null;
            totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
            totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
            currentVersion: number;
            executionOrder: number;
            executionGroup: string | null;
            dependsOnPolicies: string[];
            blockLowerPriority: boolean;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RetroApplicationStatus;
        companyId: string;
        totalDeductions: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        approvedAt: Date | null;
        policyId: string;
        approvedBy: string | null;
        reviewedAt: Date | null;
        reviewedBy: string | null;
        appliedAt: Date | null;
        results: import("@prisma/client/runtime/library").JsonValue;
        totalEmployeesAffected: number;
        totalAdditions: import("@prisma/client/runtime/library").Decimal;
        startPeriod: string;
        endPeriod: string;
        periods: string[];
        netAmount: import("@prisma/client/runtime/library").Decimal;
        requestedBy: string;
        requestedByName: string;
        requestedAt: Date;
        reviewedByName: string | null;
        approvedByName: string | null;
        appliedToPayrollPeriod: string | null;
    }>;
    private generatePeriods;
}
