import { PrismaService } from '../../common/prisma/prisma.service';
import { PolicyParserService, ParsedPolicyRule } from '../ai/services/policy-parser.service';
import { PolicyContextService } from './policy-context.service';
import { SmartPolicyTrigger, SmartPolicyStatus } from '@prisma/client';
export interface CreateSmartPolicyDto {
    originalText: string;
    name?: string;
    effectiveFrom?: Date;
    effectiveTo?: Date;
}
export interface UpdateSmartPolicyDto {
    name?: string;
    status?: SmartPolicyStatus;
    isActive?: boolean;
    priority?: number;
    effectiveFrom?: Date;
    effectiveTo?: Date;
}
export declare class SmartPoliciesService {
    private readonly prisma;
    private readonly policyParser;
    private readonly policyContext;
    private readonly logger;
    constructor(prisma: PrismaService, policyParser: PolicyParserService, policyContext: PolicyContextService);
    analyzePolicy(originalText: string): Promise<ParsedPolicyRule>;
    create(companyId: string, dto: CreateSmartPolicyDto, createdById?: string): Promise<{
        id: string;
        name: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.SmartPolicyStatus;
        companyId: string;
        description: string | null;
        isActive: boolean;
        priority: number;
        effectiveFrom: Date | null;
        effectiveTo: Date | null;
        createdById: string | null;
        requiresApproval: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        approvedAt: Date | null;
        approvedById: string | null;
        originalText: string;
        triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
        triggerSubEvent: string | null;
        parsedRule: import("@prisma/client/runtime/library").JsonValue;
        actions: import("@prisma/client/runtime/library").JsonValue;
        conditionLogic: string;
        lookbackMonths: number | null;
        scopeType: string;
        scopeId: string | null;
        scopeName: string | null;
        aiExplanation: string | null;
        clarificationNeeded: string | null;
        executionCount: number;
        lastExecutedAt: Date | null;
        totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
        totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
        currentVersion: number;
        executionOrder: number;
        executionGroup: string | null;
        dependsOnPolicies: string[];
        blockLowerPriority: boolean;
    }>;
    createAndActivate(companyId: string, originalText: string, createdById?: string): Promise<{
        created: boolean;
        policies: {
            id: string;
            name: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.SmartPolicyStatus;
            companyId: string;
            description: string | null;
            isActive: boolean;
            priority: number;
            effectiveFrom: Date | null;
            effectiveTo: Date | null;
            createdById: string | null;
            requiresApproval: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            approvedAt: Date | null;
            approvedById: string | null;
            originalText: string;
            triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
            triggerSubEvent: string | null;
            parsedRule: import("@prisma/client/runtime/library").JsonValue;
            actions: import("@prisma/client/runtime/library").JsonValue;
            conditionLogic: string;
            lookbackMonths: number | null;
            scopeType: string;
            scopeId: string | null;
            scopeName: string | null;
            aiExplanation: string | null;
            clarificationNeeded: string | null;
            executionCount: number;
            lastExecutedAt: Date | null;
            totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
            totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
            currentVersion: number;
            executionOrder: number;
            executionGroup: string | null;
            dependsOnPolicies: string[];
            blockLowerPriority: boolean;
        }[];
        message: string;
        count?: undefined;
        warning?: undefined;
        missingFields?: undefined;
        availableFields?: undefined;
        parsedRule?: undefined;
    } | {
        created: boolean;
        policies: {
            id: string;
            name: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.SmartPolicyStatus;
            companyId: string;
            description: string | null;
            isActive: boolean;
            priority: number;
            effectiveFrom: Date | null;
            effectiveTo: Date | null;
            createdById: string | null;
            requiresApproval: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            approvedAt: Date | null;
            approvedById: string | null;
            originalText: string;
            triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
            triggerSubEvent: string | null;
            parsedRule: import("@prisma/client/runtime/library").JsonValue;
            actions: import("@prisma/client/runtime/library").JsonValue;
            conditionLogic: string;
            lookbackMonths: number | null;
            scopeType: string;
            scopeId: string | null;
            scopeName: string | null;
            aiExplanation: string | null;
            clarificationNeeded: string | null;
            executionCount: number;
            lastExecutedAt: Date | null;
            totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
            totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
            currentVersion: number;
            executionOrder: number;
            executionGroup: string | null;
            dependsOnPolicies: string[];
            blockLowerPriority: boolean;
        }[];
        count: number;
        message: string;
        warning: string | undefined;
        missingFields: string[] | undefined;
        availableFields: string[];
        parsedRule: ParsedPolicyRule;
    }>;
    private detectAndSplitTieredPolicy;
    private findSimilarPolicy;
    findAll(companyId: string, options?: {
        status?: SmartPolicyStatus;
        triggerEvent?: SmartPolicyTrigger;
        isActive?: boolean;
        page?: number;
        limit?: number;
    }): Promise<{
        data: {
            id: string;
            name: string | null;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.SmartPolicyStatus;
            companyId: string;
            description: string | null;
            isActive: boolean;
            priority: number;
            effectiveFrom: Date | null;
            effectiveTo: Date | null;
            createdById: string | null;
            requiresApproval: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            approvedAt: Date | null;
            approvedById: string | null;
            originalText: string;
            triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
            triggerSubEvent: string | null;
            parsedRule: import("@prisma/client/runtime/library").JsonValue;
            actions: import("@prisma/client/runtime/library").JsonValue;
            conditionLogic: string;
            lookbackMonths: number | null;
            scopeType: string;
            scopeId: string | null;
            scopeName: string | null;
            aiExplanation: string | null;
            clarificationNeeded: string | null;
            executionCount: number;
            lastExecutedAt: Date | null;
            totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
            totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
            currentVersion: number;
            executionOrder: number;
            executionGroup: string | null;
            dependsOnPolicies: string[];
            blockLowerPriority: boolean;
        }[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    findOne(id: string): Promise<{
        executions: {
            id: string;
            payrollPeriod: string | null;
            employeeId: string;
            triggerEvent: string;
            triggerSubEvent: string | null;
            employeeName: string;
            triggerData: import("@prisma/client/runtime/library").JsonValue | null;
            conditionsMet: boolean;
            conditionsLog: import("@prisma/client/runtime/library").JsonValue | null;
            actionType: string | null;
            actionValue: import("@prisma/client/runtime/library").Decimal | null;
            actionResult: import("@prisma/client/runtime/library").JsonValue | null;
            isSuccess: boolean;
            errorMessage: string | null;
            executedAt: Date;
            policyId: string;
        }[];
    } & {
        id: string;
        name: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.SmartPolicyStatus;
        companyId: string;
        description: string | null;
        isActive: boolean;
        priority: number;
        effectiveFrom: Date | null;
        effectiveTo: Date | null;
        createdById: string | null;
        requiresApproval: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        approvedAt: Date | null;
        approvedById: string | null;
        originalText: string;
        triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
        triggerSubEvent: string | null;
        parsedRule: import("@prisma/client/runtime/library").JsonValue;
        actions: import("@prisma/client/runtime/library").JsonValue;
        conditionLogic: string;
        lookbackMonths: number | null;
        scopeType: string;
        scopeId: string | null;
        scopeName: string | null;
        aiExplanation: string | null;
        clarificationNeeded: string | null;
        executionCount: number;
        lastExecutedAt: Date | null;
        totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
        totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
        currentVersion: number;
        executionOrder: number;
        executionGroup: string | null;
        dependsOnPolicies: string[];
        blockLowerPriority: boolean;
    }>;
    update(id: string, dto: UpdateSmartPolicyDto, approvedById?: string): Promise<{
        id: string;
        name: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.SmartPolicyStatus;
        companyId: string;
        description: string | null;
        isActive: boolean;
        priority: number;
        effectiveFrom: Date | null;
        effectiveTo: Date | null;
        createdById: string | null;
        requiresApproval: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        approvedAt: Date | null;
        approvedById: string | null;
        originalText: string;
        triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
        triggerSubEvent: string | null;
        parsedRule: import("@prisma/client/runtime/library").JsonValue;
        actions: import("@prisma/client/runtime/library").JsonValue;
        conditionLogic: string;
        lookbackMonths: number | null;
        scopeType: string;
        scopeId: string | null;
        scopeName: string | null;
        aiExplanation: string | null;
        clarificationNeeded: string | null;
        executionCount: number;
        lastExecutedAt: Date | null;
        totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
        totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
        currentVersion: number;
        executionOrder: number;
        executionGroup: string | null;
        dependsOnPolicies: string[];
        blockLowerPriority: boolean;
    }>;
    delete(id: string): Promise<{
        id: string;
        name: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.SmartPolicyStatus;
        companyId: string;
        description: string | null;
        isActive: boolean;
        priority: number;
        effectiveFrom: Date | null;
        effectiveTo: Date | null;
        createdById: string | null;
        requiresApproval: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        approvedAt: Date | null;
        approvedById: string | null;
        originalText: string;
        triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
        triggerSubEvent: string | null;
        parsedRule: import("@prisma/client/runtime/library").JsonValue;
        actions: import("@prisma/client/runtime/library").JsonValue;
        conditionLogic: string;
        lookbackMonths: number | null;
        scopeType: string;
        scopeId: string | null;
        scopeName: string | null;
        aiExplanation: string | null;
        clarificationNeeded: string | null;
        executionCount: number;
        lastExecutedAt: Date | null;
        totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
        totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
        currentVersion: number;
        executionOrder: number;
        executionGroup: string | null;
        dependsOnPolicies: string[];
        blockLowerPriority: boolean;
    }>;
    toggleActive(id: string, isActive: boolean, userId?: string): Promise<{
        id: string;
        name: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.SmartPolicyStatus;
        companyId: string;
        description: string | null;
        isActive: boolean;
        priority: number;
        effectiveFrom: Date | null;
        effectiveTo: Date | null;
        createdById: string | null;
        requiresApproval: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        approvedAt: Date | null;
        approvedById: string | null;
        originalText: string;
        triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
        triggerSubEvent: string | null;
        parsedRule: import("@prisma/client/runtime/library").JsonValue;
        actions: import("@prisma/client/runtime/library").JsonValue;
        conditionLogic: string;
        lookbackMonths: number | null;
        scopeType: string;
        scopeId: string | null;
        scopeName: string | null;
        aiExplanation: string | null;
        clarificationNeeded: string | null;
        executionCount: number;
        lastExecutedAt: Date | null;
        totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
        totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
        currentVersion: number;
        executionOrder: number;
        executionGroup: string | null;
        dependsOnPolicies: string[];
        blockLowerPriority: boolean;
    }>;
    getActivePoliciesForEvent(companyId: string, triggerEvent: SmartPolicyTrigger, subEvent?: string): Promise<{
        id: string;
        name: string | null;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.SmartPolicyStatus;
        companyId: string;
        description: string | null;
        isActive: boolean;
        priority: number;
        effectiveFrom: Date | null;
        effectiveTo: Date | null;
        createdById: string | null;
        requiresApproval: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        approvedAt: Date | null;
        approvedById: string | null;
        originalText: string;
        triggerEvent: import(".prisma/client").$Enums.SmartPolicyTrigger;
        triggerSubEvent: string | null;
        parsedRule: import("@prisma/client/runtime/library").JsonValue;
        actions: import("@prisma/client/runtime/library").JsonValue;
        conditionLogic: string;
        lookbackMonths: number | null;
        scopeType: string;
        scopeId: string | null;
        scopeName: string | null;
        aiExplanation: string | null;
        clarificationNeeded: string | null;
        executionCount: number;
        lastExecutedAt: Date | null;
        totalAmountPaid: import("@prisma/client/runtime/library").Decimal;
        totalAmountDeduct: import("@prisma/client/runtime/library").Decimal;
        currentVersion: number;
        executionOrder: number;
        executionGroup: string | null;
        dependsOnPolicies: string[];
        blockLowerPriority: boolean;
    }[]>;
    logExecution(data: {
        policyId: string;
        employeeId: string;
        employeeName: string;
        triggerEvent: string;
        triggerSubEvent?: string;
        triggerData?: any;
        conditionsMet: boolean;
        conditionsLog?: any;
        actionType?: string;
        actionValue?: number;
        actionResult?: any;
        isSuccess: boolean;
        errorMessage?: string;
        payrollPeriod?: string;
    }): Promise<{
        id: string;
        payrollPeriod: string | null;
        employeeId: string;
        triggerEvent: string;
        triggerSubEvent: string | null;
        employeeName: string;
        triggerData: import("@prisma/client/runtime/library").JsonValue | null;
        conditionsMet: boolean;
        conditionsLog: import("@prisma/client/runtime/library").JsonValue | null;
        actionType: string | null;
        actionValue: import("@prisma/client/runtime/library").Decimal | null;
        actionResult: import("@prisma/client/runtime/library").JsonValue | null;
        isSuccess: boolean;
        errorMessage: string | null;
        executedAt: Date;
        policyId: string;
    }>;
    private mapTriggerEvent;
}
