import { PrismaService } from '../../common/prisma/prisma.service';
import { CreatePayrollRunDto } from './dto/create-payroll-run.dto';
import { Decimal } from '@prisma/client/runtime/library';
import { PayrollCalculationService } from '../payroll-calculation/payroll-calculation.service';
import { PayrollLedgerService } from '../payroll-calculation/payroll-ledger.service';
import { AuditService } from '../audit/audit.service';
export declare class PayrollRunsService {
    private prisma;
    private calculationService;
    private auditService;
    private ledgerService;
    constructor(prisma: PrismaService, calculationService: PayrollCalculationService, auditService: AuditService, ledgerService: PayrollLedgerService);
    create(dto: CreatePayrollRunDto, companyId: string, userId: string): Promise<{
        payslipsCount: number;
        payslips?: {
            id: string;
        }[] | undefined;
        period?: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            endDate: Date;
            month: number;
            year: number;
            startDate: Date;
            cutOffDate: Date | null;
            inputsLockedAt: Date | null;
            lockedAt: Date | null;
            lockedBy: string | null;
        } | undefined;
        id?: string | undefined;
        createdAt?: Date | undefined;
        updatedAt?: Date | undefined;
        status?: import(".prisma/client").$Enums.PayrollStatus | undefined;
        companyId?: string | null | undefined;
        lockedAt?: Date | null | undefined;
        lockedBy?: string | null | undefined;
        periodId?: string | undefined;
        runDate?: Date | undefined;
        processedBy?: string | null | undefined;
        isAdjustment?: boolean | undefined;
        originalRunId?: string | null | undefined;
        adjustmentReason?: string | null | undefined;
        calculatedAt?: Date | null | undefined;
        calculatedBy?: string | null | undefined;
        hrApprovedAt?: Date | null | undefined;
        hrApprovedBy?: string | null | undefined;
        financeApprovedAt?: Date | null | undefined;
        financeApprovedBy?: string | null | undefined;
        paidAt?: Date | null | undefined;
    }>;
    preview(dto: CreatePayrollRunDto, companyId: string): Promise<{
        period: {
            id: string;
            month: number;
            year: number;
            name: string;
        };
        summary: {
            totalEmployees: number;
            totalBaseSalary: number;
            totalGross: number;
            totalDeductions: number;
            totalNet: number;
            totalGosi: number;
            totalAdvances: number;
        };
        comparison: {
            previousMonth: {
                headcount: number;
                gross: number;
                net: number;
                deductions: number;
            };
            grossChange: number;
            grossChangePercent: number;
            netChange: number;
            netChangePercent: number;
            headcountChange: number;
        } | null;
        byBranch: {
            count: number;
            gross: number;
            net: number;
            name: string;
        }[];
        byDepartment: {
            count: number;
            gross: number;
            net: number;
            name: string;
        }[];
        employees: any[];
        gosiEnabled: boolean;
    }>;
    findAll(companyId: string): Promise<({
        _count: {
            payslips: number;
        };
        period: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            endDate: Date;
            month: number;
            year: number;
            startDate: Date;
            cutOffDate: Date | null;
            inputsLockedAt: Date | null;
            lockedAt: Date | null;
            lockedBy: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PayrollStatus;
        companyId: string | null;
        lockedAt: Date | null;
        lockedBy: string | null;
        periodId: string;
        runDate: Date;
        processedBy: string | null;
        isAdjustment: boolean;
        originalRunId: string | null;
        adjustmentReason: string | null;
        calculatedAt: Date | null;
        calculatedBy: string | null;
        hrApprovedAt: Date | null;
        hrApprovedBy: string | null;
        financeApprovedAt: Date | null;
        financeApprovedBy: string | null;
        paidAt: Date | null;
    })[]>;
    findOne(id: string, companyId: string): Promise<({
        payslips: ({
            employee: {
                id: string;
                phone: string | null;
                email: string;
                createdAt: Date;
                updatedAt: Date;
                password: string;
                firstName: string;
                lastName: string;
                avatar: string | null;
                employeeCode: string | null;
                jobTitle: string | null;
                role: import(".prisma/client").$Enums.Role;
                status: import(".prisma/client").$Enums.UserStatus;
                salary: Decimal | null;
                hireDate: Date | null;
                nationality: string | null;
                isSaudi: boolean;
                fcmToken: string | null;
                nationalId: string | null;
                iqamaNumber: string | null;
                iqamaExpiryDate: Date | null;
                borderNumber: string | null;
                passportNumber: string | null;
                passportExpiryDate: Date | null;
                professionCode: string | null;
                profession: string | null;
                dateOfBirth: Date | null;
                gender: string | null;
                gosiNumber: string | null;
                maritalStatus: string | null;
                isSuperAdmin: boolean;
                jobTitleId: string | null;
                annualLeaveDays: number;
                usedLeaveDays: number;
                remainingLeaveDays: number;
                faceRegistered: boolean;
                companyId: string | null;
                branchId: string | null;
                departmentId: string | null;
                managerId: string | null;
                costCenterId: string | null;
                jobFamilyId: string | null;
                roleLevelId: string | null;
            };
            lines: ({
                component: {
                    id: string;
                    nameEn: string | null;
                    createdAt: Date;
                    updatedAt: Date;
                    companyId: string | null;
                    code: string;
                    nameAr: string;
                    type: import(".prisma/client").$Enums.SalaryComponentType;
                    nature: import(".prisma/client").$Enums.SalaryComponentNature;
                    description: string | null;
                    gosiEligible: boolean;
                    otEligible: boolean;
                    eosEligible: boolean;
                    isProrated: boolean;
                    taxable: boolean;
                    formula: string | null;
                    version: number;
                    effectiveDate: Date;
                    endDate: Date | null;
                    isActive: boolean;
                    roundingMode: string;
                    decimals: number;
                    priority: number;
                };
            } & {
                id: string;
                createdAt: Date;
                costCenterId: string | null;
                sign: string;
                amount: Decimal;
                sourceType: import(".prisma/client").$Enums.PayslipLineSource;
                sourceRef: string | null;
                descriptionAr: string | null;
                units: Decimal | null;
                rate: Decimal | null;
                componentId: string;
                payslipId: string;
            })[];
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            periodId: string;
            baseSalary: Decimal;
            grossSalary: Decimal;
            totalDeductions: Decimal;
            netSalary: Decimal;
            calculationTrace: import("@prisma/client/runtime/library").JsonValue | null;
            employeeId: string;
            runId: string | null;
        })[];
        period: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            endDate: Date;
            month: number;
            year: number;
            startDate: Date;
            cutOffDate: Date | null;
            inputsLockedAt: Date | null;
            lockedAt: Date | null;
            lockedBy: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PayrollStatus;
        companyId: string | null;
        lockedAt: Date | null;
        lockedBy: string | null;
        periodId: string;
        runDate: Date;
        processedBy: string | null;
        isAdjustment: boolean;
        originalRunId: string | null;
        adjustmentReason: string | null;
        calculatedAt: Date | null;
        calculatedBy: string | null;
        hrApprovedAt: Date | null;
        hrApprovedBy: string | null;
        financeApprovedAt: Date | null;
        financeApprovedBy: string | null;
        paidAt: Date | null;
    }) | null>;
    approve(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PayrollStatus;
        companyId: string | null;
        lockedAt: Date | null;
        lockedBy: string | null;
        periodId: string;
        runDate: Date;
        processedBy: string | null;
        isAdjustment: boolean;
        originalRunId: string | null;
        adjustmentReason: string | null;
        calculatedAt: Date | null;
        calculatedBy: string | null;
        hrApprovedAt: Date | null;
        hrApprovedBy: string | null;
        financeApprovedAt: Date | null;
        financeApprovedBy: string | null;
        paidAt: Date | null;
    }>;
    pay(id: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PayrollStatus;
        companyId: string | null;
        lockedAt: Date | null;
        lockedBy: string | null;
        periodId: string;
        runDate: Date;
        processedBy: string | null;
        isAdjustment: boolean;
        originalRunId: string | null;
        adjustmentReason: string | null;
        calculatedAt: Date | null;
        calculatedBy: string | null;
        hrApprovedAt: Date | null;
        hrApprovedBy: string | null;
        financeApprovedAt: Date | null;
        financeApprovedBy: string | null;
        paidAt: Date | null;
    }>;
}
