import { Response } from 'express';
import { ReportsService } from './reports.service';
import { ReportQueryDto } from './dto/report-query.dto';
export declare class ReportsController {
    private readonly reportsService;
    constructor(reportsService: ReportsService);
    getDashboardStats(req: any): Promise<{
        employees: {
            total: number;
            active: number;
        };
        today: {
            present: number;
            late: number;
            earlyLeave: number;
            absent: number;
            workFromHome: number;
        };
        pendingLeaves: number;
        pendingLetters: number;
        pendingRaises: number;
        pendingAdvances: number;
        pendingDataUpdates: number;
        compliance: {
            missingFace: number;
            suspiciousToday: number;
        };
        financials: {
            employerGosiTotal: number;
            eosSettlementTotal: number;
            ledgerDraftAmount: number;
            ledgerPostedAmount: number;
            periodName: string;
        };
        isEmployeeDashboard?: undefined;
        myAttendance?: undefined;
        myPendingLeaves?: undefined;
        myPendingLetters?: undefined;
        myPendingRaises?: undefined;
        myPendingAdvances?: undefined;
        myPendingDataUpdates?: undefined;
        myApprovedLeaves?: undefined;
        remainingLeaveDays?: undefined;
        annualLeaveDays?: undefined;
        usedLeaveDays?: undefined;
    } | {
        isEmployeeDashboard: boolean;
        myAttendance: {
            checkedIn: boolean;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            workingMinutes: number;
        } | null;
        myPendingLeaves: number;
        myPendingLetters: number;
        myPendingRaises: number;
        myPendingAdvances: number;
        myPendingDataUpdates: number;
        myApprovedLeaves: number;
        remainingLeaveDays: number;
        annualLeaveDays: number;
        usedLeaveDays: number;
        financials: {
            employerGosiTotal: number;
            eosSettlementTotal: number;
            ledgerDraftAmount: number;
            ledgerPostedAmount: number;
        };
        employees?: undefined;
        today?: undefined;
        pendingLeaves?: undefined;
        pendingLetters?: undefined;
        pendingRaises?: undefined;
        pendingAdvances?: undefined;
        pendingDataUpdates?: undefined;
        compliance?: undefined;
    }>;
    getWeeklySummary(req: any): Promise<{
        data: {
            date: string;
            present: number;
            late: number;
            absent: number;
        }[];
    }>;
    getAttendanceReport(req: any, query: ReportQueryDto): Promise<{
        data: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
                jobTitle: string | null;
                branch: {
                    name: string;
                } | null;
                department: {
                    name: string;
                } | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        })[];
        stats: {
            totalDays: number;
            presentDays: number;
            lateDays: number;
            earlyLeaveDays: number;
            absentDays: number;
            onLeaveDays: number;
            workFromHomeDays: number;
            totalWorkingMinutes: any;
            totalLateMinutes: any;
            totalOvertimeMinutes: any;
        };
        filters: {
            startDate: string | undefined;
            endDate: string | undefined;
            branchId: string | undefined;
            departmentId: string | undefined;
            userId: string | undefined;
        };
    }>;
    getEmployeeReport(req: any, userId: string, query: ReportQueryDto): Promise<{
        employee: ({
            branch: {
                id: string;
                name: string;
                nameEn: string | null;
                address: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                isActive: boolean;
                workStartTime: string;
                workEndTime: string;
                lateGracePeriod: number;
                geofenceRadius: number;
                latitude: import("@prisma/client/runtime/library").Decimal;
                longitude: import("@prisma/client/runtime/library").Decimal;
                timezone: string;
                earlyCheckInPeriod: number;
                earlyCheckOutPeriod: number;
                workingDays: string;
            } | null;
            department: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                branchId: string;
                workStartTime: string | null;
                workEndTime: string | null;
            } | null;
        } & {
            id: string;
            phone: string | null;
            email: string;
            createdAt: Date;
            updatedAt: Date;
            password: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            employeeCode: string | null;
            jobTitle: string | null;
            role: import(".prisma/client").$Enums.Role;
            status: import(".prisma/client").$Enums.UserStatus;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            nationality: string | null;
            isSaudi: boolean;
            fcmToken: string | null;
            nationalId: string | null;
            iqamaNumber: string | null;
            iqamaExpiryDate: Date | null;
            borderNumber: string | null;
            passportNumber: string | null;
            passportExpiryDate: Date | null;
            professionCode: string | null;
            profession: string | null;
            dateOfBirth: Date | null;
            gender: string | null;
            gosiNumber: string | null;
            maritalStatus: string | null;
            isSuperAdmin: boolean;
            jobTitleId: string | null;
            annualLeaveDays: number;
            usedLeaveDays: number;
            remainingLeaveDays: number;
            faceRegistered: boolean;
            companyId: string | null;
            branchId: string | null;
            departmentId: string | null;
            managerId: string | null;
            costCenterId: string | null;
            jobFamilyId: string | null;
            roleLevelId: string | null;
        }) | null;
        attendances: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        }[];
        leaves: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.LeaveStatus;
            companyId: string | null;
            type: import(".prisma/client").$Enums.LeaveType;
            endDate: Date;
            startDate: Date;
            notes: string | null;
            userId: string;
            requestedDays: number;
            approvedDays: number | null;
            reason: string;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            currentStep: import(".prisma/client").$Enums.ApprovalStep;
            managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
            managerDecisionAt: Date | null;
            managerNotes: string | null;
            managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
            hrDecisionAt: Date | null;
            hrDecisionNotes: string | null;
            hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
            approverNotes: string | null;
            approvedAt: Date | null;
            fullPayDays: number | null;
            partialPayDays: number | null;
            unpaidDays: number | null;
            salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
            noticeDaysProvided: number | null;
            managerApproverId: string | null;
            hrApproverId: string | null;
            approverId: string | null;
            leaveTypeConfigId: string | null;
        }[];
        stats: {
            totalDays: number;
            presentDays: number;
            lateDays: number;
            earlyLeaveDays: number;
            absentDays: number;
            onLeaveDays: number;
            workFromHomeDays: number;
            totalWorkingMinutes: any;
            totalLateMinutes: any;
            totalOvertimeMinutes: any;
        };
    }>;
    getBranchReport(branchId: string, query: ReportQueryDto): Promise<{
        branch: ({
            departments: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                branchId: string;
                workStartTime: string | null;
                workEndTime: string | null;
            }[];
        } & {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        }) | null;
        employeeCount: number;
        attendances: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        })[];
        stats: {
            totalDays: number;
            presentDays: number;
            lateDays: number;
            earlyLeaveDays: number;
            absentDays: number;
            onLeaveDays: number;
            workFromHomeDays: number;
            totalWorkingMinutes: any;
            totalLateMinutes: any;
            totalOvertimeMinutes: any;
        };
    }>;
    getLateReport(req: any, query: ReportQueryDto): Promise<{
        data: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
                department: {
                    name: string;
                } | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        })[];
        byEmployee: any[];
        totalLateMinutes: number;
        totalLateCount: number;
    }>;
    getPayrollSummary(req: any, query: ReportQueryDto): Promise<{
        employeeId: string;
        employeeCode: string | null;
        employeeName: string;
        baseSalary: import("@prisma/client/runtime/library").Decimal | null;
        workingDays: number;
        totalWorkingHours: number;
        totalLateMinutes: number;
        totalEarlyLeaveMinutes: number;
        totalOvertimeMinutes: number;
        absentDays: number;
        lateDeduction: number;
        absentDeduction: number;
        overtimeBonus: number;
    }[]>;
    exportToExcel(req: any, type: string, query: ReportQueryDto, res: Response): Promise<void>;
    exportToPdf(req: any, type: string, query: ReportQueryDto, res: Response): Promise<void>;
}
