import { EmployeeProfileService } from './employee-profile.service';
import { UpdateProfileDto, RequestOnBehalfDto, UploadDocumentDto, AttendanceQueryDto } from './dto/profile.dto';
export declare class EmployeeProfileController {
    private readonly profileService;
    constructor(profileService: EmployeeProfileService);
    getFullProfile(userId: string, user: any): Promise<{
        yearsOfService: number;
        password: undefined;
        disciplinaryCases: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.DisciplinaryStatus;
            companyId: string;
            managerId: string;
            description: string;
            employeeId: string;
            title: string;
            caseCode: string;
            violationType: string | null;
            incidentDate: Date;
            incidentLocation: string;
            involvedParties: import("@prisma/client/runtime/library").JsonValue | null;
            stage: import(".prisma/client").$Enums.DisciplinaryStage;
            incidentMaxAgeDaysSnapshot: number;
            decisionDeadlineDaysSnapshot: number;
            objectionWindowDaysSnapshot: number;
            allowRetrospectiveSnapshot: boolean;
            deductionBasePolicySnapshot: import(".prisma/client").$Enums.DeductionBasePolicy;
            isRetrospective: boolean;
            retrospectiveReason: string | null;
            hrInitialAction: string | null;
            hrInitialReason: string | null;
            officialInvestigationOpenedAt: Date | null;
            hearingDatetime: Date | null;
            hearingLocation: string | null;
            decisionType: import(".prisma/client").$Enums.DecisionType | null;
            decisionReason: string | null;
            decisionCreatedAt: Date | null;
            penaltyUnit: import(".prisma/client").$Enums.AdjustmentUnit | null;
            penaltyValue: import("@prisma/client/runtime/library").Decimal | null;
            penaltyEffectiveDate: Date | null;
            payrollPeriodId: string | null;
            employeeAckStatus: string | null;
            employeeAckAt: Date | null;
            objectionText: string | null;
            objectionSubmittedAt: Date | null;
            hrAfterObjectionAction: string | null;
            hrAfterObjectionReason: string | null;
            finalizedAt: Date | null;
            legalHold: boolean;
        }[];
        custodyAssignments: ({
            custodyItem: {
                category: {
                    id: string;
                    name: string;
                    nameEn: string | null;
                    createdAt: Date;
                    updatedAt: Date;
                    companyId: string;
                    description: string | null;
                    isActive: boolean;
                    requiresApproval: boolean;
                    icon: string | null;
                    requiresSerialNumber: boolean;
                    depreciationYears: number | null;
                };
            } & {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                status: import(".prisma/client").$Enums.CustodyItemStatus;
                companyId: string;
                branchId: string | null;
                code: string;
                description: string | null;
                notes: string | null;
                attachments: import("@prisma/client/runtime/library").JsonValue | null;
                model: string | null;
                vendor: string | null;
                invoiceNumber: string | null;
                categoryId: string;
                serialNumber: string | null;
                brand: string | null;
                barcode: string | null;
                qrCode: string | null;
                purchaseDate: Date | null;
                purchasePrice: import("@prisma/client/runtime/library").Decimal | null;
                warrantyExpiry: Date | null;
                condition: import(".prisma/client").$Enums.CustodyCondition;
                currentLocation: string | null;
                imageUrl: string | null;
                currentAssigneeId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.CustodyAssignmentStatus;
            companyId: string;
            employeeId: string;
            notes: string | null;
            attachments: import("@prisma/client/runtime/library").JsonValue | null;
            approvedAt: Date | null;
            approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
            approvedById: string | null;
            employeeSignature: string | null;
            custodyItemId: string;
            assignedAt: Date;
            expectedReturn: Date | null;
            actualReturn: Date | null;
            conditionOnAssign: import(".prisma/client").$Enums.CustodyCondition | null;
            conditionOnReturn: import(".prisma/client").$Enums.CustodyCondition | null;
            assignedById: string;
            signatureDate: Date | null;
        })[];
        jobTitleRef: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            level: import(".prisma/client").$Enums.Role;
            isDirectManager: boolean;
        } | null;
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
            address: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            isActive: boolean;
            workStartTime: string;
            workEndTime: string;
            lateGracePeriod: number;
            geofenceRadius: number;
            latitude: import("@prisma/client/runtime/library").Decimal;
            longitude: import("@prisma/client/runtime/library").Decimal;
            timezone: string;
            earlyCheckInPeriod: number;
            earlyCheckOutPeriod: number;
            workingDays: string;
        } | null;
        department: {
            id: string;
            name: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            branchId: string;
            workStartTime: string | null;
            workEndTime: string | null;
        } | null;
        manager: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
            jobTitle: string | null;
        } | null;
        bankAccounts: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            iban: string;
            accountHolderName: string | null;
            bankName: string;
            bankCode: string | null;
            swiftCode: string | null;
            isPrimary: boolean;
            isVerified: boolean;
            verifiedAt: Date | null;
            verifiedBy: string | null;
        }[];
        contracts: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.ContractStatus;
            annualLeaveDays: number;
            type: import(".prisma/client").$Enums.ContractType;
            endDate: Date | null;
            startDate: Date;
            notes: string | null;
            userId: string;
            contractNumber: string | null;
            probationEndDate: Date | null;
            terminatedAt: Date | null;
            terminationReason: string | null;
            terminatedBy: string | null;
            renewalCount: number;
            previousContractId: string | null;
            salaryCycle: string;
            basicSalary: import("@prisma/client/runtime/library").Decimal | null;
            housingAllowance: import("@prisma/client/runtime/library").Decimal | null;
            transportAllowance: import("@prisma/client/runtime/library").Decimal | null;
            otherAllowances: import("@prisma/client/runtime/library").Decimal | null;
            totalSalary: import("@prisma/client/runtime/library").Decimal | null;
            contractJobTitle: string | null;
            workLocation: string | null;
            workingHoursPerWeek: number;
            noticePeriodDays: number;
            employeeSignature: boolean;
            employeeSignedAt: Date | null;
            employerSignature: boolean;
            employerSignedAt: Date | null;
            signedByUserId: string | null;
            qiwaContractId: string | null;
            qiwaStatus: import(".prisma/client").$Enums.QiwaAuthStatus;
            qiwaAuthDate: Date | null;
            qiwaRejectReason: string | null;
            qiwaLastSync: Date | null;
            documentUrl: string | null;
            additionalTerms: string | null;
        }[];
        customFields: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            userId: string;
            fieldName: string;
            fieldValue: string;
            fieldType: string;
            sourceHeader: string | null;
            importedAt: Date;
        }[];
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    updateProfile(userId: string, dto: UpdateProfileDto, user: any): Promise<{
        id: string;
        phone: string | null;
        email: string;
        createdAt: Date;
        updatedAt: Date;
        password: string;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        salary: import("@prisma/client/runtime/library").Decimal | null;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        fcmToken: string | null;
        nationalId: string | null;
        iqamaNumber: string | null;
        iqamaExpiryDate: Date | null;
        borderNumber: string | null;
        passportNumber: string | null;
        passportExpiryDate: Date | null;
        professionCode: string | null;
        profession: string | null;
        dateOfBirth: Date | null;
        gender: string | null;
        gosiNumber: string | null;
        maritalStatus: string | null;
        isSuperAdmin: boolean;
        jobTitleId: string | null;
        annualLeaveDays: number;
        usedLeaveDays: number;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        managerId: string | null;
        costCenterId: string | null;
        jobFamilyId: string | null;
        roleLevelId: string | null;
    }>;
    getOverview(userId: string, user: any): Promise<{
        yearsOfService: number;
        id: string;
        phone: string | null;
        email: string;
        firstName: string;
        lastName: string;
        avatar: string | null;
        employeeCode: string | null;
        jobTitle: string | null;
        role: import(".prisma/client").$Enums.Role;
        status: import(".prisma/client").$Enums.UserStatus;
        hireDate: Date | null;
        nationality: string | null;
        isSaudi: boolean;
        remainingLeaveDays: number;
        faceRegistered: boolean;
        jobTitleRef: {
            id: string;
            name: string;
            nameEn: string | null;
            level: import(".prisma/client").$Enums.Role;
        } | null;
        branch: {
            id: string;
            name: string;
            nameEn: string | null;
        } | null;
        department: {
            id: string;
            name: string;
            nameEn: string | null;
        } | null;
        manager: {
            id: string;
            firstName: string;
            lastName: string;
            avatar: string | null;
        } | null;
    }>;
    getAttendanceStats(userId: string, query: AttendanceQueryDto, user: any): Promise<import("./dto/profile.dto").AttendanceStatsResponse>;
    getLeaveHistory(userId: string, user: any): Promise<import("./dto/profile.dto").LeaveBalanceResponse & {
        requests: any[];
    }>;
    getSalaryInfo(userId: string, user: any): Promise<import("./dto/profile.dto").SalaryInfoResponse>;
    getDocuments(userId: string, user: any): Promise<{
        documents: never[];
        byType: {};
        expiringDocuments: never[];
        totalCount: number;
    }>;
    getActivityTimeline(userId: string, limit: string, user: any): Promise<import("./dto/profile.dto").ActivityTimelineItem[]>;
    uploadDocument(userId: string, dto: UploadDocumentDto, file: Express.Multer.File, user: any): Promise<void>;
    createRequestOnBehalf(userId: string, dto: RequestOnBehalfDto, user: any): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LeaveStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LeaveType;
        endDate: Date;
        startDate: Date;
        notes: string | null;
        userId: string;
        requestedDays: number;
        approvedDays: number | null;
        reason: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        fullPayDays: number | null;
        partialPayDays: number | null;
        unpaidDays: number | null;
        salaryImpact: import("@prisma/client/runtime/library").Decimal | null;
        noticeDaysProvided: number | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
        leaveTypeConfigId: string | null;
    } | {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.LetterStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.LetterType;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        approverNotes: string | null;
        approvedAt: Date | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        approverId: string | null;
    } | {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        companyId: string | null;
        type: import(".prisma/client").$Enums.AdvanceType;
        endDate: Date;
        startDate: Date;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        periodMonths: number;
        monthlyDeduction: import("@prisma/client/runtime/library").Decimal;
        approvedAmount: import("@prisma/client/runtime/library").Decimal | null;
        approvedMonthlyDeduction: import("@prisma/client/runtime/library").Decimal | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
    }>;
    deleteDocument(userId: string, docId: string, user: any): Promise<void>;
}
