import { RaisesService } from './raises.service';
import { CreateRaiseRequestDto } from './dto/create-raise-request.dto';
import { ManagerDecisionDto, HRDecisionDto } from './dto/raise-decision.dto';
import { UploadService } from '../../common/upload/upload.service';
export declare class RaisesController {
    private readonly raisesService;
    private readonly uploadService;
    constructor(raisesService: RaisesService, uploadService: UploadService);
    uploadAttachments(files: Express.Multer.File[]): Promise<{
        message: string;
        files: import("../../common/upload/upload.service").UploadedFile[];
    }>;
    createRaiseRequest(userId: string, companyId: string, createRaiseDto: CreateRaiseRequestDto): Promise<{
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    }>;
    getMyRaiseRequests(userId: string, companyId: string): Promise<({
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    })[]>;
    getStats(userId: string, companyId: string): Promise<{
        pending: number;
        approved: number;
        rejected: number;
        total: number;
    }>;
    getRaiseRequestById(id: string, userId: string, companyId: string): Promise<{
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            branch: {
                id: string;
                name: string;
                nameEn: string | null;
                address: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                isActive: boolean;
                workStartTime: string;
                workEndTime: string;
                lateGracePeriod: number;
                geofenceRadius: number;
                latitude: import("@prisma/client/runtime/library").Decimal;
                longitude: import("@prisma/client/runtime/library").Decimal;
                timezone: string;
                earlyCheckInPeriod: number;
                earlyCheckOutPeriod: number;
                workingDays: string;
            } | null;
            department: {
                id: string;
                name: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                branchId: string;
                workStartTime: string | null;
                workEndTime: string | null;
            } | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    }>;
    cancelRaiseRequest(id: string, userId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    }>;
    getManagerInbox(managerId: string, companyId: string): Promise<({
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    })[]>;
    managerDecision(id: string, managerId: string, companyId: string, dto: ManagerDecisionDto): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    }>;
    getHRInbox(hrUserId: string, companyId: string): Promise<({
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    })[]>;
    hrDecision(id: string, hrUserId: string, companyId: string, dto: HRDecisionDto): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    }>;
    getFinanceInbox(financeUserId: string, companyId: string): Promise<({
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    })[]>;
    financeDecision(id: string, financeUserId: string, companyId: string, dto: any): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    }>;
    getCEOInbox(ceoUserId: string, companyId: string): Promise<({
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            salary: import("@prisma/client/runtime/library").Decimal | null;
            hireDate: Date | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        financeApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    })[]>;
    ceoDecision(id: string, ceoUserId: string, companyId: string, dto: any): Promise<{
        user: {
            id: string;
            firstName: string;
            lastName: string;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    }>;
    getAllRaiseRequests(companyId: string, status?: string): Promise<({
        user: {
            id: string;
            email: string;
            firstName: string;
            lastName: string;
            employeeCode: string | null;
            branch: {
                name: string;
            } | null;
            department: {
                name: string;
            } | null;
        };
        managerApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
        hrApprover: {
            id: string;
            firstName: string;
            lastName: string;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.RaiseStatus;
        companyId: string | null;
        type: import(".prisma/client").$Enums.RaiseType;
        amount: import("@prisma/client/runtime/library").Decimal;
        notes: string | null;
        userId: string;
        attachments: import("@prisma/client/runtime/library").JsonValue | null;
        currentStep: import(".prisma/client").$Enums.ApprovalStep;
        managerDecision: import(".prisma/client").$Enums.ApprovalDecision;
        managerDecisionAt: Date | null;
        managerNotes: string | null;
        managerAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        hrDecision: import(".prisma/client").$Enums.ApprovalDecision;
        hrDecisionAt: Date | null;
        hrDecisionNotes: string | null;
        hrAttachments: import("@prisma/client/runtime/library").JsonValue | null;
        managerApproverId: string | null;
        hrApproverId: string | null;
        financeDecision: import(".prisma/client").$Enums.ApprovalDecision;
        financeDecisionAt: Date | null;
        financeDecisionNotes: string | null;
        ceoDecision: import(".prisma/client").$Enums.ApprovalDecision;
        ceoDecisionAt: Date | null;
        ceoDecisionNotes: string | null;
        approvalChain: import("@prisma/client/runtime/library").JsonValue | null;
        financeApproverId: string | null;
        ceoApproverId: string | null;
        effectiveMonth: Date;
        appliedToSalary: boolean;
    })[]>;
}
