import { PrismaService } from '../../common/prisma/prisma.service';
import { GeofenceService } from './services/geofence.service';
import { NotificationsService } from '../notifications/notifications.service';
import { PermissionsService } from '../permissions/permissions.service';
import { TimezoneService } from '../../common/services/timezone.service';
import { SettingsService } from '../settings/settings.service';
import { CheckInDto } from './dto/check-in.dto';
import { CheckOutDto } from './dto/check-out.dto';
import { AttendanceQueryDto } from './dto/attendance-query.dto';
import { SmartPolicyTriggerService } from '../smart-policies/smart-policy-trigger.service';
export declare class AttendanceService {
    private prisma;
    private geofenceService;
    private notificationsService;
    private permissionsService;
    private smartPolicyTrigger;
    private timezoneService;
    private settingsService;
    private readonly FACE_THRESHOLD;
    constructor(prisma: PrismaService, geofenceService: GeofenceService, notificationsService: NotificationsService, permissionsService: PermissionsService, smartPolicyTrigger: SmartPolicyTriggerService, timezoneService: TimezoneService, settingsService: SettingsService);
    checkIn(userId: string, checkInDto: CheckInDto): Promise<{
        message: string;
        attendance: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        };
        lateMinutes: number;
        isLate: boolean;
    }>;
    checkOut(userId: string, checkOutDto: CheckOutDto): Promise<{
        message: string;
        attendance: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        };
        earlyLeaveMinutes: number;
        isEarlyLeave: boolean;
        workingMinutes: number;
        overtimeMinutes: number;
    }>;
    getTodayAttendance(userId: string, companyId: string): Promise<{
        attendance: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        } | null;
        faceRegistered: boolean;
        workSchedule: {
            startTime: string | undefined;
            endTime: string | undefined;
            lateGracePeriod: number | undefined;
            earlyCheckInPeriod: number | undefined;
        };
    }>;
    getAttendanceHistory(userId: string, companyId: string, query: AttendanceQueryDto): Promise<{
        data: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        }[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    getMonthlyStats(userId: string, companyId: string, year: number, month: number): Promise<{
        year: number;
        month: number;
        stats: {
            totalDays: number;
            presentDays: number;
            lateDays: number;
            earlyLeaveDays: number;
            absentDays: number;
            workFromHomeDays: number;
            onLeaveDays: number;
            totalWorkingMinutes: number;
            totalOvertimeMinutes: number;
            totalLateMinutes: number;
            totalEarlyLeaveMinutes: number;
        };
        attendances: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        }[];
    }>;
    getAllAttendance(userId: string, companyId: string, query: AttendanceQueryDto): Promise<{
        data: ({
            user: {
                id: string;
                firstName: string;
                lastName: string;
                employeeCode: string | null;
                jobTitle: string | null;
                department: {
                    name: string;
                } | null;
            };
            branch: {
                name: string;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.AttendanceStatus;
            companyId: string | null;
            branchId: string;
            notes: string | null;
            lateMinutes: number;
            date: Date;
            checkInTime: Date | null;
            checkOutTime: Date | null;
            checkInLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkInDistance: number | null;
            checkOutLatitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutLongitude: import("@prisma/client/runtime/library").Decimal | null;
            checkOutDistance: number | null;
            earlyLeaveMinutes: number;
            workingMinutes: number;
            overtimeMinutes: number;
            isWorkFromHome: boolean;
            isMockLocation: boolean;
            deviceInfo: string | null;
            checkInFaceVerified: boolean;
            checkInFaceConfidence: number | null;
            checkOutFaceVerified: boolean;
            checkOutFaceConfidence: number | null;
            userId: string;
        })[];
        pagination: {
            page: number;
            limit: number;
            total: number;
            totalPages: number;
        };
    }>;
    getDailyStats(companyId: string, date?: Date): Promise<{
        date: Date;
        totalEmployees: number;
        presentCount: number;
        lateCount: number;
        earlyLeaveCount: number;
        lateAndEarlyCount: number;
        absentCount: number;
        workFromHomeCount: number;
    }>;
    private parseTime;
    private logSuspiciousAttempt;
    private notifyAdminSuspiciousActivity;
    private notifyAdminLateCheckIn;
    private notifyAdminEarlyCheckOut;
    private cosineSimilarity;
}
