import { PrismaService } from '../../common/prisma/prisma.service';
import { AuditService } from '../audit/audit.service';
import { CreatePolicyDto, PolicyType } from './dto/create-policy.dto';
import { FormulaEngineService } from '../payroll-calculation/services/formula-engine.service';
export declare class PoliciesService {
    private prisma;
    private auditService;
    private formulaEngine;
    private readonly logger;
    constructor(prisma: PrismaService, auditService: AuditService, formulaEngine: FormulaEngineService);
    create(dto: CreatePolicyDto, companyId: string, createdById: string): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    findAll(companyId: string, type?: PolicyType): Promise<({
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    })[]>;
    findOne(id: string, companyId: string): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    update(id: string, companyId: string, dto: Partial<CreatePolicyDto>, updatedById?: string): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    delete(id: string, companyId: string, deletedById?: string): Promise<{
        success: boolean;
    }>;
    toggleActive(id: string, companyId: string, toggledById?: string): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    resolvePolicy(type: PolicyType, employeeId: string, companyId: string, date?: Date): Promise<{
        rules: ({
            outputComponent: {
                id: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                code: string;
                nameAr: string;
                type: import(".prisma/client").$Enums.SalaryComponentType;
                nature: import(".prisma/client").$Enums.SalaryComponentNature;
                description: string | null;
                gosiEligible: boolean;
                otEligible: boolean;
                eosEligible: boolean;
                isProrated: boolean;
                taxable: boolean;
                formula: string | null;
                version: number;
                effectiveDate: Date;
                endDate: Date | null;
                isActive: boolean;
                roundingMode: string;
                decimals: number;
                priority: number;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        })[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    addRule(policyId: string, companyId: string, ruleData: any): Promise<{
        outputComponent: {
            id: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            code: string;
            nameAr: string;
            type: import(".prisma/client").$Enums.SalaryComponentType;
            nature: import(".prisma/client").$Enums.SalaryComponentNature;
            description: string | null;
            gosiEligible: boolean;
            otEligible: boolean;
            eosEligible: boolean;
            isProrated: boolean;
            taxable: boolean;
            formula: string | null;
            version: number;
            effectiveDate: Date;
            endDate: Date | null;
            isActive: boolean;
            roundingMode: string;
            decimals: number;
            priority: number;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        nameAr: string;
        isActive: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        valueType: string;
        value: string;
        outputSign: import(".prisma/client").$Enums.OutputSign;
        ruleOrder: number;
        outputComponentId: string | null;
        policyId: string;
    }>;
    deleteRule(ruleId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        nameAr: string;
        isActive: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        valueType: string;
        value: string;
        outputSign: import(".prisma/client").$Enums.OutputSign;
        ruleOrder: number;
        outputComponentId: string | null;
        policyId: string;
    }>;
    evaluateRules(policy: any, context: Record<string, any>): {
        rule: any;
        value: any;
    } | null;
    private matchesConditions;
    private computeRuleValue;
    private evaluateFormula;
    getPolicyValue(type: string, employeeId: string, companyId: string, context: Record<string, any>, date?: Date): Promise<{
        policy: any;
        rule: any;
        value: any;
    } | null>;
    getPolicySetting(type: string, employeeId: string, companyId: string, settingKey: string, defaultValue?: any, date?: Date): Promise<any>;
}
