import { PoliciesService } from './policies.service';
import { CreatePolicyDto, PolicyType } from './dto/create-policy.dto';
export declare class PoliciesController {
    private readonly service;
    constructor(service: PoliciesService);
    create(dto: CreatePolicyDto, userId: string, companyId: string): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    findAll(companyId: string, type?: PolicyType): Promise<({
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    })[]>;
    findOne(id: string, companyId: string): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    resolve(employeeId: string, companyId: string, type: PolicyType, date?: string): Promise<{
        rules: ({
            outputComponent: {
                id: string;
                nameEn: string | null;
                createdAt: Date;
                updatedAt: Date;
                companyId: string | null;
                code: string;
                nameAr: string;
                type: import(".prisma/client").$Enums.SalaryComponentType;
                nature: import(".prisma/client").$Enums.SalaryComponentNature;
                description: string | null;
                gosiEligible: boolean;
                otEligible: boolean;
                eosEligible: boolean;
                isProrated: boolean;
                taxable: boolean;
                formula: string | null;
                version: number;
                effectiveDate: Date;
                endDate: Date | null;
                isActive: boolean;
                roundingMode: string;
                decimals: number;
                priority: number;
            } | null;
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        })[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    update(id: string, companyId: string, dto: Partial<CreatePolicyDto>): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    toggleActive(id: string, companyId: string): Promise<{
        rules: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            code: string;
            nameAr: string;
            isActive: boolean;
            conditions: import("@prisma/client/runtime/library").JsonValue;
            valueType: string;
            value: string;
            outputSign: import(".prisma/client").$Enums.OutputSign;
            ruleOrder: number;
            outputComponentId: string | null;
            policyId: string;
        }[];
    } & {
        id: string;
        nameEn: string | null;
        createdAt: Date;
        updatedAt: Date;
        jobTitleId: string | null;
        companyId: string | null;
        branchId: string | null;
        departmentId: string | null;
        code: string;
        nameAr: string;
        type: import(".prisma/client").$Enums.PolicyType;
        description: string | null;
        isActive: boolean;
        priority: number;
        employeeId: string | null;
        scope: import(".prisma/client").$Enums.PolicyScope;
        effectiveFrom: Date;
        settings: import("@prisma/client/runtime/library").JsonValue;
        effectiveTo: Date | null;
        scopeRank: number;
        createdById: string | null;
    }>;
    remove(id: string, companyId: string): Promise<{
        success: boolean;
    }>;
    addRule(id: string, companyId: string, ruleData: any): Promise<{
        outputComponent: {
            id: string;
            nameEn: string | null;
            createdAt: Date;
            updatedAt: Date;
            companyId: string | null;
            code: string;
            nameAr: string;
            type: import(".prisma/client").$Enums.SalaryComponentType;
            nature: import(".prisma/client").$Enums.SalaryComponentNature;
            description: string | null;
            gosiEligible: boolean;
            otEligible: boolean;
            eosEligible: boolean;
            isProrated: boolean;
            taxable: boolean;
            formula: string | null;
            version: number;
            effectiveDate: Date;
            endDate: Date | null;
            isActive: boolean;
            roundingMode: string;
            decimals: number;
            priority: number;
        } | null;
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        nameAr: string;
        isActive: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        valueType: string;
        value: string;
        outputSign: import(".prisma/client").$Enums.OutputSign;
        ruleOrder: number;
        outputComponentId: string | null;
        policyId: string;
    }>;
    deleteRule(ruleId: string, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        code: string;
        nameAr: string;
        isActive: boolean;
        conditions: import("@prisma/client/runtime/library").JsonValue;
        valueType: string;
        value: string;
        outputSign: import(".prisma/client").$Enums.OutputSign;
        ruleOrder: number;
        outputComponentId: string | null;
        policyId: string;
    }>;
}
