import { PrismaService } from '../../common/prisma/prisma.service';
import { CreatePayrollPeriodDto } from './dto/create-payroll-period.dto';
export declare class PayrollPeriodsService {
    private prisma;
    constructor(prisma: PrismaService);
    create(dto: CreatePayrollPeriodDto, companyId: string): Promise<{
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PayrollStatus;
        companyId: string | null;
        endDate: Date;
        month: number;
        year: number;
        startDate: Date;
        cutOffDate: Date | null;
        inputsLockedAt: Date | null;
        lockedAt: Date | null;
        lockedBy: string | null;
    }>;
    findAll(companyId: string): Promise<({
        _count: {
            payslips: number;
        };
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PayrollStatus;
        companyId: string | null;
        endDate: Date;
        month: number;
        year: number;
        startDate: Date;
        cutOffDate: Date | null;
        inputsLockedAt: Date | null;
        lockedAt: Date | null;
        lockedBy: string | null;
    })[]>;
    findOne(id: string, companyId: string): Promise<{
        payslips: ({
            employee: {
                id: string;
                phone: string | null;
                email: string;
                createdAt: Date;
                updatedAt: Date;
                password: string;
                firstName: string;
                lastName: string;
                avatar: string | null;
                employeeCode: string | null;
                jobTitle: string | null;
                role: import(".prisma/client").$Enums.Role;
                status: import(".prisma/client").$Enums.UserStatus;
                salary: import("@prisma/client/runtime/library").Decimal | null;
                hireDate: Date | null;
                nationality: string | null;
                isSaudi: boolean;
                fcmToken: string | null;
                nationalId: string | null;
                iqamaNumber: string | null;
                iqamaExpiryDate: Date | null;
                borderNumber: string | null;
                passportNumber: string | null;
                passportExpiryDate: Date | null;
                professionCode: string | null;
                profession: string | null;
                dateOfBirth: Date | null;
                gender: string | null;
                gosiNumber: string | null;
                maritalStatus: string | null;
                isSuperAdmin: boolean;
                jobTitleId: string | null;
                annualLeaveDays: number;
                usedLeaveDays: number;
                remainingLeaveDays: number;
                faceRegistered: boolean;
                companyId: string | null;
                branchId: string | null;
                departmentId: string | null;
                managerId: string | null;
                costCenterId: string | null;
                jobFamilyId: string | null;
                roleLevelId: string | null;
            };
        } & {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            periodId: string;
            baseSalary: import("@prisma/client/runtime/library").Decimal;
            grossSalary: import("@prisma/client/runtime/library").Decimal;
            totalDeductions: import("@prisma/client/runtime/library").Decimal;
            netSalary: import("@prisma/client/runtime/library").Decimal;
            calculationTrace: import("@prisma/client/runtime/library").JsonValue | null;
            employeeId: string;
            runId: string | null;
        })[];
        runs: {
            id: string;
            createdAt: Date;
            updatedAt: Date;
            status: import(".prisma/client").$Enums.PayrollStatus;
            companyId: string | null;
            lockedAt: Date | null;
            lockedBy: string | null;
            periodId: string;
            runDate: Date;
            processedBy: string | null;
            isAdjustment: boolean;
            originalRunId: string | null;
            adjustmentReason: string | null;
            calculatedAt: Date | null;
            calculatedBy: string | null;
            hrApprovedAt: Date | null;
            hrApprovedBy: string | null;
            financeApprovedAt: Date | null;
            financeApprovedBy: string | null;
            paidAt: Date | null;
        }[];
    } & {
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: import(".prisma/client").$Enums.PayrollStatus;
        companyId: string | null;
        endDate: Date;
        month: number;
        year: number;
        startDate: Date;
        cutOffDate: Date | null;
        inputsLockedAt: Date | null;
        lockedAt: Date | null;
        lockedBy: string | null;
    }>;
    updateStatus(id: string, companyId: string, status: any): Promise<import(".prisma/client").Prisma.BatchPayload>;
}
